package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode
import de.visualdigits.common.domain.model.geodata.Location
                 
object PortsMY {
    val PORTS: List<PortCode> = listOf(
        PortCode("MY", "ABU", "Abu", Location(6.116667, 105.283333)),
        PortCode("MY", "ANG", "Angsi", Location(5.083333, 104.683333)),
        PortCode("MY", "ASQ", "Teronoh", Location(4.416667, 100.983333)),
        PortCode("MY", "BAG", "Bagan Datok", null),
        PortCode("MY", "BAK", "Batang Kali", Location(3.466667, 101.633333)),
        PortCode("MY", "BAT", "Batu Pahat", null),
        PortCode("MY", "BAU", "Bau, Sarawak", null),
        PortCode("MY", "BBA", "Batu Batu, Sabah", Location(5.033333, 115.95)),
        PortCode("MY", "BDV", "Bandau, Sabah", Location(6.5, 116.766667)),
        PortCode("MY", "BEA", "Beaufort", Location(5.333333, 115.75)),
        PortCode("MY", "BEL", "Beluran, Sabah", Location(5.883333, 117.55)),
        PortCode("MY", "BGG", "Bunan Gega, Sarawak", null),
        PortCode("MY", "BGR", "Bunga Raya", Location(6.95, 104.1)),
        PortCode("MY", "BGU", "Bangau", Location(6.95, 116.7)),
        PortCode("MY", "BIA", "Biawak, Sarawak", null),
        PortCode("MY", "BKI", "Kota Kinabalu, Sabah", Location(5.966667, 116.066667)),
        PortCode("MY", "BKP", "Bakapit", null),
        PortCode("MY", "BLG", "Belaga, Sarawak", null),
        PortCode("MY", "BLI", "Batu Lintang, Sarawak", null),
        PortCode("MY", "BMA", "Bandar Maharani", null),
        PortCode("MY", "BNG", "Binatang, Sarawak", null),
        PortCode("MY", "BNT", "Benut, Johor", null),
        PortCode("MY", "BRU", "Pulau Bruit", Location(2.583333, 111.333333)),
        PortCode("MY", "BSE", "Sematan, Sarawak", null),
        PortCode("MY", "BST", "Kuala Besut", Location(5.833333, 102.566667)),
        PortCode("MY", "BTG", "Betong, Sarawak", null),
        PortCode("MY", "BTK", "Bandar Tenggara", Location(1.866667, 103.616667)),
        PortCode("MY", "BTM", "Batu Maung", Location(5.283333, 100.283333)),
        PortCode("MY", "BTN", "Bintangor", null),
        PortCode("MY", "BTU", "Bintulu, Sarawak", null),
        PortCode("MY", "BTW", "Batu Kawan", Location(5.25, 100.416667)),
        PortCode("MY", "BWH", "Bagan Luar (Butterworth)", null),
        PortCode("MY", "CEN", "Cendor", Location(5.566667, 104.55)),
        PortCode("MY", "DDW", "Danjindawai", null),
        PortCode("MY", "DGN", "Kuala Dungun", Location(4.783333, 103.433333)),
        PortCode("MY", "DRO", "Daro, Sarawak", null),
        PortCode("MY", "END", "Endau", null),
        PortCode("MY", "HUM", "Hutan Melintang", Location(3.883333, 100.933333)),
        PortCode("MY", "JAM", "Jambongan, Sabah", Location(6.666667, 117.5)),
        PortCode("MY", "JEL", "Jelutong", Location(5.4, 100.316667)),
        PortCode("MY", "JHB", "Johor Bahru", null),
        PortCode("MY", "KAB", "Kabong, Sarawak", null),
        PortCode("MY", "KBA", "Kuala Baram", Location(4.566667, 113.983333)),
        PortCode("MY", "KBD", "Kota Belud, Sabah", Location(6.35, 116.433333)),
        PortCode("MY", "KBE", "Kuala Belud, Sabah", null),
        PortCode("MY", "KBR", "Kota Bharu", null),
        PortCode("MY", "KBS", "Kuala Besar", null),
        PortCode("MY", "KCH", "Kuching, Sarawak", null),
        PortCode("MY", "KEM", "Kemaman", null),
        PortCode("MY", "KES", "Kejit", null),
        PortCode("MY", "KET", "Kertih", Location(4.516667, 103.45)),
        PortCode("MY", "KIJ", "Kijal", null),
        PortCode("MY", "KIM", "Kimanis, Sabah", Location(5.616667, 115.9)),
        PortCode("MY", "KKH", "Kuala Kedah", null),
        PortCode("MY", "KKP", "Kukup", null),
        PortCode("MY", "KPN", "Kepong", Location(3.216667, 101.633333)),
        PortCode("MY", "KPS", "Kuala Perlis", null),
        PortCode("MY", "KPU", "Kuala Penyu, Sabah", null),
        PortCode("MY", "KRE", "Krety", null),
        PortCode("MY", "KSD", "Kuala Sedili", null),
        PortCode("MY", "KSG", "Kuala Segama, Sabah", null),
        PortCode("MY", "KSL", "Kuala Selangor", Location(3.333333, 101.05)),
        PortCode("MY", "KSS", "Kota Sarang Semut", Location(56.5, 102.666667)),
        PortCode("MY", "KTI", "Kota Tinggi", null),
        PortCode("MY", "KUA", "Kuantan (Tanjong Gelang)", null),
        PortCode("MY", "KUD", "Kudat, Sabah", null),
        PortCode("MY", "KUG", "Kuala Gula", null),
        PortCode("MY", "KUN", "Kunak, Sabah", null),
        PortCode("MY", "LAU", "Pulau Indah", Location(2.933333, 101.316667)),
        PortCode("MY", "LBH", "Labuan Haji", Location(4.483333, 118.633333)),
        PortCode("MY", "LBU", "Labuan, Sabah", Location(5.283333, 115.233333)),
        PortCode("MY", "LDU", "Lahad Datu, Sabah", null),
        PortCode("MY", "LGG", "Lingga, Sarawak", null),
        PortCode("MY", "LGK", "Langkawi", Location(6.366667, 99.8)),
        PortCode("MY", "LMN", "Limbang, Sarawak", null),
        PortCode("MY", "LPK", "Northport/Pt Klang", null),
        PortCode("MY", "LUM", "Lumut", null),
        PortCode("MY", "LUN", "Lundu, Sarawak", null),
        PortCode("MY", "LUT", "Lutong, Sarawak", null),
        PortCode("MY", "LWY", "Lawas, Sarawak", null),
        PortCode("MY", "MAN", "Manjung", Location(4.15, 100.616667)),
        PortCode("MY", "MBK", "Merbok", Location(5.716667, 100.416667)),
        PortCode("MY", "MBS", "Menumbok", Location(5.3, 115.366667)),
        PortCode("MY", "MEM", "Mempakul, Sabah", null),
        PortCode("MY", "MEN", "Nenasi", Location(3.133333, 103.45)),
        PortCode("MY", "MEP", "Mersing", null),
        PortCode("MY", "MKM", "Mukah, Sarawak", null),
        PortCode("MY", "MKZ", "Malacca", null),
        PortCode("MY", "MUA", "Muar", null),
        PortCode("MY", "MUD", "Muda Marine Terminal", Location(7.583333, 102.983333)),
        PortCode("MY", "MUR", "Marudi, Sarawak", null),
        PortCode("MY", "MYY", "Miri, Sarawak", null),
        PortCode("MY", "NII", "Nilai", Location(2.816667, 101.8)),
        PortCode("MY", "PAL", "Paloh, Sarawak", null),
        PortCode("MY", "PAN", "Panchang", null),
        PortCode("MY", "PAS", "Pasir Gogok", null),
        PortCode("MY", "PBA", "Pulau Batik, Sabah", null),
        PortCode("MY", "PDI", "Port Dickson", null),
        PortCode("MY", "PED", "Pedena", null),
        PortCode("MY", "PEN", "Penang (Georgetown)", Location(5.416667, 100.316667)),
        PortCode("MY", "PGG", "Pengerang", Location(1.366667, 104.116667)),
        PortCode("MY", "PGU", "Pasir Gudang, Johor", null),
        PortCode("MY", "PHI", "Pasir Hitam", null),
        PortCode("MY", "PJK", "Pulau Jarak", Location(3.966667, 100.083333)),
        PortCode("MY", "PKG", "Port Klang (Pelabuhan Klang)", Location(3.0, 101.4)),
        PortCode("MY", "PKK", "Pengkalan Kubor", null),
        PortCode("MY", "PMT", "Penara Marine Terminal", Location(6.116667, 105.016667)),
        PortCode("MY", "PND", "Pending", Location(1.55, 110.383333)),
        PortCode("MY", "POW", "Pontian", null),
        PortCode("MY", "PPI", "Pulau Pisang", null),
        PortCode("MY", "PRA", "Perai", Location(5.383333, 100.383333)),
        PortCode("MY", "PRN", "Kuala Rompin", null),
        PortCode("MY", "PTB", "Pulau Tambisan, Sabah", null),
        PortCode("MY", "PUN", "Punang, Sarawak", null),
        PortCode("MY", "REJ", "Rejang, Sarawak", null),
        PortCode("MY", "SAM", "Samu", Location(1.55, 111.533333)),
        PortCode("MY", "SAR", "Sarikei", Location(2.116667, 111.516667)),
        PortCode("MY", "SBT", "Sabahat", Location(5.066667, 119.033333)),
        PortCode("MY", "SBW", "Sibu, Sarawak", null),
        PortCode("MY", "SDK", "Sandakan, Sabah", null),
        PortCode("MY", "SDM", "Sindumin", null),
        PortCode("MY", "SDR", "Sundar, Sarawak", null),
        PortCode("MY", "SEJ", "Sejingkat, Sarawak", null),
        PortCode("MY", "SEL", "Selalang, Sarawak", null),
        PortCode("MY", "SEP", "Sepang, Selangor", Location(2.7, 101.75)),
        PortCode("MY", "SGG", "Sungai Udang", Location(2.25, 102.083333)),
        PortCode("MY", "SGM", "Segamat", Location(2.5, 102.816667)),
        PortCode("MY", "SHA", "Shah Alam", null),
        PortCode("MY", "SIJ", "Sijingkat", null),
        PortCode("MY", "SIL", "Silay", null),
        PortCode("MY", "SIP", "Samalaju", Location(3.95, 113.533333)),
        PortCode("MY", "SIR", "Siran", null),
        PortCode("MY", "SME", "Sri Medan", null),
        PortCode("MY", "SMG", "Simanggang, Sarawak", null),
        PortCode("MY", "SMJ", "Simunjan, Sarawak", null),
        PortCode("MY", "SMM", "Semporna, Sabah", null),
        PortCode("MY", "SNP", "North Pt", null),
        PortCode("MY", "SNR", "Senari - Sarawak", Location(1.6, 110.433333)),
        PortCode("MY", "SPG", "Simpangan, Sabah", null),
        PortCode("MY", "SPT", "Sipitang, Sabah", null),
        PortCode("MY", "SRE", "Sungai Rengit", null),
        PortCode("MY", "SRK", "Sirikin, Sarawak", null),
        PortCode("MY", "SUM", "Sungai Merah", Location(2.333333, 111.833333)),
        PortCode("MY", "SUP", "Sungai Udang Port", Location(2.25, 102.133333)),
        PortCode("MY", "SUW", "Sungai Way", Location(3.083333, 101.616667)),
        PortCode("MY", "TAG", "Tanjung Lembung", Location(6.283333, 99.783333)),
        PortCode("MY", "TAI", "Tampoi", Location(1.483333, 103.683333)),
        PortCode("MY", "TAS", "Telok Intan", null),
        PortCode("MY", "TAT", "Tapis Terminal", null),
        PortCode("MY", "TBA", "Tanjong Baran", null),
        PortCode("MY", "TBE", "Tanjong Berhala", null),
        PortCode("MY", "TBI", "Tanjong Bin", Location(1.333333, 103.55)),
        PortCode("MY", "TDA", "Tanjong Dawai", null),
        PortCode("MY", "TEN", "Tengku, Sabah", null),
        PortCode("MY", "TGE", "Tanjung Gelang", Location(3.983333, 103.416667)),
        PortCode("MY", "TGG", "Kuala Terengganu", null),
        PortCode("MY", "TJH", "Batu Gajah", Location(4.466667, 101.05)),
        PortCode("MY", "TKI", "Tanjong Kidurong", null),
        PortCode("MY", "TKP", "Kampong Tanjong Kupang", Location(1.35, 103.583333)),
        PortCode("MY", "TLA", "Kampung Tanjung Langsat", Location(1.466667, 104.016667)),
        PortCode("MY", "TMB", "Tumbum", null),
        PortCode("MY", "TMG", "Tomanggong", null),
        PortCode("MY", "TMP", "Tanjung Manis", Location(2.133333, 111.35)),
        PortCode("MY", "TOD", "Tioman", null),
        PortCode("MY", "TPP", "Tanjung Pelepas", Location(1.366667, 103.55)),
        PortCode("MY", "TRB", "Teluk Rubiah", Location(49.816667, 100.616667)),
        PortCode("MY", "TRM", "Telok Ramunia", null),
        PortCode("MY", "TSR", "Tanjong Surat", null),
        PortCode("MY", "TTE", "Tandjung Tengelili", null),
        PortCode("MY", "TUB", "Tubau", Location(3.133333, 113.7)),
        PortCode("MY", "TUM", "Tumpat", null),
        PortCode("MY", "TUN", "Tungku", null),
        PortCode("MY", "TWU", "Tawau, Sabah", null),
        PortCode("MY", "WAL", "Wallace Bay, Sabah", null),
        PortCode("MY", "WES", "Weston, Sabah", null),
        PortCode("MY", "XPQ", "Port Klang (Ferry Port)", Location(3.016667, 101.366667))
    )
}
