package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode
import de.visualdigits.common.domain.model.geodata.Location
                 
object PortsDK {
    val PORTS: List<PortCode> = listOf(
        PortCode("DK", "AAB", "Åbenrå", Location(55.033333, 9.433333)),
        PortCode("DK", "AAL", "Aalborg", null),
        PortCode("DK", "AAR", "Aarhus", Location(56.15, 10.216667)),
        PortCode("DK", "AGE", "Allinge", Location(55.266667, 14.8)),
        PortCode("DK", "AGH", "Agger Havn", null),
        PortCode("DK", "AGO", "Agersø", null),
        PortCode("DK", "AK3", "Åkirkeby", Location(55.066667, 14.933333)),
        PortCode("DK", "ANH", "Anholt", null),
        PortCode("DK", "ARD", "Årosund", Location(55.25, 9.716667)),
        PortCode("DK", "ARK", "Ærøskøbing", null),
        PortCode("DK", "ARO", "Åro", Location(55.266667, 9.75)),
        PortCode("DK", "ASA", "Asaa", Location(57.15, 10.416667)),
        PortCode("DK", "ASH", "Aggersund", null),
        PortCode("DK", "ASK", "Askø", null),
        PortCode("DK", "ASN", "Assens", null),
        PortCode("DK", "ASV", "Asnæsværkets Havn", null),
        PortCode("DK", "AUB", "Augustenborg", null),
        PortCode("DK", "AVE", "Avedøreværkets Havn", null),
        PortCode("DK", "AVK", "Avernak By", Location(55.033333, 10.266667)),
        PortCode("DK", "AVN", "Avernakke Havn", Location(55.3, 10.783333)),
        PortCode("DK", "BAG", "Bagenkop", null),
        PortCode("DK", "BAL", "Ballen", Location(55.816667, 10.65)),
        PortCode("DK", "BBG", "Bøvlingbjerg", Location(56.433333, 8.2)),
        PortCode("DK", "BDX", "Bandholm", null),
        PortCode("DK", "BGO", "Baagø", null),
        PortCode("DK", "BGZ", "Bogense", Location(55.566667, 10.083333)),
        PortCode("DK", "BLA", "Blavand", Location(55.55, 8.133333)),
        PortCode("DK", "BLB", "Ballebro", null),
        PortCode("DK", "BLU", "Baelum", Location(56.816667, 10.1)),
        PortCode("DK", "BOG", "Bogo By", Location(54.933333, 12.05)),
        PortCode("DK", "BOS", "Bøjden", Location(55.1, 10.083333)),
        PortCode("DK", "BRB", "Brabrand", null),
        PortCode("DK", "BRH", "Branden Havn", null),
        PortCode("DK", "CPH", "København", Location(55.666667, 12.583333)),
        PortCode("DK", "CSO", "Christiansø Havn", Location(55.316667, 15.183333)),
        PortCode("DK", "DAN", "Cementfabriken Dania", null),
        PortCode("DK", "DAS", "Dansk Salts Havn", null),
        PortCode("DK", "DN6", "Dannemare", Location(54.75, 11.2)),
        PortCode("DK", "DRA", "Dragør", null),
        PortCode("DK", "DYS", "Dyssegard", Location(55.733333, 12.533333)),
        PortCode("DK", "EBJ", "Esbjerg", null),
        PortCode("DK", "EBT", "Ebeltoft", null),
        PortCode("DK", "EDL", "Endelave", null),
        PortCode("DK", "EGN", "Egense", null),
        PortCode("DK", "EK4", "Eskilstrup", Location(55.85, 11.633333)),
        PortCode("DK", "END", "Egernsund", null),
        PortCode("DK", "ENS", "Enstedværket Havn", Location(55.016667, 9.433333)),
        PortCode("DK", "EOT", "Styrtom", Location(55.016667, 9.433333)),
        PortCode("DK", "FAA", "Faaborg", null),
        PortCode("DK", "FAK", "Fakse Ladeplads Havn", null),
        PortCode("DK", "FDH", "Frederikshavn", null),
        PortCode("DK", "FDS", "Frederikssund", Location(55.833333, 12.066667)),
        PortCode("DK", "FDV", "Frederiksværk", null),
        PortCode("DK", "FEJ", "Fejø", null),
        PortCode("DK", "FER", "Ferritslev", Location(55.3, 10.583333)),
        PortCode("DK", "FGS", "Feggesund", null),
        PortCode("DK", "FMO", "Femø", null),
        PortCode("DK", "FRC", "Fredericia", null),
        PortCode("DK", "FRK", "Føvling", Location(55.45, 8.95)),
        PortCode("DK", "FUH", "Fur", null),
        PortCode("DK", "FYH", "Fynshav", Location(54.966667, 9.966667)),
        PortCode("DK", "GDM", "Gudhjem", Location(55.216667, 14.966667)),
        PortCode("DK", "GED", "Gedser", null),
        PortCode("DK", "GFH", "Gulfhavn", null),
        PortCode("DK", "GLY", "Glyngøre", null),
        PortCode("DK", "GRA", "Gråsten", null),
        PortCode("DK", "GRE", "Grenaa", null),
        PortCode("DK", "GTS", "Glatved Strand", Location(56.3, 105.316667)),
        PortCode("DK", "HAD", "Haderslev", null),
        PortCode("DK", "HAN", "Hanstholm", null),
        PortCode("DK", "HAS", "Hals", null),
        PortCode("DK", "HBA", "Humlebæk", Location(55.966667, 12.516667)),
        PortCode("DK", "HBK", "Holbæk", null),
        PortCode("DK", "HBO", "Hobro", null),
        PortCode("DK", "HDH", "Hardeshøj", null),
        PortCode("DK", "HEJ", "Hejls", Location(55.383333, 9.6)),
        PortCode("DK", "HER", "Herning", null),
        PortCode("DK", "HHV", "Hammerhavn", Location(55.283333, 14.75)),
        PortCode("DK", "HIR", "Hirtshals", null),
        PortCode("DK", "HJ3", "Højby", Location(55.333333, 10.45)),
        PortCode("DK", "HJT", "Hjerting", Location(55.516667, 8.366667)),
        PortCode("DK", "HLS", "Helsingør", null),
        PortCode("DK", "HNB", "Havneby", null),
        PortCode("DK", "HOH", "Hou Havn", null),
        PortCode("DK", "HOR", "Horsens", null),
        PortCode("DK", "HSB", "Holstebro", null),
        PortCode("DK", "HSL", "Hasle", null),
        PortCode("DK", "HSU", "Hadsund", Location(56.716667, 10.1)),
        PortCode("DK", "HUN", "Hundested", null),
        PortCode("DK", "HVA", "Hvalpsund", null),
        PortCode("DK", "HVN", "Havnsø", null),
        PortCode("DK", "HVS", "Hvide Sande", Location(55.983333, 8.133333)),
        PortCode("DK", "HVT", "Hellebæk", Location(56.066667, 12.566667)),
        PortCode("DK", "HWO", "Hov", Location(55.916667, 10.25)),
        PortCode("DK", "JEL", "Jelling", Location(55.75, 9.433333)),
        PortCode("DK", "JUE", "Juelsminde", Location(55.7, 10.016667)),
        PortCode("DK", "KAL", "Kalundborg", null),
        PortCode("DK", "KAR", "Karlslunde", Location(55.566667, 12.216667)),
        PortCode("DK", "KBG", "Klintebjerg", Location(55.483333, 10.45)),
        PortCode("DK", "KBK", "Karrebæksminde", Location(55.183333, 11.666667)),
        PortCode("DK", "KBY", "Kyndbyvaerkets Havn", null),
        PortCode("DK", "KDM", "Kollund Mole", Location(54.333333, 9.45)),
        PortCode("DK", "KGL", "Kongsdal Harbour", Location(56.7, 10.066667)),
        PortCode("DK", "KHV", "Knudshoved", null),
        PortCode("DK", "KII", "Saint Kilian", null),
        PortCode("DK", "KK4", "Åbybro", Location(57.15, 9.75)),
        PortCode("DK", "KLH", "Klintholm Havn", Location(57.95, 12.466667)),
        PortCode("DK", "KLP", "Kleppen", Location(56.533333, 8.583333)),
        PortCode("DK", "KOG", "Køge", null),
        PortCode("DK", "KOK", "Kolby Kås", Location(55.8, 10.55)),
        PortCode("DK", "KOL", "Kolding", null),
        PortCode("DK", "KON", "Cementfabrikken Kongsdal Havn", null),
        PortCode("DK", "KRA", "Kragenæs", null),
        PortCode("DK", "KRR", "Korsør", null),
        PortCode("DK", "KT4", "Kettinge", Location(54.7, 11.75)),
        PortCode("DK", "KTD", "Kerteminde", null),
        PortCode("DK", "KTP", "Kastrup", null),
        PortCode("DK", "KVR", "Kværndrup", null),
        PortCode("DK", "LGR", "Løgstør", null),
        PortCode("DK", "LHH", "Lindholm Havn", Location(55.283333, 10.8)),
        PortCode("DK", "LIN", "Lindø Havn", null),
        PortCode("DK", "LOH", "Lohals", null),
        PortCode("DK", "LUN", "Lundeborg", Location(55.133333, 10.783333)),
        PortCode("DK", "LVG", "Lemvig", null),
        PortCode("DK", "LYO", "Lyngs Odde Havn", null),
        PortCode("DK", "MAS", "Masnedø", null),
        PortCode("DK", "MID", "Middelfart", null),
        PortCode("DK", "MKH", "Masnedovaerkets Havn/Vordingborg", Location(54.966667, 11.883333)),
        PortCode("DK", "MNS", "Masnedsund", Location(55.0, 11.866667)),
        PortCode("DK", "MOM", "Mommark", null),
        PortCode("DK", "MRB", "Marbæk Havn", null),
        PortCode("DK", "MRR", "Mariager", Location(56.65, 10.0)),
        PortCode("DK", "MRS", "Marstal", null),
        PortCode("DK", "N3S", "Nykobing Sjaelland", Location(55.916667, 11.666667)),
        PortCode("DK", "NAK", "Nakskov", null),
        PortCode("DK", "NBG", "Nyborg", null),
        PortCode("DK", "NDB", "Nordby Havn, Fanø", null),
        PortCode("DK", "NEX", "Neksø", null),
        PortCode("DK", "NGB", "Nagbol", Location(55.45, 9.283333)),
        PortCode("DK", "NHN", "Nordhavn", Location(55.7, 12.6)),
        PortCode("DK", "NR4", "Nyrup", Location(55.6, 11.666667)),
        PortCode("DK", "NRE", "Nørre Aaby", null),
        PortCode("DK", "NRS", "Nørresundby", null),
        PortCode("DK", "NSD", "Nørre Snede", Location(55.95, 9.383333)),
        PortCode("DK", "NTD", "Nysted", null),
        PortCode("DK", "NUD", "Næssund", null),
        PortCode("DK", "NVD", "Næstved", Location(55.233333, 11.766667)),
        PortCode("DK", "NYB", "Nyborg Lystbådehavn", Location(55.3, 10.783333)),
        PortCode("DK", "NYF", "Nykøbing Falster", Location(54.766667, 11.883333)),
        PortCode("DK", "NYM", "Nykøbing Mors", Location(56.783333, 8.85)),
        PortCode("DK", "ODE", "Odense", null),
        PortCode("DK", "OMO", "Omø", null),
        PortCode("DK", "OOT", "Charlottenlund", null),
        PortCode("DK", "ORE", "Orehoved, Falster", null),
        PortCode("DK", "ORO", "Orø", null),
        PortCode("DK", "OTB", "Østerby Havn", Location(57.316667, 11.133333)),
        PortCode("DK", "RAN", "Randers", null),
        PortCode("DK", "RD4", "Rude", Location(56.0, 10.233333)),
        PortCode("DK", "RDH", "Rødvig Havn", Location(55.25, 12.366667)),
        PortCode("DK", "RDK", "Rødekro", Location(55.066667, 9.316667)),
        PortCode("DK", "RKB", "Rudkøbing", null),
        PortCode("DK", "RKE", "Roskilde", null),
        PortCode("DK", "RMO", "Romo", Location(55.133333, 8.516667)),
        PortCode("DK", "RNN", "Rønne", null),
        PortCode("DK", "ROD", "Rødbyhavn", Location(54.65, 11.35)),
        PortCode("DK", "ROF", "Rødby", Location(54.683333, 11.383333)),
        PortCode("DK", "ROR", "Aalborg Portland Cementfabrikk", null),
        PortCode("DK", "RRV", "Rørvig", null),
        PortCode("DK", "RYS", "Ryslinge", Location(55.25, 10.55)),
        PortCode("DK", "SAE", "Sæby", Location(57.333333, 10.533333)),
        PortCode("DK", "SAX", "Sakskøbing", null),
        PortCode("DK", "SB2", "Strøby", Location(55.383333, 12.3)),
        PortCode("DK", "SBK", "Stubbekøbing", Location(54.883333, 12.05)),
        PortCode("DK", "SD7", "Sandved", Location(55.266667, 11.533333)),
        PortCode("DK", "SDA", "Sydals", Location(54.9, 9.883333)),
        PortCode("DK", "SDO", "Skarø/Drejø", null),
        PortCode("DK", "SEO", "Sejerø", null),
        PortCode("DK", "SF2", "Store Fuglede", Location(55.583333, 11.25)),
        PortCode("DK", "SGD", "Sønderborg", Location(54.9, 9.783333)),
        PortCode("DK", "SH6", "Store Heddinge", Location(55.316667, 12.416667)),
        PortCode("DK", "SIT", "Stigsnaes Inter Terminal", Location(55.2, 11.233333)),
        PortCode("DK", "SK3", "Skodsborg", Location(55.816667, 12.566667)),
        PortCode("DK", "SKA", "Skagen", null),
        PortCode("DK", "SKH", "Skovshoved", Location(55.766667, 12.6)),
        PortCode("DK", "SKV", "Skive", null),
        PortCode("DK", "SL2", "Søllested", Location(55.3, 10.05)),
        PortCode("DK", "SLB", "Silkeborg", null),
        PortCode("DK", "SLV", "Sælvig Havn", null),
        PortCode("DK", "SM6", "Store Merløse", Location(55.55, 11.716667)),
        PortCode("DK", "SN2", "Snertinge", Location(55.066667, 11.916667)),
        PortCode("DK", "SN7", "Stensved", Location(55.0, 12.033333)),
        PortCode("DK", "SNE", "Snekkersten", null),
        PortCode("DK", "SNO", "Strynø", null),
        PortCode("DK", "SNY", "Sundby/Mors", Location(56.866667, 8.666667)),
        PortCode("DK", "SOB", "Søby Havn", null),
        PortCode("DK", "SPB", "Spodsbjerg Havn", null),
        PortCode("DK", "SSK", "Skælskør", null),
        PortCode("DK", "SSV", "Studstrupværkets Havn", null),
        PortCode("DK", "STA", "Stavning", Location(55.966667, 8.383333)),
        PortCode("DK", "STB", "Strib Havn", null),
        PortCode("DK", "STE", "Stege", null),
        PortCode("DK", "STG", "Stignæsværkets Havn", null),
        PortCode("DK", "STN", "Stigsnæs", null),
        PortCode("DK", "STP", "Stevns Pier", Location(55.316667, 12.45)),
        PortCode("DK", "STR", "Struer", null),
        PortCode("DK", "STT", "Statoil-Havnen", null),
        PortCode("DK", "SUE", "Sundsøre", null),
        PortCode("DK", "SVA", "Svaneke", Location(55.133333, 15.15)),
        PortCode("DK", "SVE", "Svendborg", null),
        PortCode("DK", "SVG", "Sandvig", Location(55.283333, 14.783333)),
        PortCode("DK", "SVV", "Stålvalseværket", null),
        PortCode("DK", "TB4", "Toreby", Location(54.75, 11.8)),
        PortCode("DK", "TED", "Thisted", null),
        PortCode("DK", "TJL", "Tjele", Location(56.5, 9.6)),
        PortCode("DK", "TKB", "Tikøb", Location(56.016667, 12.466667)),
        PortCode("DK", "TMD", "Torsminde", Location(56.366667, 8.116667)),
        PortCode("DK", "TN3", "Tune", Location(55.6, 12.183333)),
        PortCode("DK", "TNO", "Tunø", null),
        PortCode("DK", "TRG", "Torrig", Location(54.9, 11.333333)),
        PortCode("DK", "TRO", "Troense", Location(55.033333, 10.65)),
        PortCode("DK", "TRS", "Tårs", null),
        PortCode("DK", "TUB", "Tuborg", null),
        PortCode("DK", "TYB", "Tyborøn", null),
        PortCode("DK", "UNX", "Masnedsund Godningshamn", Location(55.0, 11.916667)),
        PortCode("DK", "VAE", "Vallensbæk", Location(55.633333, 12.35)),
        PortCode("DK", "VB2", "Vejby", Location(56.066667, 12.15)),
        PortCode("DK", "VBN", "Vordingborg Nordhavnen", Location(55.0, 11.916667)),
        PortCode("DK", "VBS", "Vordingborg Sydhavnen", Location(54.983333, 11.883333)),
        PortCode("DK", "VEJ", "Vejle", null),
        PortCode("DK", "VEN", "Venø Havn", null),
        PortCode("DK", "VES", "Vesterø Havn, Læsø", null),
        PortCode("DK", "VG4", "Væggerløse", Location(54.7, 11.933333)),
        PortCode("DK", "VK7", "Veksø", Location(55.75, 12.25)),
        PortCode("DK", "VM2", "Vemmelev", Location(55.366667, 11.266667)),
        PortCode("DK", "VNG", "Vang Havn", null),
        PortCode("DK", "VOR", "Vordingborg", Location(55.0, 11.9)),
        PortCode("DK", "VRE", "Avedore", null),
        PortCode("DK", "VSV", "Norjyllandsvarkets havn", null),
        PortCode("DK", "VT2", "Vesterborg", Location(54.85, 11.283333))
    )
}
