package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.common.domain.model.geodata.Location
import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode

object PortsVE {
    val PORTS: List<PortCode> = listOf(
        PortCode("VE", "AMY", "Amuay", null),
        PortCode("VE", "ARA", "Araya", null),
        PortCode("VE", "BAV", "Bachaquero/Maracaibo L", null),
        PortCode("VE", "BJV", "Bajo Grande/Maracaibo L", null),
        PortCode("VE", "CAR", "Caripito", Location(10.133333, -63.033333)),
        PortCode("VE", "CBL", "Ciudad Bolívar", Location(8.116667, -63.55)),
        PortCode("VE", "CBS", "Cabimas/Maracaibo L", null),
        PortCode("VE", "CGU", "Ciudad Guayana", null),
        PortCode("VE", "CHQ", "Chiquinquirá", Location(10.433333, -71.633333)),
        PortCode("VE", "CHV", "Chichiriviche", null),
        PortCode("VE", "CMR", "Puerto Cumarebo", Location(11.483333, -69.35)),
        PortCode("VE", "CUM", "Cumana", null),
        PortCode("VE", "CUP", "Carupano", null),
        PortCode("VE", "CXA", "Caicara de Orinoco", null),
        PortCode("VE", "CZE", "Coro", null),
        PortCode("VE", "EGU", "El Guamache", null),
        PortCode("VE", "ELC", "El Chaure", Location(10.25, -64.616667)),
        PortCode("VE", "ELP", "El Palito", null),
        PortCode("VE", "ETV", "El Tablazo/Maracaibo L", null),
        PortCode("VE", "GUA", "Guaranao", Location(11.7, -70.15)),
        PortCode("VE", "GUB", "Guaranao Bay", null),
        PortCode("VE", "GUI", "Guiria", null),
        PortCode("VE", "GUT", "Guanta", null),
        PortCode("VE", "JOT", "Jose Terminal", Location(10.1, -64.85)),
        PortCode("VE", "LAG", "La Guaira", null),
        PortCode("VE", "LCV", "La Ceiba/Maracaibo L", null),
        PortCode("VE", "LEC", "La Estacada", null),
        PortCode("VE", "LGY", "Lagunillas", null),
        PortCode("VE", "LSP", "Las Piedras", null),
        PortCode("VE", "LSV", "La Salina/Maracaibo L", null),
        PortCode("VE", "LVL", "La Vela de Coro", null),
        PortCode("VE", "MAR", "Maracaibo", null),
        PortCode("VE", "MIV", "Puerto Miranda/Maracaibo L.", null),
        PortCode("VE", "MOR", "Morón", Location(10.483333, -68.2)),
        PortCode("VE", "MTV", "Matanzas", null),
        PortCode("VE", "PAR", "Paradero", null),
        PortCode("VE", "PBL", "Puerto Cabello", null),
        PortCode("VE", "PCA", "Punta Camacho", null),
        PortCode("VE", "PCN", "Punta Cardón", Location(11.65, -70.216667)),
        PortCode("VE", "PCO", "Puerto Carenero", Location(10.483333, -64.166667)),
        PortCode("VE", "PCT", "Paracotos", Location(10.266667, -66.95)),
        PortCode("VE", "PCU", "Punta Cuchillo", null),
        PortCode("VE", "PCZ", "Puerto La Cruz", null),
        PortCode("VE", "PFI", "Punto Fijo", Location(11.683333, -70.183333)),
        PortCode("VE", "PHO", "Puerto de Hierro", null),
        PortCode("VE", "PLA", "Palúa", Location(8.35, -62.666667)),
        PortCode("VE", "PLV", "Punta de Palmas", null),
        PortCode("VE", "PMP", "Pampatar", null),
        PortCode("VE", "PMR", "Palmarejo/Maracaibo L.", null),
        PortCode("VE", "PPD", "Punta de Piedra", null),
        PortCode("VE", "PPZ", "Puerto Páez", Location(6.216667, -67.45)),
        PortCode("VE", "PRC", "Paraguana Refinery Center", Location(11.616667, -70.233333)),
        PortCode("VE", "PRG", "Pertigalete", null),
        PortCode("VE", "PSU", "Puerto Sucre", null),
        PortCode("VE", "PTZ", "Petrozuata", Location(10.15, -64.85)),
        PortCode("VE", "PYH", "Puerto Ayacucho", null),
        PortCode("VE", "PZO", "Puerto Ordaz", null),
        PortCode("VE", "SFD", "San Fernando de Apure", null),
        PortCode("VE", "SFX", "San Félix", null),
        PortCode("VE", "SLV", "San Lorenzo/Maracaibo L", Location(9.783333, -71.066667)),
        PortCode("VE", "TJV", "Tia Juana/Maracaibo L", null),
        PortCode("VE", "TUR", "Turiamo", null),
        PortCode("VE", "YUR", "Ureña", Location(7.916667, -72.45))
    )
}
