package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.common.domain.model.geodata.Location
import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode

object PortsIN {
    val PORTS: List<PortCode> = listOf(
        PortCode("IN", "ABG", "Alibag", null),
        PortCode("IN", "ACH", "Achra", null),
        PortCode("IN", "ADI", "Androth Is", null),
        PortCode("IN", "AIS", "Amini Island", Location(11.116667, 72.733333)),
        PortCode("IN", "ALA", "Alang SBY", null),
        PortCode("IN", "ALF", "Alleppey", Location(9.483333, 76.316667)),
        PortCode("IN", "AMI", "Andorth Is", null),
        PortCode("IN", "ANG", "Anijengo", null),
        PortCode("IN", "ANL", "Arnala", null),
        PortCode("IN", "ATU", "Attur", Location(12.733333, 79.95)),
        PortCode("IN", "AZK", "Azhikkal", null),
        PortCode("IN", "BAW", "Bawal", null),
        PortCode("IN", "BBP", "Bahabal Pur", null),
        PortCode("IN", "BDA", "Bandra", null),
        PortCode("IN", "BDG", "Badagara", null),
        PortCode("IN", "BDH", "Bhadohi", Location(25.416667, 82.566667)),
        PortCode("IN", "BDQ", "Vadodara", Location(22.3, 73.2)),
        PortCode("IN", "BDR", "Baindur", null),
        PortCode("IN", "BED", "Bedi", null),
        PortCode("IN", "BET", "Betul", null),
        PortCode("IN", "BEY", "Beypore", null),
        PortCode("IN", "BGW", "Bhagwa", null),
        PortCode("IN", "BHM", "Bheemunipatnam", null),
        PortCode("IN", "BHU", "Bhavnagar", Location(21.766667, 72.133333)),
        PortCode("IN", "BKT", "Bankot", null),
        PortCode("IN", "BLK", "Belekeri", null),
        PortCode("IN", "BLM", "Bilimora", null),
        PortCode("IN", "BLP", "Belapur", null),
        PortCode("IN", "BND", "Banddar", null),
        PortCode("IN", "BOM", "Mumbai (ex Bombay)", Location(18.966667, 72.816667)),
        PortCode("IN", "BPQ", "Pratapganj", Location(26.3, 86.966667)),
        PortCode("IN", "BPT", "Bangarapet", Location(12.983333, 78.183333)),
        PortCode("IN", "BRH", "Broach", null),
        PortCode("IN", "BRM", "Borliai-Mandla", null),
        PortCode("IN", "BRU", "Bharuch", Location(21.7, 72.966667)),
        PortCode("IN", "BRY", "Borya", null),
        PortCode("IN", "BSN", "Bassain", null),
        PortCode("IN", "BSR", "Bulsar", null),
        PortCode("IN", "BTK", "Bhatkal", null),
        PortCode("IN", "BTR", "Bitra Is", null),
        PortCode("IN", "BUD", "Budge-Budge", null),
        PortCode("IN", "BWN", "Bhiwandi", null),
        PortCode("IN", "BYT", "Beyt", null),
        PortCode("IN", "CAM", "Cambay", null),
        PortCode("IN", "CAP", "Calingapatam", null),
        PortCode("IN", "CAR", "Carijam", null),
        PortCode("IN", "CBL", "Chandbali", null),
        PortCode("IN", "CCJ", "Kozhikode (ex Calicut)", Location(11.25, 75.766667)),
        PortCode("IN", "CCU", "Kolkata (ex Calcutta)", Location(22.566667, 88.35)),
        PortCode("IN", "CDL", "Cuddalore", null),
        PortCode("IN", "CHI", "Chikaballur", null),
        PortCode("IN", "CHR", "Chapora", null),
        PortCode("IN", "COK", "Kochi", Location(9.966667, 76.266667)),
        PortCode("IN", "COL", "Colochel", null),
        PortCode("IN", "COO", "Coondapur (Ganguly)", null),
        PortCode("IN", "CRN", "Cornwallis", null),
        PortCode("IN", "CTI", "Chetlat Is", null),
        PortCode("IN", "DAH", "Dahej", null),
        PortCode("IN", "DAM", "Daman", null),
        PortCode("IN", "DEG", "Deogad", null),
        PortCode("IN", "DHP", "Dabhol Port", null),
        PortCode("IN", "DHR", "Dholera", null),
        PortCode("IN", "DHU", "Dahanu", null),
        PortCode("IN", "DIG", "Dighi (Pune)", Location(18.25, 72.966667)),
        PortCode("IN", "DIU", "Diu", null),
        PortCode("IN", "DIV", "Div", null),
        PortCode("IN", "DMA", "Dhamara", Location(20.8, 86.9)),
        PortCode("IN", "DMQ", "Dhamra Port", Location(20.816667, 86.95)),
        PortCode("IN", "DMT", "Dharamtar", null),
        PortCode("IN", "DRK", "Dwarka (Rupen)", null),
        PortCode("IN", "DRL", "Dabolim", null),
        PortCode("IN", "DSK", "Dhanu-shkodi", null),
        PortCode("IN", "DTW", "Dantiwara", null),
        PortCode("IN", "DWA", "Dwarka", null),
        PortCode("IN", "EKM", "Ernakulam", Location(9.983333, 76.283333)),
        PortCode("IN", "ENR", "Ennore", null),
        PortCode("IN", "ERO", "Erode", Location(11.35, 77.733333)),
        PortCode("IN", "ESH", "Elphinstone Harbour", null),
        PortCode("IN", "GAN", "Gandhar", Location(21.083333, 72.633333)),
        PortCode("IN", "GAU", "Gauhati (Panidi)", null),
        PortCode("IN", "GGA", "Gogha", Location(21.683333, 72.266667)),
        PortCode("IN", "GGV", "Gangavaram", Location(17.65, 83.25)),
        PortCode("IN", "GHA", "Ghogha", null),
        PortCode("IN", "GND", "Greater Nodia", Location(28.816667, 77.883333)),
        PortCode("IN", "GNO", "Greater Noida", Location(28.466667, 77.516667)),
        PortCode("IN", "GPR", "Gopalpur", null),
        PortCode("IN", "GRR", "Garden Reach", Location(22.516667, 88.3)),
        PortCode("IN", "HAL", "Haldia", null),
        PortCode("IN", "HGT", "Hangarkatta", null),
        PortCode("IN", "HIP", "Himachal Pradesh", null),
        PortCode("IN", "HON", "Honavar", null),
        PortCode("IN", "HRN", "Harnai", null),
        PortCode("IN", "HWR", "Honawar", null),
        PortCode("IN", "HZA", "Hazira Port/Surat", Location(21.083333, 72.616667)),
        PortCode("IN", "ICD", "New Delhi", Location(28.6, 77.2)),
        PortCode("IN", "IXE", "Mangalore", null),
        PortCode("IN", "IXJ", "Jammu", Location(32.7, 74.85)),
        PortCode("IN", "IXM", "Madurai", Location(9.933333, 78.116667)),
        PortCode("IN", "IXY", "Kandla", Location(23.033333, 70.216667)),
        PortCode("IN", "IXZ", "Port Blair", null),
        PortCode("IN", "JAK", "Jakhau", null),
        PortCode("IN", "JBD", "Jafarabad", Location(20.85, 71.366667)),
        PortCode("IN", "JDA", "Jodia", null),
        PortCode("IN", "JDG", "Jodhpur", Location(21.883333, 70.033333)),
        PortCode("IN", "JGD", "Jaigad", null),
        PortCode("IN", "JTP", "Jaitapur", null),
        PortCode("IN", "KAK", "Kakinada", null),
        PortCode("IN", "KAL", "Kallai", null),
        PortCode("IN", "KAR", "Karur", Location(10.95, 78.083333)),
        PortCode("IN", "KAT", "Kattupalli", Location(13.3, 80.35)),
        PortCode("IN", "KBT", "Khambhat", null),
        PortCode("IN", "KDI", "Kadmat Is", null),
        PortCode("IN", "KDP", "Kondiapetnam", null),
        PortCode("IN", "KHO", "Khodiyar", Location(23.05, 72.933333)),
        PortCode("IN", "KIW", "Kelwa", null),
        PortCode("IN", "KKM", "Kanyakumari", null),
        PortCode("IN", "KKR", "Kilakari", null),
        PortCode("IN", "KKU", "Jaipur-Kanakpura", null),
        PortCode("IN", "KLY", "Kalyan", null),
        PortCode("IN", "KMB", "Kumbharu", null),
        PortCode("IN", "KND", "Kankudy", null),
        PortCode("IN", "KOD", "Kodinar", null),
        PortCode("IN", "KOI", "Koilthottum", null),
        PortCode("IN", "KOK", "Koka", null),
        PortCode("IN", "KON", "Konarak", null),
        PortCode("IN", "KPI", "Kalpeni Island", Location(10.066667, 73.633333)),
        PortCode("IN", "KRI", "Krishnapatnam", null),
        PortCode("IN", "KRK", "Karaikal", null),
        PortCode("IN", "KRN", "Karanja", null),
        PortCode("IN", "KRP", "Kiranpani", null),
        PortCode("IN", "KRW", "Karwar", null),
        PortCode("IN", "KSG", "Kasargod", null),
        PortCode("IN", "KSH", "Kelshi", null),
        PortCode("IN", "KSP", "Kulasekarapanam", null),
        PortCode("IN", "KTD", "Kotda", null),
        PortCode("IN", "KTI", "Kiltan Is", null),
        PortCode("IN", "KTK", "Toranagallu", Location(15.2, 76.683333)),
        PortCode("IN", "KTP", "Kattupalli Port", Location(13.3, 80.383333)),
        PortCode("IN", "KTW", "Koheshwar", null),
        PortCode("IN", "KVI", "Kavi", null),
        PortCode("IN", "KVL", "Kovalam", null),
        PortCode("IN", "KVT", "Kavaram Is", null),
        PortCode("IN", "LNG", "Lapanga", Location(21.733333, 84.016667)),
        PortCode("IN", "LPR", "Leapuram", null),
        PortCode("IN", "MAA", "Chennai (ex Madras)", Location(13.083333, 80.283333)),
        PortCode("IN", "MAC", "Machilipatnam", Location(16.183333, 81.133333)),
        PortCode("IN", "MAH", "Mahe", Location(11.7, 75.533333)),
        PortCode("IN", "MAL", "Malpe", null),
        PortCode("IN", "MAP", "Masulipatnam", null),
        PortCode("IN", "MCI", "Minicoi I", null),
        PortCode("IN", "MDA", "Magdalla", null),
        PortCode("IN", "MDK", "Mul Dwårka", Location(20.75, 70.666667)),
        PortCode("IN", "MDP", "Mandapam", null),
        PortCode("IN", "MDV", "Måndvi", Location(22.833333, 69.366667)),
        PortCode("IN", "MDW", "Meadows", null),
        PortCode("IN", "MGR", "Mangrol", null),
        PortCode("IN", "MHA", "Mahuva", null),
        PortCode("IN", "MLI", "Maroli", null),
        PortCode("IN", "MLP", "Mallipuram", null),
        PortCode("IN", "MLW", "Malwan", null),
        PortCode("IN", "MNR", "Manori", null),
        PortCode("IN", "MNW", "Mandwa", null),
        PortCode("IN", "MOB", "Morbi", Location(22.816667, 70.833333)),
        PortCode("IN", "MRA", "Mora", null),
        PortCode("IN", "MRI", "Mithivirdi", Location(21.466667, 72.233333)),
        PortCode("IN", "MRK", "Malappuram", null),
        PortCode("IN", "MRM", "Marmagao (Marmugao)", Location(15.4, 73.783333)),
        PortCode("IN", "MRM", "Marmugao (Marmagao)", Location(15.4, 73.783333)),
        PortCode("IN", "MTW", "Metwad", null),
        PortCode("IN", "MUG", "Munger", Location(25.383333, 86.466667)),
        PortCode("IN", "MUN", "Mundra", null),
        PortCode("IN", "MUR", "Murad", null),
        PortCode("IN", "MYB", "Mayabandar", null),
        PortCode("IN", "NAN", "Nancowrie", null),
        PortCode("IN", "NAV", "Navlakhi", null),
        PortCode("IN", "NDG", "Nandgaon", null),
        PortCode("IN", "NEE", "Nindakara", Location(8.933333, 76.533333)),
        PortCode("IN", "NEL", "Nellore", null),
        PortCode("IN", "NGC", "Nagercoil", Location(8.166667, 77.433333)),
        PortCode("IN", "NHV", "Nhave", Location(18.95, 72.966667)),
        PortCode("IN", "NML", "New Mangalore", null),
        PortCode("IN", "NPT", "Nagappattinam", Location(10.783333, 79.816667)),
        PortCode("IN", "NSA", "Jawaharlal Nehru (Nhava Sheva)", null),
        PortCode("IN", "NSA", "Nhava Sheva (Jawaharlal Nehru)", null),
        PortCode("IN", "NTU", "New Tuticorin", Location(8.75, 78.216667)),
        PortCode("IN", "NVB", "Navabunder", null),
        PortCode("IN", "NVP", "Navaspur", null),
        PortCode("IN", "NVT", "Nivti", null),
        PortCode("IN", "NWP", "Newapur", null),
        PortCode("IN", "OKH", "Okha", null),
        PortCode("IN", "ONJ", "Onjal", null),
        PortCode("IN", "ORS", "Orissa", Location(20.233333, 84.266667)),
        PortCode("IN", "PAN", "Panaji Port", null),
        PortCode("IN", "PAV", "Pipavav (Victor) Port", Location(20.966667, 71.55)),
        PortCode("IN", "PBD", "Porbandar", null),
        PortCode("IN", "PDD", "Padubidri", null),
        PortCode("IN", "PER", "Perundurai", null),
        PortCode("IN", "PID", "Port Indai", null),
        PortCode("IN", "PIN", "Pindhara", null),
        PortCode("IN", "PMB", "Pamban", null),
        PortCode("IN", "PNJ", "Panjim", null),
        PortCode("IN", "PNM", "Panambur, Va Mangalore", null),
        PortCode("IN", "PNN", "Ponnani", null),
        PortCode("IN", "PNY", "Pondicherry", Location(11.916667, 79.816667)),
        PortCode("IN", "PPJ", "Pellet Plant Jetty/Shiroda", null),
        PortCode("IN", "PPT", "Paradip Port", Location(20.25, 86.583333)),
        PortCode("IN", "PPV", "Port Pipavav", Location(20.933333, 71.516667)),
        PortCode("IN", "PRG", "Purangad", null),
        PortCode("IN", "PRN", "Portonovo", null),
        PortCode("IN", "PRT", "Paradip Garh", Location(20.316667, 86.616667)),
        PortCode("IN", "PSH", "Palshet", null),
        PortCode("IN", "PST", "Positra", Location(22.4, 69.166667)),
        PortCode("IN", "PUL", "Pulicat", null),
        PortCode("IN", "PUR", "Puri", null),
        PortCode("IN", "QUI", "Quilon", null),
        PortCode("IN", "RAM", "Rameshwaram", null),
        PortCode("IN", "RED", "Redi", null),
        PortCode("IN", "RGT", "Ranghat Bay", null),
        PortCode("IN", "RJP", "Rajpara/Navabunder", null),
        PortCode("IN", "RJR", "Rajpuri", null),
        PortCode("IN", "RKG", "Rajakkamangalam", null),
        PortCode("IN", "RNR", "Ranpar", null),
        PortCode("IN", "ROZ", "Rozi", Location(22.566667, 70.033333)),
        PortCode("IN", "RRI", "Raili", null),
        PortCode("IN", "RTC", "Ratnagiri", null),
        PortCode("IN", "RVD", "Revdanda", null),
        PortCode("IN", "SAD", "Sanathnagar", null),
        PortCode("IN", "SAL", "Salaya", null),
        PortCode("IN", "SAM", "Samalkot", Location(17.05, 82.183333)),
        PortCode("IN", "SBH", "Sinbhour", null),
        PortCode("IN", "SHI", "Shirola", null),
        PortCode("IN", "SHP", "Simbhour Port", null),
        PortCode("IN", "SIK", "Sika", Location(22.433333, 69.833333)),
        PortCode("IN", "SIL", "Siliguri", Location(26.716667, 88.416667)),
        PortCode("IN", "SIM", "Sima/Navabunder", null),
        PortCode("IN", "SKK", "Sikkim", Location(27.316667, 88.616667)),
        PortCode("IN", "SMR", "Simor", null),
        PortCode("IN", "SRV", "Surasani-Yanam", null),
        PortCode("IN", "STP", "Satpati", null),
        PortCode("IN", "STV", "Surat", Location(21.166667, 72.833333)),
        PortCode("IN", "SWA", "Sahnewal", Location(30.85, 75.95)),
        PortCode("IN", "SWD", "Shriwardhan", null),
        PortCode("IN", "TAD", "Tadri", Location(14.516667, 74.35)),
        PortCode("IN", "TEL", "Tellicherry", null),
        PortCode("IN", "THL", "Thal", null),
        PortCode("IN", "THN", "Thane", Location(19.2, 72.966667)),
        PortCode("IN", "TIV", "Tiviri", null),
        PortCode("IN", "TJA", "Talaja", null),
        PortCode("IN", "TKS", "Tenkasi", null),
        PortCode("IN", "TMP", "Trombay", null),
        PortCode("IN", "TNA", "Thana", null),
        PortCode("IN", "TND", "Tondi", null),
        PortCode("IN", "TNK", "Tankari", null),
        PortCode("IN", "TPH", "Thopputhurai", null),
        PortCode("IN", "TPN", "Talpona", null),
        PortCode("IN", "TRA", "Tranquebar", null),
        PortCode("IN", "TRP", "Tarapur", null),
        PortCode("IN", "TRV", "Thiruvananthapuram (ex Trivandrum)", Location(8.483333, 76.916667)),
        PortCode("IN", "TUN", "Tuna", null),
        PortCode("IN", "TUT", "Tuticorin", Location(8.783333, 78.133333)),
        PortCode("IN", "TYR", "Tirukkadayyur", null),
        PortCode("IN", "ULW", "Ulwa", null),
        PortCode("IN", "UMB", "Umbergoan", null),
        PortCode("IN", "UMR", "Umarsadi", null),
        PortCode("IN", "URA", "Uran", Location(18.883333, 72.933333)),
        PortCode("IN", "UTN", "Uttan", null),
        PortCode("IN", "VAD", "Vadinar", null),
        PortCode("IN", "VEN", "Vengurla", null),
        PortCode("IN", "VEP", "Veppalodai", null),
        PortCode("IN", "VIG", "Vizagapatanam", null),
        PortCode("IN", "VKM", "Valinokkam", null),
        PortCode("IN", "VNG", "Vemgira", null),
        PortCode("IN", "VRD", "Varavda", null),
        PortCode("IN", "VRU", "Vadarevu", null),
        PortCode("IN", "VSI", "Vansi-Borsi", null),
        PortCode("IN", "VSV", "Varsova", null),
        PortCode("IN", "VTZ", "Visakhapatnam", Location(17.7, 83.3)),
        PortCode("IN", "VVA", "Veraval", null),
        PortCode("IN", "VYD", "Vijaydurg", null),
        PortCode("IN", "VZJ", "Vazhinjam", Location(8.383333, 77.0)),
        PortCode("IN", "WAD", "Wada", Location(18.983333, 73.75)),
        PortCode("IN", "ZUM", "Tumkur", Location(16.5, 77.083333))
    )
}
