package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.common.domain.model.geodata.Location
import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode

object PortsIS {
    val PORTS: List<PortCode> = listOf(
        PortCode("IS", "AKR", "Akranes", null),
        PortCode("IS", "AKU", "Akureyri", null),
        PortCode("IS", "ASS", "Arskogssandur", Location(65.933333, -18.366667)),
        PortCode("IS", "BAK", "Bakkafjördur", Location(66.033333, -14.8)),
        PortCode("IS", "BGJ", "Borgarfjørdur eystri", null),
        PortCode("IS", "BIL", "Bildudalur - høfn", null),
        PortCode("IS", "BLO", "Blonduos", null),
        PortCode("IS", "BOI", "Bordeyri", null),
        PortCode("IS", "BOL", "Bolungarvik", Location(66.133333, -23.25)),
        PortCode("IS", "BOR", "Borgarnes", null),
        PortCode("IS", "BRE", "Breiddalsvik", null),
        PortCode("IS", "BRJ", "Brjánslækur", Location(65.533333, -23.2)),
        PortCode("IS", "BUD", "Budardalur", Location(65.116667, -21.766667)),
        PortCode("IS", "DAL", "Dalvík", Location(65.966667, -18.533333)),
        PortCode("IS", "DJU", "Djúpivogur", Location(64.65, -14.283333)),
        PortCode("IS", "DPV", "Djupavik", null),
        PortCode("IS", "DRA", "Drangsnes", null),
        PortCode("IS", "ESK", "Eskifjørdur - høfn", null),
        PortCode("IS", "FAS", "Faskrudsfjørdur", null),
        PortCode("IS", "FEY", "Flatey", Location(65.366667, -22.933333)),
        PortCode("IS", "FLA", "Flateyri", null),
        PortCode("IS", "GRB", "Gardabaer", Location(64.083333, -12.933333)),
        PortCode("IS", "GRD", "Gardur", null),
        PortCode("IS", "GRE", "Grenivík", Location(65.95, -18.183333)),
        PortCode("IS", "GRF", "Grundarfjørdur", null),
        PortCode("IS", "GRI", "Grindavík", Location(63.833333, -22.433333)),
        PortCode("IS", "GRT", "Grundartangi", null),
        PortCode("IS", "GUF", "Gufunes/Reykjavik", null),
        PortCode("IS", "HAF", "Hafnarfjørdur", null),
        PortCode("IS", "HEL", "Helguvik", Location(64.033333, -22.55)),
        PortCode("IS", "HFN", "Höfn, Hornafjørdur", Location(64.25, -15.216667)),
        PortCode("IS", "HJA", "Hjalteyri", null),
        PortCode("IS", "HNR", "Hafnir", Location(63.916667, -22.683333)),
        PortCode("IS", "HOF", "Hofsós", Location(65.9, -19.433333)),
        PortCode("IS", "HRI", "Hrisey", null),
        PortCode("IS", "HUS", "Husavik - høfn", null),
        PortCode("IS", "HVM", "Hvammstangi", null),
        PortCode("IS", "HVR", "Midsandur", null),
        PortCode("IS", "ISA", "Isafjørdur - høfn", null),
        PortCode("IS", "KEV", "Keflavikurkaupstadur", null),
        PortCode("IS", "KJF", "Skerjafjördur", null),
        PortCode("IS", "KOP", "Kopasker - høfn", null),
        PortCode("IS", "KOV", "Kópavogur", Location(64.1, -21.916667)),
        PortCode("IS", "KRO", "Krokfjardarnes", null),
        PortCode("IS", "LAN", "Landeyjahöfn", Location(61.516667, -20.116667)),
        PortCode("IS", "LSA", "Litli Sandur", Location(64.4, -21.45)),
        PortCode("IS", "MJH", "Mjoeyrarhofn", Location(64.916667, -13.95)),
        PortCode("IS", "MJO", "Mjofjördur", null),
        PortCode("IS", "MOS", "Mosfellsbaer", Location(64.166667, -21.716667)),
        PortCode("IS", "NES", "Neskaupstadur", null),
        PortCode("IS", "NJA", "Njardvik", null),
        PortCode("IS", "NOU", "Nordurfjördur", null),
        PortCode("IS", "OLF", "Olafsfjørdur", null),
        PortCode("IS", "OLV", "Olafsvík", Location(64.883333, -23.716667)),
        PortCode("IS", "OSP", "Ospakseyri", Location(65.45, -21.433333)),
        PortCode("IS", "PAT", "Patreksfjørdur - høfn", null),
        PortCode("IS", "RAU", "Raufarhöfn", Location(66.45, -15.95)),
        PortCode("IS", "REY", "Reykjavík", Location(64.15, -21.95)),
        PortCode("IS", "RFJ", "Reydarfjørdur", null),
        PortCode("IS", "RHA", "Reykhólar", Location(65.45, -22.2)),
        PortCode("IS", "RIF", "Rif-Hellisandur", null),
        PortCode("IS", "SAN", "Sandgerdi", null),
        PortCode("IS", "SAU", "Saudarkrokur - høfn", null),
        PortCode("IS", "SEY", "Seydisfjørdur", null),
        PortCode("IS", "SIG", "Siglufjørdur - høfn", null),
        PortCode("IS", "SKA", "Skagaströnd", Location(65.833333, -20.316667)),
        PortCode("IS", "STD", "Stodhvarfjørdur", null),
        PortCode("IS", "STR", "Straumsvik", null),
        PortCode("IS", "STY", "Stykkisholmur - høfn", null),
        PortCode("IS", "SUD", "Sudureyri/Sugandafjord", null),
        PortCode("IS", "SUV", "Sudavik", null),
        PortCode("IS", "SVA", "Svalbardseyri", null),
        PortCode("IS", "TAL", "Talknafjørdur/Sveinseyri", null),
        PortCode("IS", "TEY", "Thingeyri", null),
        PortCode("IS", "THH", "Thorlakshofn", null),
        PortCode("IS", "THN", "Tjörneshöfn", null),
        PortCode("IS", "THO", "Thorshofn", null),
        PortCode("IS", "VES", "Vestmannaeyjar - høfn", null),
        PortCode("IS", "VOG", "Vogar", Location(63.983333, -22.383333)),
        PortCode("IS", "VPN", "Vopnafjördur", Location(65.75, -14.833333))
    )
}
