package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.common.domain.model.geodata.Location
import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode

object PortsJP {
    val PORTS: List<PortCode> = listOf(
        PortCode("JP", "AAM", "Ama, Shimane", null),
        PortCode("JP", "ABA", "Abashiri", null),
        PortCode("JP", "ABO", "Aboshi/Himeji", null),
        PortCode("JP", "ABS", "Abohshita", null),
        PortCode("JP", "ABT", "Abuto", null),
        PortCode("JP", "ABU", "Aburatsu", null),
        PortCode("JP", "ACH", "Ajisu", null),
        PortCode("JP", "ADE", "Ade", null),
        PortCode("JP", "ADO", "Ado", null),
        PortCode("JP", "AFG", "Akitafunagawa", Location(39.883333, 139.95)),
        PortCode("JP", "AGJ", "Aguni", null),
        PortCode("JP", "AGN", "Agenosho", null),
        PortCode("JP", "AGR", "Agonoura", null),
        PortCode("JP", "AGS", "Ageshima", null),
        PortCode("JP", "AIA", "Ainouraaoki/Naru", null),
        PortCode("JP", "AIG", "Aki-gun/Hiroshima", Location(34.333333, 132.533333)),
        PortCode("JP", "AII", "Aio", null),
        PortCode("JP", "AIK", "Aikawa, Niigata", null),
        PortCode("JP", "AIM", "Aishima", null),
        PortCode("JP", "AIN", "Ainoura/Sasebo", null),
        PortCode("JP", "AIO", "Aioi", Location(34.783333, 134.466667)),
        PortCode("JP", "AIW", "Aikawa, Nagasaki", null),
        PortCode("JP", "AIZ", "Aizu, Kumamoto", null),
        PortCode("JP", "AJI", "Aji", null),
        PortCode("JP", "AJK", "Ajigasawa", null),
        PortCode("JP", "AJN", "Ajino", null),
        PortCode("JP", "AJR", "Ajiro, Shizuoka", null),
        PortCode("JP", "AJX", "Aja", null),
        PortCode("JP", "AKA", "Akashi", null),
        PortCode("JP", "AKB", "Akohbaru", null),
        PortCode("JP", "AKD", "Akadomari", null),
        PortCode("JP", "AKE", "Akkeshi", null),
        PortCode("JP", "AKG", "Akakina", null),
        PortCode("JP", "AKH", "Akehama", null),
        PortCode("JP", "AKI", "Aikakita", null),
        PortCode("JP", "AKK", "Akasaki, Kumamoto", null),
        PortCode("JP", "AKM", "Akamizu", null),
        PortCode("JP", "AKN", "Akune", null),
        PortCode("JP", "AKO", "Akoh", null),
        PortCode("JP", "AKT", "Akitsu", null),
        PortCode("JP", "AKW", "Azako", null),
        PortCode("JP", "AKZ", "Aika", null),
        PortCode("JP", "AMA", "Amagasaki", null),
        PortCode("JP", "AMG", "Asamogawa", null),
        PortCode("JP", "AMI", "Atami", null),
        PortCode("JP", "AMJ", "Amaji", null),
        PortCode("JP", "AMM", "Ama, Hyogo", null),
        PortCode("JP", "AMR", "Arimura", null),
        PortCode("JP", "AMS", "Amasaki", null),
        PortCode("JP", "AMT", "Amatsuke", null),
        PortCode("JP", "AMU", "Amura", null),
        PortCode("JP", "AMX", "AmagasakiNishinomiyaAshiya", Location(34.716667, 135.416667)),
        PortCode("JP", "AMY", "Amiya", null),
        PortCode("JP", "ANA", "Anan", null),
        PortCode("JP", "ANB", "Anbo", null),
        PortCode("JP", "ANE", "Anegasaki", null),
        PortCode("JP", "ANM", "Anamizu", null),
        PortCode("JP", "AOE", "Aoe", null),
        PortCode("JP", "AOG", "Aogashima", null),
        PortCode("JP", "AOI", "Aoki", null),
        PortCode("JP", "AOJ", "Aomori", null),
        PortCode("JP", "AOK", "Aokata", null),
        PortCode("JP", "AOM", "Omi", Location(37.016667, 137.8)),
        PortCode("JP", "AON", "Aonae", null),
        PortCode("JP", "AOS", "Aoshima", null),
        PortCode("JP", "APP", "Koshi", Location(32.883333, 130.783333)),
        PortCode("JP", "ARA", "Arari", null),
        PortCode("JP", "ARG", "Amurogama", null),
        PortCode("JP", "ARI", "Ariake, Tokyo", Location(35.633333, 139.783333)),
        PortCode("JP", "ARK", "Arikawa", null),
        PortCode("JP", "ARO", "Arao", null),
        PortCode("JP", "ARZ", "Arouzu", null),
        PortCode("JP", "ASA", "Asa", null),
        PortCode("JP", "ASB", "Ashibe", null),
        PortCode("JP", "ASH", "Ashinoura", null),
        PortCode("JP", "ASI", "Asahimachi", Location(35.533333, 139.7)),
        PortCode("JP", "ASJ", "Amamioshima", null),
        PortCode("JP", "ASK", "Akasaki, Tottori", null),
        PortCode("JP", "ASM", "Asami", null),
        PortCode("JP", "ASR", "Ashizuri", null),
        PortCode("JP", "AST", "Ashitoku", null),
        PortCode("JP", "ASU", "Kasuya", Location(33.616667, 130.483333)),
        PortCode("JP", "ASW", "Asakawa", null),
        PortCode("JP", "ASZ", "Ashiya, Fukuoka", null),
        PortCode("JP", "ATA", "Ataka", Location(36.416667, 136.416667)),
        PortCode("JP", "ATK", "Atsuki", null),
        PortCode("JP", "ATM", "Atsumi", null),
        PortCode("JP", "ATT", "Atatajima", null),
        PortCode("JP", "AUI", "Asakuchi", Location(34.516667, 133.583333)),
        PortCode("JP", "AWA", "Awa", null),
        PortCode("JP", "AWM", "Awashimanishi", null),
        PortCode("JP", "AWS", "Awashima", null),
        PortCode("JP", "AWZ", "Awazu", null),
        PortCode("JP", "AXT", "Akita", null),
        PortCode("JP", "AXZ", "Zushi", Location(35.283333, 139.583333)),
        PortCode("JP", "AYU", "Ayukawa", null),
        PortCode("JP", "AZJ", "Ajiro, Tottori", null),
        PortCode("JP", "AZR", "Ajiro, Okayama", null),
        PortCode("JP", "AZU", "Azu", null),
        PortCode("JP", "BDM", "Bohdomari", null),
        PortCode("JP", "BEP", "Beppu, Shimane", null),
        PortCode("JP", "BFS", "Beppushinko", null),
        PortCode("JP", "BIZ", "Bizen", Location(34.733333, 134.183333)),
        PortCode("JP", "BKW", "Shibukawa", Location(36.483333, 139.0)),
        PortCode("JP", "BOM", "Boma", null),
        PortCode("JP", "BPU", "Beppu, Oita", null),
        PortCode("JP", "BYO", "Byobu", null),
        PortCode("JP", "CHB", "Chiba", null),
        PortCode("JP", "CHF", "Chofu", null),
        PortCode("JP", "CHG", "Chigasaki", Location(35.316667, 139.4)),
        PortCode("JP", "CHH", "Chichii", null),
        PortCode("JP", "CHI", "China", null),
        PortCode("JP", "CHK", "Chikubushima", null),
        PortCode("JP", "CHO", "Choshi", null),
        PortCode("JP", "CHT", "Chitose, Hiroshima", null),
        PortCode("JP", "CHU", "Churui", null),
        PortCode("JP", "CHW", "Chimu Wan", Location(26.383333, 127.916667)),
        PortCode("JP", "CIO", "Chio", null),
        PortCode("JP", "CJU", "Chiju", null),
        PortCode("JP", "CKM", "Chikumi", null),
        PortCode("JP", "CNS", "Chinase", null),
        PortCode("JP", "CTA", "Chita", null),
        PortCode("JP", "CYU", "Chiryu", Location(35.0, 137.05)),
        PortCode("JP", "CYZ", "Chiyozaki", null),
        PortCode("JP", "DAT", "Date", null),
        PortCode("JP", "DSR", "Dohshiro", null),
        PortCode("JP", "DTU", "Daito", null),
        PortCode("JP", "DZK", "Dohzaki", null),
        PortCode("JP", "EBI", "Ebito", null),
        PortCode("JP", "EGO", "Ego", null),
        PortCode("JP", "EGS", "Eigashima", null),
        PortCode("JP", "EII", "Ei", null),
        PortCode("JP", "EIS", "Eishi", null),
        PortCode("JP", "EJM", "Ejima", null),
        PortCode("JP", "EKZ", "Enokizu", null),
        PortCode("JP", "EMM", "Erimo", null),
        PortCode("JP", "EMU", "Emukae", null),
        PortCode("JP", "ENA", "Ena", null),
        PortCode("JP", "ENH", "Enohama", null),
        PortCode("JP", "ENN", "En", null),
        PortCode("JP", "ENO", "Enoura, Shizuoka", null),
        PortCode("JP", "ENR", "Enoura, Kagawa", null),
        PortCode("JP", "ESI", "Esashi/Hiyama", null),
        PortCode("JP", "ESK", "Esaki", null),
        PortCode("JP", "ESM", "Eshima", null),
        PortCode("JP", "ESS", "Esashi/Soya", null),
        PortCode("JP", "ETA", "Etajima", null),
        PortCode("JP", "ETM", "Etomo", null),
        PortCode("JP", "EZA", "Ezaki", null),
        PortCode("JP", "FAE", "Fukae, Nagasaki", null),
        PortCode("JP", "FCM", "Fuchinomoto", null),
        PortCode("JP", "FGS", "Fugusaki", null),
        PortCode("JP", "FGW", "Futagawa", null),
        PortCode("JP", "FHR", "Furubira", null),
        PortCode("JP", "FJN", "Fujino", null),
        PortCode("JP", "FKD", "Fukuda", null),
        PortCode("JP", "FKE", "Fukue, Aichi", null),
        PortCode("JP", "FKH", "Fukae, Hiroshima", null),
        PortCode("JP", "FKI", "Fukai", null),
        PortCode("JP", "FKJ", "Fukui", null),
        PortCode("JP", "FKK", "Fukaura, Aomori", null),
        PortCode("JP", "FKM", "Fukushima, Nagasaki", Location(33.35, 129.8)),
        PortCode("JP", "FKR", "Fukaura, Ehime", null),
        PortCode("JP", "FKU", "Fukushima, Hokkaido", Location(41.466667, 140.25)),
        PortCode("JP", "FKY", "Fukuyama, Hiroshima", null),
        PortCode("JP", "FMD", "Futamado", null),
        PortCode("JP", "FMS", "Fukushima, Miyazaki", Location(31.466667, 131.216667)),
        PortCode("JP", "FMT", "Futamata, Kagoshima", null),
        PortCode("JP", "FNA", "Funaya", null),
        PortCode("JP", "FNB", "Funabashi", null),
        PortCode("JP", "FND", "Funadomari", null),
        PortCode("JP", "FNK", "Funagawa", null),
        PortCode("JP", "FNR", "Funaura", null),
        PortCode("JP", "FNS", "Funakoshi", null),
        PortCode("JP", "FNU", "Funauki", null),
        PortCode("JP", "FNZ", "Funazu", null),
        PortCode("JP", "FRA", "Fukura, Hyogo", null),
        PortCode("JP", "FRE", "Furue, Nagasaki", null),
        PortCode("JP", "FRI", "Fukari", null),
        PortCode("JP", "FRJ", "Fukuura, Ishikawa", null),
        PortCode("JP", "FRK", "Furuike", null),
        PortCode("JP", "FRM", "Furue, Miyazaki", null),
        PortCode("JP", "FRS", "Furusato, Nagasaki", null),
        PortCode("JP", "FRU", "Furue, Kagoshima", null),
        PortCode("JP", "FRX", "Furue, Ehime", null),
        PortCode("JP", "FSH", "Funakakushi", null),
        PortCode("JP", "FSK", "Fushiki", null),
        PortCode("JP", "FST", "Furusato, Kagoshima", Location(27.366667, 128.633333)),
        PortCode("JP", "FTE", "Futae", null),
        PortCode("JP", "FTG", "Futago", null),
        PortCode("JP", "FTM", "Futenma", null),
        PortCode("JP", "FTS", "Futtsu, Chiba", Location(35.583333, 140.383333)),
        PortCode("JP", "FTT", "Futamata, Shimane", null),
        PortCode("JP", "FTX", "Fushikitoyama", Location(36.8, 137.116667)),
        PortCode("JP", "FUA", "Fukuura, Kumamoto", null),
        PortCode("JP", "FUE", "Fuke", null),
        PortCode("JP", "FUJ", "Fukue, Nagasaki", null),
        PortCode("JP", "FUM", "Fukami", null),
        PortCode("JP", "FUO", "Fukuro", null),
        PortCode("JP", "FUR", "Fukuura, Ehime", null),
        PortCode("JP", "FUU", "Fukura, Kagoshima", null),
        PortCode("JP", "FUW", "Fukawa", null),
        PortCode("JP", "FYM", "Fukuyama, Kagoshima", null),
        PortCode("JP", "GAM", "Gamagori", null),
        PortCode("JP", "GKA", "Gushikawa", Location(26.35, 127.866667)),
        PortCode("JP", "GKB", "Gohnokubi", null),
        PortCode("JP", "GKN", "Gokan", null),
        PortCode("JP", "GKS", "Gokasho", null),
        PortCode("JP", "GNG", "Gunge", null),
        PortCode("JP", "GNW", "Ginowan", null),
        PortCode("JP", "GOI", "Goi/Ichihara", null),
        PortCode("JP", "GON", "Gonoura", null),
        PortCode("JP", "GOO", "Gobo Wakayama", Location(33.883333, 135.15)),
        PortCode("JP", "GOT", "Gohtsu", null),
        PortCode("JP", "GPT", "Gendentokai", null),
        PortCode("JP", "GTK", "Kitanagoya", Location(35.233333, 136.85)),
        PortCode("JP", "GTO", "Goto", Location(32.683333, 128.833333)),
        PortCode("JP", "HAA", "Hami", null),
        PortCode("JP", "HAB", "Habu, Hiroshima", null),
        PortCode("JP", "HAD", "Heda", null),
        PortCode("JP", "HAE", "Haenohama", null),
        PortCode("JP", "HAG", "Hagi", null),
        PortCode("JP", "HAH", "Hashima", null),
        PortCode("JP", "HAI", "Haiki", null),
        PortCode("JP", "HAM", "Hamasarufutsu", null),
        PortCode("JP", "HAN", "Hannan", null),
        PortCode("JP", "HAR", "Hara", null),
        PortCode("JP", "HAS", "Hashihama", null),
        PortCode("JP", "HAU", "Habu, Tokyo", null),
        PortCode("JP", "HBB", "Habu, Yamaguchi", null),
        PortCode("JP", "HBK", "Hibikishinko", Location(33.983333, 130.75)),
        PortCode("JP", "HBO", "Haboro", null),
        PortCode("JP", "HBR", "Hiburi", null),
        PortCode("JP", "HDA", "Handa", null),
        PortCode("JP", "HDK", "Hidaka", null),
        PortCode("JP", "HDO", "Himedo", null),
        PortCode("JP", "HEA", "Hiketa", null),
        PortCode("JP", "HED", "Hetono", null),
        PortCode("JP", "HEI", "Henza", null),
        PortCode("JP", "HES", "Hesaki", null),
        PortCode("JP", "HET", "Heta", null),
        PortCode("JP", "HGH", "Higashihazu", null),
        PortCode("JP", "HGN", "Higashisonogi-Gun Cho", Location(32.033333, 129.916667)),
        PortCode("JP", "HGO", "Hachigo", null),
        PortCode("JP", "HGS", "Ohshima/Hagi", null),
        PortCode("JP", "HGU", "Hirugaura", null),
        PortCode("JP", "HHE", "Hachinohe", null),
        PortCode("JP", "HHH", "Higashinohama", null),
        PortCode("JP", "HHM", "Hohomi", null),
        PortCode("JP", "HHR", "Higashiharima", null),
        PortCode("JP", "HIA", "Hiagari/Kitakiushu", null),
        PortCode("JP", "HIB", "Hibi", null),
        PortCode("JP", "HIC", "Hitachinaka", null),
        PortCode("JP", "HIE", "Hikone", null),
        PortCode("JP", "HIG", "Higashishioya", null),
        PortCode("JP", "HII", "Hirasaki", null),
        PortCode("JP", "HIJ", "Hiroshima", null),
        PortCode("JP", "HIK", "Hiki", null),
        PortCode("JP", "HIM", "Himeji", null),
        PortCode("JP", "HIN", "Hinase", null),
        PortCode("JP", "HIO", "Higashi-Ogishima", null),
        PortCode("JP", "HIR", "Hiroo", null),
        PortCode("JP", "HIS", "Hikoshima", null),
        PortCode("JP", "HIU", "Hiratsuka", Location(35.316667, 139.35)),
        PortCode("JP", "HIZ", "Hizenohshima", null),
        PortCode("JP", "HJA", "Honjima", null),
        PortCode("JP", "HJI", "Hiji", null),
        PortCode("JP", "HJM", "Hamajima", null),
        PortCode("JP", "HJO", "Hojo", null),
        PortCode("JP", "HJR", "Hamajiri", null),
        PortCode("JP", "HJT", "Hirota, Kagoshima", null),
        PortCode("JP", "HKD", "Hakodate", null),
        PortCode("JP", "HKJ", "Hamasaka", null),
        PortCode("JP", "HKK", "Hyakkan", null),
        PortCode("JP", "HKM", "Honkushima", null),
        PortCode("JP", "HKN", "Hekinan", null),
        PortCode("JP", "HKR", "Hikari", null),
        PortCode("JP", "HKS", "Hakatashima", null),
        PortCode("JP", "HKT", "Hakata/Fukuoka", Location(33.6, 130.416667)),
        PortCode("JP", "HKU", "Hakoura", null),
        PortCode("JP", "HKW", "Hamakanaya", null),
        PortCode("JP", "HKZ", "Hikozaki", null),
        PortCode("JP", "HMA", "Hishima", null),
        PortCode("JP", "HMC", "Hamochi", null),
        PortCode("JP", "HMD", "Hamada", null),
        PortCode("JP", "HMG", "Hamaguri", null),
        PortCode("JP", "HMH", "Himeshima", null),
        PortCode("JP", "HMI", "Hatami", null),
        PortCode("JP", "HMJ", "Himi", null),
        PortCode("JP", "HMK", "Himekawa", null),
        PortCode("JP", "HMM", "Hamamatsu", null),
        PortCode("JP", "HMN", "Hamana", null),
        PortCode("JP", "HMR", "Hamura", Location(35.766667, 139.3)),
        PortCode("JP", "HMS", "Himosashi", null),
        PortCode("JP", "HMT", "Hikimoto", null),
        PortCode("JP", "HMW", "Hamawaki", null),
        PortCode("JP", "HMX", "Hamasaki", null),
        PortCode("JP", "HNE", "Hane", null),
        PortCode("JP", "HNG", "Hinagu", null),
        PortCode("JP", "HNJ", "Honjo, Kyoto", null),
        PortCode("JP", "HNK", "Hanasaki", null),
        PortCode("JP", "HNN", "Honmoku", null),
        PortCode("JP", "HNR", "Himenoura", null),
        PortCode("JP", "HNS", "Hinoshima", null),
        PortCode("JP", "HNY", "Hanyu", null),
        PortCode("JP", "HNZ", "Hinozu", null),
        PortCode("JP", "HOD", "Hondo", null),
        PortCode("JP", "HOF", "Hofu", Location(34.033333, 131.566667)),
        PortCode("JP", "HON", "Honjo, Akita", null),
        PortCode("JP", "HOS", "Hoshika, Saga", null),
        PortCode("JP", "HOT", "Hotokegaura", null),
        PortCode("JP", "HPP", "Hoppozaki", null),
        PortCode("JP", "HRA", "Hirao", null),
        PortCode("JP", "HRD", "Hirado", null),
        PortCode("JP", "HRE", "Horie", null),
        PortCode("JP", "HRH", "Hirohata", null),
        PortCode("JP", "HRI", "Horikappu", null),
        PortCode("JP", "HRJ", "Hirai", null),
        PortCode("JP", "HRK", "Hirakata", null),
        PortCode("JP", "HRM", "Haramachi", null),
        PortCode("JP", "HRO", "Hiro", null),
        PortCode("JP", "HRR", "Hirara", null),
        PortCode("JP", "HRS", "Hirase", null),
        PortCode("JP", "HRU", "Hiroura", null),
        PortCode("JP", "HRW", "Hiraiwa", null),
        PortCode("JP", "HSG", "Saga", Location(33.083333, 133.1)),
        PortCode("JP", "HSH", "Hashi", null),
        PortCode("JP", "HSI", "Hoshika, Nagasaki", null),
        PortCode("JP", "HSK", "Hamasako", null),
        PortCode("JP", "HSM", "Hososhima", null),
        PortCode("JP", "HSN", "Hisanohama", null),
        PortCode("JP", "HSR", "Hashirajima", null),
        PortCode("JP", "HSS", "Hase", null),
        PortCode("JP", "HSU", "Hamasuki", null),
        PortCode("JP", "HSW", "Hirasawa", null),
        PortCode("JP", "HTA", "Hirota, Iwate", null),
        PortCode("JP", "HTC", "Hitachi", null),
        PortCode("JP", "HTK", "Hitakatsu", null),
        PortCode("JP", "HTM", "Futami, Tokyo", null),
        PortCode("JP", "HTO", "Hatoma", Location(24.466667, 123.766667)),
        PortCode("JP", "HTS", "Hitsushima", null),
        PortCode("JP", "HTT", "Hata", null),
        PortCode("JP", "HUD", "Hoda", null),
        PortCode("JP", "HUR", "Hannoura", null),
        PortCode("JP", "HUT", "Futami, Niigata", null),
        PortCode("JP", "HWA", "Hamatsuwaki", null),
        PortCode("JP", "HWS", "Hiwasa", null),
        PortCode("JP", "HYG", "Hyugadomari", null),
        PortCode("JP", "HYK", "Hayakawa", null),
        PortCode("JP", "HYM", "Hayama", null),
        PortCode("JP", "HYR", "Hyakunoura", null),
        PortCode("JP", "HYS", "Hisayoshi", null),
        PortCode("JP", "HYT", "Hayato", null),
        PortCode("JP", "IBR", "Iburi", null),
        PortCode("JP", "IBS", "Ibusuki", null),
        PortCode("JP", "ICD", "Icchoda", null),
        PortCode("JP", "ICH", "Ichihara", null),
        PortCode("JP", "ICK", "Ichikawa", null),
        PortCode("JP", "ICO", "Ichikikushikino", Location(31.716667, 130.266667)),
        PortCode("JP", "ICW", "Ishikariwan Shinko", Location(43.35, 141.5)),
        PortCode("JP", "IDA", "Iida", null),
        PortCode("JP", "IDJ", "Indohji", null),
        PortCode("JP", "IDM", "Iwayadomari", null),
        PortCode("JP", "IEJ", "Iejima/Okinawa", null),
        PortCode("JP", "IER", "Ieura", null),
        PortCode("JP", "IES", "Ieshima, Hyogo", null),
        PortCode("JP", "IGO", "Igo", null),
        PortCode("JP", "IGR", "Imagire", null),
        PortCode("JP", "IHA", "Niihama", null),
        PortCode("JP", "IHO", "Ihota", null),
        PortCode("JP", "IIB", "Iibi", null),
        PortCode("JP", "III", "Ii", null),
        PortCode("JP", "IIN", "Nishinoomote", null),
        PortCode("JP", "IKA", "Ikeda, Kagawa", null),
        PortCode("JP", "IKC", "Ikuchi", null),
        PortCode("JP", "IKD", "Ikeda, Wakayama", null),
        PortCode("JP", "IKE", "Ikeshima", null),
        PortCode("JP", "IKJ", "Isshiki", null),
        PortCode("JP", "IKK", "Ikitsuki", Location(33.383333, 129.433333)),
        PortCode("JP", "IKN", "Ikina", null),
        PortCode("JP", "IKR", "Ikara", null),
        PortCode("JP", "IKT", "Ikata", null),
        PortCode("JP", "IKU", "Ikunohama", null),
        PortCode("JP", "IKW", "Ishikawa", Location(26.416667, 127.816667)),
        PortCode("JP", "IMA", "Imafuku", null),
        PortCode("JP", "IMB", "Imabari", null),
        PortCode("JP", "IMI", "Imari", null),
        PortCode("JP", "IMM", "Imi", null),
        PortCode("JP", "IMT", "Imazato", null),
        PortCode("JP", "IMZ", "Imazu", null),
        PortCode("JP", "INA", "Ina", null),
        PortCode("JP", "IND", "Inonada", null),
        PortCode("JP", "INE", "Ine", null),
        PortCode("JP", "ING", "Inugaura", null),
        PortCode("JP", "INK", "Inokushi, Oita", null),
        PortCode("JP", "INO", "Inobe", null),
        PortCode("JP", "INR", "Inatori", null),
        PortCode("JP", "INS", "Innoshima", null),
        PortCode("JP", "INT", "Iinoseto", null),
        PortCode("JP", "INZ", "Inujima", null),
        PortCode("JP", "IOU", "Iwojima, Kagoshima", null),
        PortCode("JP", "IRK", "Irago", null),
        PortCode("JP", "ISA", "Issai", null),
        PortCode("JP", "ISB", "Ishiba", null),
        PortCode("JP", "ISC", "Ishiwaki", null),
        PortCode("JP", "ISD", "Ishida", null),
        PortCode("JP", "ISE", "Ise", null),
        PortCode("JP", "ISG", "Ishigaki", Location(24.333333, 124.15)),
        PortCode("JP", "ISH", "Ishima", null),
        PortCode("JP", "ISI", "Ishikari", null),
        PortCode("JP", "ISK", "Iseki", null),
        PortCode("JP", "ISM", "Ishinomaki", null),
        PortCode("JP", "ISU", "Isuwan", null),
        PortCode("JP", "ISX", "Isozaki", null),
        PortCode("JP", "ISY", "Isahaya", null),
        PortCode("JP", "ITJ", "Itoh, Shizuoka", null),
        PortCode("JP", "ITK", "Itako", null),
        PortCode("JP", "ITO", "Itozaki", null),
        PortCode("JP", "ITS", "Itsukushima", null),
        PortCode("JP", "ITU", "Itoh, Shimane", null),
        PortCode("JP", "IUH", "Inokuchi, Ehime", null),
        PortCode("JP", "IWA", "Iwamatsu", null),
        PortCode("JP", "IWG", "Iwagi,Ehime", null),
        PortCode("JP", "IWH", "Iwafune", null),
        PortCode("JP", "IWI", "Iwaki", null),
        PortCode("JP", "IWK", "Iwakuni", null),
        PortCode("JP", "IWN", "Iwanai", null),
        PortCode("JP", "IWT", "Iwojima, Nagasaki", null),
        PortCode("JP", "IWY", "Iwaya", null),
        PortCode("JP", "IYA", "Iya", null),
        PortCode("JP", "IYM", "Iyomishima", null),
        PortCode("JP", "IYO", "Iyo", null),
        PortCode("JP", "IZH", "Izuhara", null),
        PortCode("JP", "IZI", "Izumi, Nagasaki", null),
        PortCode("JP", "IZM", "Izumi, Aichi", null),
        PortCode("JP", "IZO", "Izumo", null),
        PortCode("JP", "IZS", "Izumisano", null),
        PortCode("JP", "IZU", "Izuka", null),
        PortCode("JP", "IZW", "Inazawa", Location(35.25, 136.783333)),
        PortCode("JP", "JKT", "Kotoura", null),
        PortCode("JP", "JKW", "Jokawauchi", null),
        PortCode("JP", "JON", "Jonoshita", null),
        PortCode("JP", "JTS", "Joetsu", Location(37.15, 138.233333)),
        PortCode("JP", "KAA", "Kada", null),
        PortCode("JP", "KAB", "Kabanoki", null),
        PortCode("JP", "KAC", "Kasaura", null),
        PortCode("JP", "KAD", "Kaita", null),
        PortCode("JP", "KAE", "Kashimae", null),
        PortCode("JP", "KAF", "Kafuri", null),
        PortCode("JP", "KAG", "Kawarago", null),
        PortCode("JP", "KAH", "Kamihira", null),
        PortCode("JP", "KAI", "Kainan", null),
        PortCode("JP", "KAJ", "Kama, Shimane", null),
        PortCode("JP", "KAM", "Kametoku", null),
        PortCode("JP", "KAN", "Karuno", null),
        PortCode("JP", "KAO", "Kashino", null),
        PortCode("JP", "KAR", "Karatsu", null),
        PortCode("JP", "KAT", "Katsuura, Wakayama", null),
        PortCode("JP", "KAU", "Kasumigaura", Location(36.033333, 140.216667)),
        PortCode("JP", "KAW", "Kawauchi", null),
        PortCode("JP", "KAX", "Komoe", null),
        PortCode("JP", "KAZ", "Kaizaki", null),
        PortCode("JP", "KBA", "Katasoba", null),
        PortCode("JP", "KBI", "Kobui", null),
        PortCode("JP", "KBK", "Kafuka", null),
        PortCode("JP", "KBM", "Kabashima", null),
        PortCode("JP", "KBR", "Kubura", null),
        PortCode("JP", "KBS", "Kobishima", null),
        PortCode("JP", "KBT", "Kobato", null),
        PortCode("JP", "KBU", "Kubuki", null),
        PortCode("JP", "KCF", "Kuchinofukuura", null),
        PortCode("JP", "KCH", "Kawachi, Kumamoto", null),
        PortCode("JP", "KCZ", "Kochi", null),
        PortCode("JP", "KDA", "Kishiwada", null),
        PortCode("JP", "KDI", "Kodai", null),
        PortCode("JP", "KDJ", "Kasedo", null),
        PortCode("JP", "KDK", "Kodakashima", null),
        PortCode("JP", "KDM", "Kodomari, Kumamoto", null),
        PortCode("JP", "KDO", "Kadokura", null),
        PortCode("JP", "KDR", "Katadomari", null),
        PortCode("JP", "KDW", "Kadokawa", null),
        PortCode("JP", "KDX", "Kita/Minamidaito", null),
        PortCode("JP", "KEB", "Kebuki", null),
        PortCode("JP", "KEC", "Kechi", null),
        PortCode("JP", "KEE", "Kameike", null),
        PortCode("JP", "KEG", "Kegoya", null),
        PortCode("JP", "KEJ", "Keraji", null),
        PortCode("JP", "KEM", "Keruma", null),
        PortCode("JP", "KER", "Kakeroma", null),
        PortCode("JP", "KFU", "Kohtsufukae", null),
        PortCode("JP", "KGA", "Kakogawa", null),
        PortCode("JP", "KGB", "Kuka", null),
        PortCode("JP", "KGC", "Koguchi", null),
        PortCode("JP", "KGE", "Kumage", null),
        PortCode("JP", "KGJ", "Kigasajima", null),
        PortCode("JP", "KGM", "Kagami", null),
        PortCode("JP", "KGO", "Kumago", null),
        PortCode("JP", "KGR", "Kamagari", null),
        PortCode("JP", "KGS", "Kogushi, Yamaguchi", null),
        PortCode("JP", "KGT", "Kaigata", null),
        PortCode("JP", "KGU", "Kanegusuku", null),
        PortCode("JP", "KHJ", "Kurimamaehama", null),
        PortCode("JP", "KHM", "Ohama, Kagoshima", null),
        PortCode("JP", "KHR", "Kihara", null),
        PortCode("JP", "KHS", "Kurahashi", null),
        PortCode("JP", "KIA", "Kiami", null),
        PortCode("JP", "KIB", "Kibe", null),
        PortCode("JP", "KII", "Kiire", null),
        PortCode("JP", "KIJ", "Niigata", null),
        PortCode("JP", "KIK", "Kikuma", null),
        PortCode("JP", "KIM", "Kineshima", null),
        PortCode("JP", "KIN", "Kinwan", null),
        PortCode("JP", "KIR", "Kitaura, Ehime", null),
        PortCode("JP", "KIS", "Kamaishi", null),
        PortCode("JP", "KIT", "Kitaura, Miyazaki", null),
        PortCode("JP", "KIW", "Kisawa", null),
        PortCode("JP", "KJA", "Kohjima", null),
        PortCode("JP", "KJD", "Kudadon", null),
        PortCode("JP", "KJG", "Kaga, Shimane", null),
        PortCode("JP", "KJI", "Kuji, Iwate", null),
        PortCode("JP", "KJJ", "Koshima", null),
        PortCode("JP", "KJK", "Kajiki", null),
        PortCode("JP", "KJM", "Kameura, Kumamoto", null),
        PortCode("JP", "KJN", "Kannonji", null),
        PortCode("JP", "KJO", "Kinjo", null),
        PortCode("JP", "KJR", "Kiriishi", null),
        PortCode("JP", "KJT", "Kitaura, Akita", null),
        PortCode("JP", "KJU", "Koura, Kagoshima", null),
        PortCode("JP", "KKA", "Karakuma", null),
        PortCode("JP", "KKB", "Kokubo", null),
        PortCode("JP", "KKE", "Komukae", null),
        PortCode("JP", "KKJ", "Kitakyushu", Location(33.833333, 130.833333)),
        PortCode("JP", "KKK", "Kushiku", null),
        PortCode("JP", "KKL", "Kohzaki", null),
        PortCode("JP", "KKM", "Katakami", null),
        PortCode("JP", "KKO", "Komenotsu", null),
        PortCode("JP", "KKR", "Kouri", null),
        PortCode("JP", "KKT", "Kamikatetsu", null),
        PortCode("JP", "KKU", "Kuji, Kagoshima", null),
        PortCode("JP", "KKW", "Kanokawa", null),
        PortCode("JP", "KKX", "Kikaishima", Location(28.316667, 129.983333)),
        PortCode("JP", "KKZ", "Kashikojima", null),
        PortCode("JP", "KMD", "Komoda", null),
        PortCode("JP", "KME", "Kamae", null),
        PortCode("JP", "KMF", "Kaminofuruta", null),
        PortCode("JP", "KMH", "Kumihama", null),
        PortCode("JP", "KMI", "Miyazaki, Miyazaki", null),
        PortCode("JP", "KMJ", "Kumamoto", null),
        PortCode("JP", "KMK", "Kaminokae", null),
        PortCode("JP", "KMM", "Kaminato", null),
        PortCode("JP", "KMN", "Kominato", null),
        PortCode("JP", "KMO", "Kamo", null),
        PortCode("JP", "KMR", "Kameura, Tokushima", null),
        PortCode("JP", "KMS", "Kumeshima", null),
        PortCode("JP", "KMT", "Kimitsu", null),
        PortCode("JP", "KMU", "Kamiura", null),
        PortCode("JP", "KMW", "Kamikawaguchi", null),
        PortCode("JP", "KMX", "Komatsu, Yamaguchi", null),
        PortCode("JP", "KMY", "Kamiyakunagata", null),
        PortCode("JP", "KNA", "Kuwana", null),
        PortCode("JP", "KNB", "Konbukariishi", null),
        PortCode("JP", "KND", "Kanda, Fukuoka", null),
        PortCode("JP", "KNE", "Kinoe", null),
        PortCode("JP", "KNG", "Kuniga", null),
        PortCode("JP", "KNH", "Kunehama", null),
        PortCode("JP", "KNI", "Konagai", null),
        PortCode("JP", "KNJ", "Kisane", null),
        PortCode("JP", "KNK", "Kinkasan", null),
        PortCode("JP", "KNM", "Kanmon", Location(33.9, 130.916667)),
        PortCode("JP", "KNN", "Kin", null),
        PortCode("JP", "KNO", "Konoura", null),
        PortCode("JP", "KNR", "Kohnoura", null),
        PortCode("JP", "KNS", "Kunisaki", null),
        PortCode("JP", "KNT", "Kinomoto", null),
        PortCode("JP", "KNU", "Kinuura", null),
        PortCode("JP", "KNX", "KinNakagusuku", null),
        PortCode("JP", "KNY", "Koniya", null),
        PortCode("JP", "KNZ", "Kanazawa", null),
        PortCode("JP", "KOB", "Koza", null),
        PortCode("JP", "KOD", "Kodomari, Aomori", null),
        PortCode("JP", "KOF", "Konan", null),
        PortCode("JP", "KOG", "Kogushi, Okayama", null),
        PortCode("JP", "KOH", "Kohama", Location(24.333333, 123.983333)),
        PortCode("JP", "KOI", "Koike/Uwajima", null),
        PortCode("JP", "KOJ", "Kagoshima", null),
        PortCode("JP", "KOK", "Kokura", Location(33.8, 130.883333)),
        PortCode("JP", "KOM", "Komatsushima", null),
        PortCode("JP", "KON", "Konoshima", null),
        PortCode("JP", "KOO", "Kohmen", null),
        PortCode("JP", "KOR", "Koura, Kagawa", null),
        PortCode("JP", "KOS", "Kose", null),
        PortCode("JP", "KOU", "Kohzujima", null),
        PortCode("JP", "KOX", "Kaminoseki", null),
        PortCode("JP", "KOY", "Koyoh/Etajima", null),
        PortCode("JP", "KOZ", "Kozuna", null),
        PortCode("JP", "KRA", "Kannoura", null),
        PortCode("JP", "KRB", "Karubi", null),
        PortCode("JP", "KRC", "Kuramai", null),
        PortCode("JP", "KRD", "Kuroda", null),
        PortCode("JP", "KRE", "Kure, Hiroshima", null),
        PortCode("JP", "KRH", "Kurihama", null),
        PortCode("JP", "KRI", "Kurio", null),
        PortCode("JP", "KRJ", "Kuroshima, Okinawa", null),
        PortCode("JP", "KRK", "Karakizaki", null),
        PortCode("JP", "KRM", "Kurokami", null),
        PortCode("JP", "KRN", "Kuranotani", null),
        PortCode("JP", "KRR", "Kujiragaura", null),
        PortCode("JP", "KRS", "Kurushima", null),
        PortCode("JP", "KRT", "Kiritappu", null),
        PortCode("JP", "KRU", "Kurii", null),
        PortCode("JP", "KRX", "Kuroi", null),
        PortCode("JP", "KRY", "Kariya, Saga", null),
        PortCode("JP", "KSA", "Kasaoka", null),
        PortCode("JP", "KSB", "Kusubo", null),
        PortCode("JP", "KSC", "Kashima, Saga", null),
        PortCode("JP", "KSD", "Kasado", null),
        PortCode("JP", "KSE", "Kamoise", null),
        PortCode("JP", "KSF", "Kitsuki", Location(33.416667, 131.616667)),
        PortCode("JP", "KSH", "Kishiku", null),
        PortCode("JP", "KSK", "Kurosaki", null),
        PortCode("JP", "KSM", "Kashima, Ibaraki", null),
        PortCode("JP", "KSN", "Kesennuma", null),
        PortCode("JP", "KSR", "Kishira", null),
        PortCode("JP", "KSS", "Kasasa, Kagoshima", null),
        PortCode("JP", "KST", "Kisakata", null),
        PortCode("JP", "KSU", "Katsumoto", null),
        PortCode("JP", "KSW", "Kashiwa, Ehime", null),
        PortCode("JP", "KSX", "Kosuki", null),
        PortCode("JP", "KSY", "Kasasa, Yamaguchi", null),
        PortCode("JP", "KTA", "Kitanada", null),
        PortCode("JP", "KTG", "Kutsugata", null),
        PortCode("JP", "KTJ", "Kotakarajima", null),
        PortCode("JP", "KTK", "Kataku", null),
        PortCode("JP", "KTL", "Kitakijima", null),
        PortCode("JP", "KTM", "Karatomari", null),
        PortCode("JP", "KTN", "Kitakami", Location(39.283333, 141.116667)),
        PortCode("JP", "KTO", "Kottoi", null),
        PortCode("JP", "KTR", "Kitaura, Kagawa", null),
        PortCode("JP", "KTS", "Katashima", null),
        PortCode("JP", "KTU", "Kohtsuura", null),
        PortCode("JP", "KTX", "Kita/Kitadaito", null),
        PortCode("JP", "KTZ", "Kata", null),
        PortCode("JP", "KUC", "Kuchinotsu", null),
        PortCode("JP", "KUD", "Kudamatsu", null),
        PortCode("JP", "KUE", "Kure, Kochi", null),
        PortCode("JP", "KUF", "Kofu", null),
        PortCode("JP", "KUG", "Kugui", null),
        PortCode("JP", "KUH", "Kushiro", null),
        PortCode("JP", "KUR", "Katsuura, Chiba", null),
        PortCode("JP", "KUT", "Kute", null),
        PortCode("JP", "KUU", "Kumanoe", null),
        PortCode("JP", "KUW", "Kuwanoura", null),
        PortCode("JP", "KUX", "Kuronohama", null),
        PortCode("JP", "KUZ", "Kuzu", null),
        PortCode("JP", "KWA", "Kawanazu", null),
        PortCode("JP", "KWC", "Kawachi, Nagasaki", null),
        PortCode("JP", "KWI", "Kawanoishi", null),
        PortCode("JP", "KWJ", "Kawajiri, Hiroshima", null),
        PortCode("JP", "KWM", "Kawashimo", null),
        PortCode("JP", "KWN", "Kawanoe", null),
        PortCode("JP", "KWR", "Kawajiri, Ibaraki", null),
        PortCode("JP", "KWS", "Kawasaki", null),
        PortCode("JP", "KWT", "Kawatana", null),
        PortCode("JP", "KWX", "Kowa", null),
        PortCode("JP", "KWZ", "Kashiwazaki", null),
        PortCode("JP", "KXK", "Kusukawa", null),
        PortCode("JP", "KXS", "Kasumi", null),
        PortCode("JP", "KYA", "Kanoya", null),
        PortCode("JP", "KYK", "Kanayaki", null),
        PortCode("JP", "KYM", "Kuyama", null),
        PortCode("JP", "KYO", "Koyoh/Kawajiri", null),
        PortCode("JP", "KYR", "Isso", null),
        PortCode("JP", "KZE", "Kozera", null),
        PortCode("JP", "KZH", "Kazuhara", null),
        PortCode("JP", "KZI", "Kijima", null),
        PortCode("JP", "KZJ", "Kozai", null),
        PortCode("JP", "KZK", "Kozukushi", null),
        PortCode("JP", "KZM", "Kazume", null),
        PortCode("JP", "KZR", "Kohjiro", null),
        PortCode("JP", "KZS", "Kazusaminato", null),
        PortCode("JP", "KZU", "Kisarazu", null),
        PortCode("JP", "MAB", "Maruichibi", null),
        PortCode("JP", "MAD", "Maedomari/Iheya", null),
        PortCode("JP", "MAG", "Mategata", null),
        PortCode("JP", "MAI", "Maizuru", null),
        PortCode("JP", "MAK", "Makiyama", null),
        PortCode("JP", "MAM", "Matama", null),
        PortCode("JP", "MAO", "Matsuo", null),
        PortCode("JP", "MAR", "Marugame", null),
        PortCode("JP", "MAS", "Masaki", null),
        PortCode("JP", "MAT", "Matsushima, Nagasaki", null),
        PortCode("JP", "MAU", "Matsuura, Kagoshima", null),
        PortCode("JP", "MAW", "Nishimaizuru", null),
        PortCode("JP", "MBE", "Monbetsu/Abashiri", null),
        PortCode("JP", "MBR", "Mebaruzaki", null),
        PortCode("JP", "MBT", "Motobu", null),
        PortCode("JP", "MCD", "Mochidoi", null),
        PortCode("JP", "MCH", "Mochiishi", null),
        PortCode("JP", "MDJ", "Masuda, Kagoshima", null),
        PortCode("JP", "MDR", "Maedomari/Tarama", null),
        PortCode("JP", "MEG", "Megi", null),
        PortCode("JP", "MEI", "Meihama", null),
        PortCode("JP", "MEN", "Mei", null),
        PortCode("JP", "MER", "Maeura", null),
        PortCode("JP", "MET", "Meitsu", null),
        PortCode("JP", "MGA", "Matsugaura", null),
        PortCode("JP", "MGC", "Maguchi", null),
        PortCode("JP", "MGM", "Magome", null),
        PortCode("JP", "MGN", "Mogine", null),
        PortCode("JP", "MGS", "Megoshima", null),
        PortCode("JP", "MGU", "Magusa", null),
        PortCode("JP", "MGY", "Nagayama", null),
        PortCode("JP", "MHM", "Maehama", null),
        PortCode("JP", "MHN", "Mihowan", null),
        PortCode("JP", "MHR", "Mihara", null),
        PortCode("JP", "MIH", "Mihonoseki", null),
        PortCode("JP", "MII", "Miike, Fukuoka", null),
        PortCode("JP", "MIJ", "Miike, Tokyo", null),
        PortCode("JP", "MIK", "Misaki, Kanagawa", null),
        PortCode("JP", "MIN", "Minamata", null),
        PortCode("JP", "MIR", "Miura/Mitsushima", null),
        PortCode("JP", "MIS", "Misumi, Kumamoto", null),
        PortCode("JP", "MIT", "Mitaka, Hiroshima", null),
        PortCode("JP", "MIY", "Miyazu", null),
        PortCode("JP", "MIZ", "Mizushima", null),
        PortCode("JP", "MJR", "Mitajiri", Location(34.033333, 131.583333)),
        PortCode("JP", "MKA", "Mukata", null),
        PortCode("JP", "MKG", "Makigawa", null),
        PortCode("JP", "MKI", "Misaki, Kochi", null),
        PortCode("JP", "MKJ", "Mikisato", null),
        PortCode("JP", "MKK", "Makurazaki", null),
        PortCode("JP", "MKM", "Mikame", null),
        PortCode("JP", "MKR", "Mikurajima", null),
        PortCode("JP", "MKS", "Mitsukoshima", null),
        PortCode("JP", "MKU", "Mukunoura", null),
        PortCode("JP", "MKW", "Mikawa", null),
        PortCode("JP", "MKX", "Mishima, Kawanoe", null),
        PortCode("JP", "MMA", "Maenohama", null),
        PortCode("JP", "MMD", "Minamidaito", Location(25.833333, 131.233333)),
        PortCode("JP", "MMI", "Misumi, Shimane", null),
        PortCode("JP", "MMM", "Mageshimamisaki", null),
        PortCode("JP", "MMT", "Mimitsu", null),
        PortCode("JP", "MMY", "Miyakojima", Location(24.783333, 125.3)),
        PortCode("JP", "MNA", "Manazuru", null),
        PortCode("JP", "MNE", "Mine", null),
        PortCode("JP", "MNG", "Matsunaga", null),
        PortCode("JP", "MNJ", "Minna/Motobu", null),
        PortCode("JP", "MNM", "Minami", null),
        PortCode("JP", "MNN", "Minna/Tarama", null),
        PortCode("JP", "MNO", "Miyanoura/Kamiyaku", null),
        PortCode("JP", "MNR", "Miyanoura, Nagasaki", null),
        PortCode("JP", "MNT", "Minato, Hyogo", null),
        PortCode("JP", "MNY", "Minmaya", null),
        PortCode("JP", "MOG", "Mogi", null),
        PortCode("JP", "MOJ", "Moji/Kitakyushu", Location(33.9, 130.966667)),
        PortCode("JP", "MOM", "Morodomi", null),
        PortCode("JP", "MOO", "Morie", null),
        PortCode("JP", "MOR", "Mori", null),
        PortCode("JP", "MOT", "Motomachi", null),
        PortCode("JP", "MOU", "Motoura/Toshima", null),
        PortCode("JP", "MOX", "Monoi", null),
        PortCode("JP", "MQT", "Mito, Kagawa", null),
        PortCode("JP", "MRA", "Matsushima, Miyagi", null),
        PortCode("JP", "MRE", "Mure", null),
        PortCode("JP", "MRG", "Moriage", null),
        PortCode("JP", "MRH", "Morinohama", null),
        PortCode("JP", "MRJ", "Murotomisaki", null),
        PortCode("JP", "MRK", "Morakui", null),
        PortCode("JP", "MRM", "Muromoto", null),
        PortCode("JP", "MRO", "Murokita", null),
        PortCode("JP", "MRS", "Murotsu, Hyogo", null),
        PortCode("JP", "MRT", "Murotsu, Yamaguchi", null),
        PortCode("JP", "MRU", "Maruo", null),
        PortCode("JP", "MRZ", "Morozaki", null),
        PortCode("JP", "MSA", "Matsusaka", null),
        PortCode("JP", "MSD", "Masuda, Shimane", null),
        PortCode("JP", "MSH", "Musashi", null),
        PortCode("JP", "MSI", "MieShikimi", null),
        PortCode("JP", "MSK", "Mashike", null),
        PortCode("JP", "MSO", "Misho", null),
        PortCode("JP", "MSR", "Mishiro", null),
        PortCode("JP", "MSS", "Matsushima, Okayama", null),
        PortCode("JP", "MST", "Misato", null),
        PortCode("JP", "MSX", "Misaki, Ehime", null),
        PortCode("JP", "MTC", "Mitachi", null),
        PortCode("JP", "MTE", "Matsue", null),
        PortCode("JP", "MTH", "Mitsuhama", null),
        PortCode("JP", "MTI", "Mitarai", null),
        PortCode("JP", "MTK", "Mitsukue", null),
        PortCode("JP", "MTM", "Matsumae", null),
        PortCode("JP", "MTO", "Motoura/Azuma", null),
        PortCode("JP", "MTR", "Mutsure", null),
        PortCode("JP", "MTS", "Matsuura, Nagasaki", null),
        PortCode("JP", "MTU", "Matsuura, Oita", null),
        PortCode("JP", "MTY", "Matoya", null),
        PortCode("JP", "MTZ", "Matsuzaki", null),
        PortCode("JP", "MUG", "Mugi", null),
        PortCode("JP", "MUK", "Mukaishima", null),
        PortCode("JP", "MUR", "Muroran", null),
        PortCode("JP", "MUT", "Mutsuogawara", null),
        PortCode("JP", "MUX", "Murotsu, Kochi", null),
        PortCode("JP", "MUY", "Miyanoura, Kagawa", null),
        PortCode("JP", "MWA", "Maruiwa", null),
        PortCode("JP", "MWR", "Mawari", null),
        PortCode("JP", "MXT", "Mita", null),
        PortCode("JP", "MYA", "Muya", null),
        PortCode("JP", "MYG", "Miyagahama", null),
        PortCode("JP", "MYI", "Miyagi", Location(36.433333, 139.166667)),
        PortCode("JP", "MYJ", "Matsuyama", null),
        PortCode("JP", "MYK", "Miyako, Iwate", null),
        PortCode("JP", "MYN", "Miyanoura/Azuma", null),
        PortCode("JP", "MYT", "Miyoshi, Tokushima", Location(34.016667, 133.8)),
        PortCode("JP", "MYU", "Miyaura", null),
        PortCode("JP", "MYX", "Muta, Nagasaki", Location(31.816667, 130.266667)),
        PortCode("JP", "MZK", "Miyazaki, Ehime", null),
        PortCode("JP", "MZM", "Murozumi", null),
        PortCode("JP", "MZR", "Motozaru", null),
        PortCode("JP", "MZS", "Mizusaki", null),
        PortCode("JP", "NAA", "Nagaura, Nagasaki", null),
        PortCode("JP", "NAB", "Nagara", null),
        PortCode("JP", "NAD", "Nadahama", null),
        PortCode("JP", "NAG", "Nagahama, Shimane", null),
        PortCode("JP", "NAH", "Naha, Okinawa", null),
        PortCode("JP", "NAI", "Narashino", Location(35.666667, 140.016667)),
        PortCode("JP", "NAK", "Nakagusuku", null),
        PortCode("JP", "NAM", "Nama", null),
        PortCode("JP", "NAN", "Nakanoseki", Location(34.0, 131.533333)),
        PortCode("JP", "NAO", "Naoetsu", null),
        PortCode("JP", "NAR", "Naarai", null),
        PortCode("JP", "NAS", "Naoshima", null),
        PortCode("JP", "NAT", "Nakatsu", null),
        PortCode("JP", "NAY", "Nagayo", null),
        PortCode("JP", "NAZ", "Naze", null),
        PortCode("JP", "NBS", "Nobeokashinko", null),
        PortCode("JP", "NBU", "Nobu/Mitsushima", null),
        PortCode("JP", "NDI", "Nishi/Minamidaito", null),
        PortCode("JP", "NDY", "Nadayama", null),
        PortCode("JP", "NEJ", "Nejime", null),
        PortCode("JP", "NEM", "Nemuro", null),
        PortCode("JP", "NEO", "Neo", null),
        PortCode("JP", "NEX", "Nagae, Ehime", null),
        PortCode("JP", "NEZ", "Nezugaseki", null),
        PortCode("JP", "NGA", "Nagareyama, Chiba", Location(35.85, 139.9)),
        PortCode("JP", "NGD", "Nagouda", null),
        PortCode("JP", "NGE", "Nagae, Shimane", null),
        PortCode("JP", "NGG", "Nagame", null),
        PortCode("JP", "NGH", "Nagahama, Ehime", null),
        PortCode("JP", "NGI", "Neghishi/Yokohama", null),
        PortCode("JP", "NGM", "Nagimi", null),
        PortCode("JP", "NGN", "Naigainoura", null),
        PortCode("JP", "NGO", "Nagoya, Aichi", null),
        PortCode("JP", "NGR", "Nagaura/Yokosuka", null),
        PortCode("JP", "NGS", "Nagasaki", null),
        PortCode("JP", "NGU", "Nagasu, Kumamoto", null),
        PortCode("JP", "NGY", "Nagaokakyo", Location(34.933333, 135.7)),
        PortCode("JP", "NHA", "Nakahama, Hiroshima", null),
        PortCode("JP", "NHI", "Nahari", null),
        PortCode("JP", "NHJ", "Noheji", null),
        PortCode("JP", "NHM", "Nagahama, Shiga", null),
        PortCode("JP", "NHN", "Nagasakinohana", null),
        PortCode("JP", "NHR", "Nishihara", null),
        PortCode("JP", "NIA", "Nita", null),
        PortCode("JP", "NIC", "Nichinan", null),
        PortCode("JP", "NID", "Nishi/Kitadaito", null),
        PortCode("JP", "NIH", "Niigatahigashi", null),
        PortCode("JP", "NIJ", "Niijima", null),
        PortCode("JP", "NIK", "Nikaho", Location(39.383333, 140.083333)),
        PortCode("JP", "NIM", "Nima", null),
        PortCode("JP", "NIN", "Niigatanishi", null),
        PortCode("JP", "NIO", "Nio", null),
        PortCode("JP", "NIS", "Nishinaka", null),
        PortCode("JP", "NIT", "Namikata", null),
        PortCode("JP", "NIX", "Nii", null),
        PortCode("JP", "NJM", "Nakajima", null),
        PortCode("JP", "NJR", "Nojiri", null),
        PortCode("JP", "NKD", "Nakada", null),
        PortCode("JP", "NKH", "Nakahama, Tottori", null),
        PortCode("JP", "NKJ", "Nakahama, Kyoto", null),
        PortCode("JP", "NKK", "Nakakoshiki", null),
        PortCode("JP", "NKL", "Nakama, Kagoshima", null),
        PortCode("JP", "NKM", "Nakama, Okinawa", null),
        PortCode("JP", "NKN", "Nakanoura", null),
        PortCode("JP", "NKO", "Nanko", null),
        PortCode("JP", "NKR", "Nakiri", null),
        PortCode("JP", "NKS", "Nakanoshima", null),
        PortCode("JP", "NKT", "Nakata, Hiroshima", null),
        PortCode("JP", "NKX", "Nakanosaku", null),
        PortCode("JP", "NKY", "Nakayama", null),
        PortCode("JP", "NKZ", "Nakashima", null),
        PortCode("JP", "NMA", "Nagahama, Kagoshima", null),
        PortCode("JP", "NMC", "Nakamichi", Location(35.583333, 138.583333)),
        PortCode("JP", "NMI", "Nomi", null),
        PortCode("JP", "NMK", "Nomaike", null),
        PortCode("JP", "NMT", "Nakaminato", null),
        PortCode("JP", "NNH", "Nunohama", null),
        PortCode("JP", "NNK", "Nenokuchi", null),
        PortCode("JP", "NNO", "Nanao", null),
        PortCode("JP", "NNT", "Nanatsugama", null),
        PortCode("JP", "NOA", "Nago", Location(26.583333, 127.966667)),
        PortCode("JP", "NOB", "Nobeoka", null),
        PortCode("JP", "NOH", "Nohara", null),
        PortCode("JP", "NOJ", "Onojo", Location(33.533333, 130.483333)),
        PortCode("JP", "NOM", "Nomizaki", null),
        PortCode("JP", "NON", "Nonohama", null),
        PortCode("JP", "NOU", "Noh", null),
        PortCode("JP", "NQH", "Noho", null),
        PortCode("JP", "NRO", "Narao", null),
        PortCode("JP", "NRS", "Narushima", null),
        PortCode("JP", "NRU", "Naruto", null),
        PortCode("JP", "NSA", "Nagashima", null),
        PortCode("JP", "NSB", "Nishibe", null),
        PortCode("JP", "NSH", "Nishishioya", null),
        PortCode("JP", "NSI", "Nishiesan", null),
        PortCode("JP", "NSK", "Nishiki", null),
        PortCode("JP", "NSM", "Nishimura", null),
        PortCode("JP", "NSR", "Noshiro", null),
        PortCode("JP", "NST", "Nishikata", null),
        PortCode("JP", "NSU", "Nagasu, Oita", null),
        PortCode("JP", "NSX", "Nasa", null),
        PortCode("JP", "NTO", "Nishitokyo", Location(34.733333, 139.533333)),
        PortCode("JP", "NTX", "Nakata, Kumamoto", null),
        PortCode("JP", "NTY", "Nanatsuyama", null),
        PortCode("JP", "NUM", "Numazu", null),
        PortCode("JP", "NUR", "Nishiura", null),
        PortCode("JP", "NWA", "Nyugawa", null),
        PortCode("JP", "NXG", "Nigishima", null),
        PortCode("JP", "NYA", "Nishinomiya", null),
        PortCode("JP", "NYK", "Nyukou", null),
        PortCode("JP", "NYZ", "Nyuzu", null),
        PortCode("JP", "OAA", "Okada", null),
        PortCode("JP", "OAD", "Onoaida", null),
        PortCode("JP", "OAR", "Oarai", null),
        PortCode("JP", "OAT", "Ogatsu", null),
        PortCode("JP", "OAX", "Oma", null),
        PortCode("JP", "OBA", "Obama, Mie", null),
        PortCode("JP", "OBB", "Obama, Nagasaki", null),
        PortCode("JP", "OBE", "Obe, Ehime", null),
        PortCode("JP", "OBM", "Obama, Fukui", null),
        PortCode("JP", "OBS", "Ohbishima", null),
        PortCode("JP", "OBX", "Ohbe, Kagawa", null),
        PortCode("JP", "OCH", "Okunouchi", null),
        PortCode("JP", "ODA", "Odahigashi", null),
        PortCode("JP", "ODM", "Odomari", null),
        PortCode("JP", "ODN", "Ohdana", null),
        PortCode("JP", "ODO", "Odoh", null),
        PortCode("JP", "ODS", "Odeshima", null),
        PortCode("JP", "OFK", "Ohfunakoshi", null),
        PortCode("JP", "OFR", "Ohfukaura", null),
        PortCode("JP", "OFT", "Ohfunato", null),
        PortCode("JP", "OGA", "Ogasawara", null),
        PortCode("JP", "OGC", "Ongachi", null),
        PortCode("JP", "OGE", "Ohge", null),
        PortCode("JP", "OGF", "Ogifushi", null),
        PortCode("JP", "OGH", "Oginohama", null),
        PortCode("JP", "OGI", "Ogi, Niigata", null),
        PortCode("JP", "OGK", "Ogi, Kagawa", null),
        PortCode("JP", "OGM", "Ogomori", null),
        PortCode("JP", "OGS", "Ohgishima", null),
        PortCode("JP", "OGU", "Ohgushi", null),
        PortCode("JP", "OHA", "Ohama, Kagawa", null),
        PortCode("JP", "OHM", "Ohama, Ehime", null),
        PortCode("JP", "OHO", "Ohi", null),
        PortCode("JP", "OHT", "Ohata", null),
        PortCode("JP", "OIG", "Ohigawa", null),
        PortCode("JP", "OII", "Ogi, Ishikawa", null),
        PortCode("JP", "OIM", "Ohshima, Tokyo", null),
        PortCode("JP", "OIS", "Oiso", null),
        PortCode("JP", "OIT", "Oita", null),
        PortCode("JP", "OIU", "Okiura, Hiroshima", null),
        PortCode("JP", "OJI", "Ojika", null),
        PortCode("JP", "OJM", "Omosu", null),
        PortCode("JP", "OJO", "Osako", null),
        PortCode("JP", "OKB", "Okubo, Tokyo", null),
        PortCode("JP", "OKC", "Okitsu, Chiba", null),
        PortCode("JP", "OKG", "Okogi", null),
        PortCode("JP", "OKH", "Ohkawara", null),
        PortCode("JP", "OKI", "Oki", null),
        PortCode("JP", "OKJ", "Okayama", null),
        PortCode("JP", "OKK", "Okinokojima", null),
        PortCode("JP", "OKM", "Okamoto", null),
        PortCode("JP", "OKN", "Okinajima", null),
        PortCode("JP", "OKR", "Ohbukura/Uwajima", null),
        PortCode("JP", "OKS", "Okiuranishi", null),
        PortCode("JP", "OKT", "Okitsu, Shizuoka", null),
        PortCode("JP", "OKU", "Oku", null),
        PortCode("JP", "OKW", "Okawa, Wakayama", null),
        PortCode("JP", "OKX", "Okiura, Yamaguchi", null),
        PortCode("JP", "OMA", "Aomi", Location(35.616667, 139.783333)),
        PortCode("JP", "OMC", "Omachi", Location(36.833333, 138.416667)),
        PortCode("JP", "OMD", "Omodaka", null),
        PortCode("JP", "OMH", "Omotehama", null),
        PortCode("JP", "OMI", "Omi", null),
        PortCode("JP", "OMJ", "Omura", null),
        PortCode("JP", "OMN", "Omon", null),
        PortCode("JP", "OMO", "Omoto", null),
        PortCode("JP", "OMR", "Okamura", null),
        PortCode("JP", "OMS", "Omishima", null),
        PortCode("JP", "OMT", "Ominato", null),
        PortCode("JP", "OMU", "Omuta", null),
        PortCode("JP", "OMW", "Omonawa", null),
        PortCode("JP", "OMX", "Ohama, Tottori", null),
        PortCode("JP", "OMY", "Omiyaji", null),
        PortCode("JP", "OMZ", "Omaezaki", null),
        PortCode("JP", "ONA", "Onahama", null),
        PortCode("JP", "OND", "Onoda", null),
        PortCode("JP", "ONE", "Ohnejime", null),
        PortCode("JP", "ONG", "Onagawa", null),
        PortCode("JP", "ONI", "Onishi", null),
        PortCode("JP", "ONJ", "Oniike", null),
        PortCode("JP", "ONK", "Oniki", null),
        PortCode("JP", "ONO", "Onomichi", null),
        PortCode("JP", "ONS", "Ohnishi/Ohsaki", null),
        PortCode("JP", "ONW", "Oniwaki", null),
        PortCode("JP", "ONX", "OnomichiItozaki", null),
        PortCode("JP", "OOA", "Oura, Saga", null),
        PortCode("JP", "OOB", "Obatake", null),
        PortCode("JP", "OOC", "Ochiyo", null),
        PortCode("JP", "OOG", "Ohgaki", null),
        PortCode("JP", "OOH", "Ohama, Okayama", null),
        PortCode("JP", "OOJ", "Okubo, Kagoshima", null),
        PortCode("JP", "OOM", "Ohshima, Kagawa", null),
        PortCode("JP", "OON", "Ohnoh", null),
        PortCode("JP", "OOO", "Ozu", null),
        PortCode("JP", "OOR", "Oura/Kasaoka", null),
        PortCode("JP", "OOW", "Okawa, Nagasaki", null),
        PortCode("JP", "OPA", "Oppama", Location(35.3, 139.616667)),
        PortCode("JP", "ORA", "Ohra", null),
        PortCode("JP", "ORG", "Origami", null),
        PortCode("JP", "ORN", "Orino", null),
        PortCode("JP", "ORR", "Oura/Uchinoura", null),
        PortCode("JP", "ORX", "Oura/Marugame", null),
        PortCode("JP", "OSA", "Osaka", Location(34.666667, 135.5)),
        PortCode("JP", "OSD", "Oshidomari", null),
        PortCode("JP", "OSE", "Osoe", null),
        PortCode("JP", "OSG", "Ogi", Location(33.283333, 130.2)),
        PortCode("JP", "OSH", "Ohshima, Wakayama", null),
        PortCode("JP", "OSI", "Ohshima, Ehime", null),
        PortCode("JP", "OSJ", "Otsu, Ibaraki", null),
        PortCode("JP", "OSK", "Osaki, Miyagi", null),
        PortCode("JP", "OSL", "Oshima, Yamaguchi", null),
        PortCode("JP", "OSM", "Ôshima, Nagasaki", Location(33.066667, 129.616667)),
        PortCode("JP", "OSN", "Osaki/Mitsushima", null),
        PortCode("JP", "OSO", "Ohshima, Miyazaki", null),
        PortCode("JP", "OSR", "Ohgasari", null),
        PortCode("JP", "OSS", "Ohshima, Fukuoka", null),
        PortCode("JP", "OST", "Osetoyanagi", null),
        PortCode("JP", "OSU", "Osuki", null),
        PortCode("JP", "OSX", "Osaki, Kagoshima", null),
        PortCode("JP", "OTA", "Otao", null),
        PortCode("JP", "OTJ", "Otsuchi", null),
        PortCode("JP", "OTK", "Otake", null),
        PortCode("JP", "OTM", "Otomi", null),
        PortCode("JP", "OTO", "Osato", null),
        PortCode("JP", "OTR", "Otaru", null),
        PortCode("JP", "OTU", "Otsu, Shiga", null),
        PortCode("JP", "OTW", "Otawa", null),
        PortCode("JP", "OUA", "Oura/Ariake", null),
        PortCode("JP", "OUK", "Osaka, Tottori", null),
        PortCode("JP", "OUM", "Omu", null),
        PortCode("JP", "OUR", "Oura/Kamitsushima", null),
        PortCode("JP", "OUS", "Ohse", null),
        PortCode("JP", "OWA", "Owase", null),
        PortCode("JP", "OYA", "Ojoya", null),
        PortCode("JP", "OYB", "Oyabu", null),
        PortCode("JP", "OYM", "Ohyama/Mitsushima", null),
        PortCode("JP", "OZJ", "Ohzuku", null),
        PortCode("JP", "OZU", "Ozuku", null),
        PortCode("JP", "OZX", "Ozaki", null),
        PortCode("JP", "QSG", "Saga, Saga", null),
        PortCode("JP", "RAU", "Rausu", null),
        PortCode("JP", "RBN", "Noboribetsu", Location(42.45, 141.166667)),
        PortCode("JP", "RHK", "Reihoku", null),
        PortCode("JP", "RKO", "Rokko Island", null),
        PortCode("JP", "RMI", "Rumoi", null),
        PortCode("JP", "RND", "Ronden", null),
        PortCode("JP", "RYA", "Ryuo", Location(35.666667, 16.616667)),
        PortCode("JP", "RYG", "Ryugamizu", null),
        PortCode("JP", "RYO", "Ryotsu", null),
        PortCode("JP", "RYS", "Ryohshida", null),
        PortCode("JP", "SAB", "Saba", null),
        PortCode("JP", "SAC", "Sai, Shimane", null),
        PortCode("JP", "SAD", "Saidoh", null),
        PortCode("JP", "SAE", "Saiki", null),
        PortCode("JP", "SAG", "Saganoseki", null),
        PortCode("JP", "SAI", "Saigo, Shimane", null),
        PortCode("JP", "SAJ", "Saijo", null),
        PortCode("JP", "SAK", "Sakai", null),
        PortCode("JP", "SAM", "Samani", null),
        PortCode("JP", "SAN", "Sanbonmatsu", null),
        PortCode("JP", "SAO", "Sato", null),
        PortCode("JP", "SAR", "Shikaura", null),
        PortCode("JP", "SAS", "Sasago", null),
        PortCode("JP", "SAT", "Sakate", null),
        PortCode("JP", "SAU", "Sakitsu", null),
        PortCode("JP", "SAW", "Sagawa", null),
        PortCode("JP", "SAZ", "Saza", null),
        PortCode("JP", "SBH", "Shibetsu", Location(43.65, 145.116667)),
        PortCode("JP", "SBK", "Sakaisenboku", null),
        PortCode("JP", "SBS", "Shibushi", null),
        PortCode("JP", "SBU", "Shibaura", null),
        PortCode("JP", "SBY", "Shibayama", null),
        PortCode("JP", "SCH", "Shichirinagahama", null),
        PortCode("JP", "SCR", "Shichirui", null),
        PortCode("JP", "SDA", "Shimoda, Nagasaki", null),
        PortCode("JP", "SDJ", "Sendai, Miyagi", Location(38.133333, 140.916667)),
        PortCode("JP", "SDK", "Shitooke", null),
        PortCode("JP", "SDS", "Sendaishinko", null),
        PortCode("JP", "SDU", "Sodegaura", null),
        PortCode("JP", "SDZ", "Saidaiji", null),
        PortCode("JP", "SEB", "Seibu", null),
        PortCode("JP", "SEG", "Seigaura", null),
        PortCode("JP", "SEI", "Seki", Location(35.483333, 136.916667)),
        PortCode("JP", "SEK", "Sekinehama", null),
        PortCode("JP", "SEN", "Satsumasendai", Location(31.816667, 130.25)),
        PortCode("JP", "SEQ", "Se/Izuhara", null),
        PortCode("JP", "SES", "Sesoko", null),
        PortCode("JP", "SET", "Seto", Location(32.933333, 129.633333)),
        PortCode("JP", "SEZ", "Sezaki", null),
        PortCode("JP", "SGA", "Saga, Kochi", null),
        PortCode("JP", "SGE", "Suge", null),
        PortCode("JP", "SGI", "Shigetomi", null),
        PortCode("JP", "SGJ", "Sagi", null),
        PortCode("JP", "SGM", "Sendaishiogama", null),
        PortCode("JP", "SGR", "Sagara", null),
        PortCode("JP", "SGT", "Shiogatani", null),
        PortCode("JP", "SGU", "Saigo, Nagasaki", null),
        PortCode("JP", "SGW", "Segawa", null),
        PortCode("JP", "SGX", "Sonogi", null),
        PortCode("JP", "SHG", "Shinagawa, Tokyo", Location(35.6, 139.716667)),
        PortCode("JP", "SHH", "Shirahama, Kagoshima", null),
        PortCode("JP", "SHJ", "Shinko", Location(36.566667, 138.066667)),
        PortCode("JP", "SHK", "Shinkiba", null),
        PortCode("JP", "SHN", "Shingu", null),
        PortCode("JP", "SHR", "Shari", null),
        PortCode("JP", "SHS", "Shimonoseki", null),
        PortCode("JP", "SHU", "Shushi", null),
        PortCode("JP", "SHZ", "Shimazuya", null),
        PortCode("JP", "SIA", "Shimoda, Kumamoto", null),
        PortCode("JP", "SID", "Shido", null),
        PortCode("JP", "SIG", "Shigei", null),
        PortCode("JP", "SIH", "Shirahama, Okinawa", null),
        PortCode("JP", "SIK", "Shikamachi", null),
        PortCode("JP", "SIM", "Shimama", null),
        PortCode("JP", "SIN", "Shiinoki", null),
        PortCode("JP", "SIO", "Shioya, Ishikawa", null),
        PortCode("JP", "SIR", "Shirahama, Nagasaki", null),
        PortCode("JP", "SIS", "Shishikui", null),
        PortCode("JP", "SIT", "Shitanoura", null),
        PortCode("JP", "SJA", "Sai, Aomori", null),
        PortCode("JP", "SJI", "Shishijima, Kagawa", null),
        PortCode("JP", "SJM", "Shishijima, Kagoshima", null),
        PortCode("JP", "SJR", "Shiroko", null),
        PortCode("JP", "SKB", "Shibukawa", null),
        PortCode("JP", "SKD", "Sakaide", null),
        PortCode("JP", "SKH", "Sakihama", null),
        PortCode("JP", "SKK", "Sakaki", null),
        PortCode("JP", "SKM", "Shikama", null),
        PortCode("JP", "SKN", "Shikinejima", null),
        PortCode("JP", "SKO", "Sakoshi", null),
        PortCode("JP", "SKR", "Sakuraikako", null),
        PortCode("JP", "SKT", "Sakata", null),
        PortCode("JP", "SKU", "Shiraku", null),
        PortCode("JP", "SKW", "Shinkawa, Aichi", null),
        PortCode("JP", "SKY", "Sekiya", null),
        PortCode("JP", "SKZ", "Shikokuchuo", Location(33.983333, 133.55)),
        PortCode("JP", "SMA", "Souma", null),
        PortCode("JP", "SMB", "Shimabara", null),
        PortCode("JP", "SMD", "Shimoda, Shizuoka", null),
        PortCode("JP", "SME", "Same", null),
        PortCode("JP", "SMH", "Shimohisage", null),
        PortCode("JP", "SMI", "Sumie", null),
        PortCode("JP", "SMJ", "Shinmoji", Location(33.866667, 130.983333)),
        PortCode("JP", "SMM", "Shimamaki", null),
        PortCode("JP", "SMN", "Sakaiminato", null),
        PortCode("JP", "SMO", "Shimoda, Kochi", null),
        PortCode("JP", "SMR", "Shimodomari/Mikame", null),
        PortCode("JP", "SMT", "Shimotsu", null),
        PortCode("JP", "SMU", "Sakimui", null),
        PortCode("JP", "SMY", "Sumiyoshi", null),
        PortCode("JP", "SMZ", "Shimizu", null),
        PortCode("JP", "SNA", "Sonai/Yonaguni", null),
        PortCode("JP", "SNE", "Sone", null),
        PortCode("JP", "SNI", "Sonai/Taketomi", null),
        PortCode("JP", "SNJ", "Shinojima", null),
        PortCode("JP", "SNK", "Shinkawa, Kagoshima", null),
        PortCode("JP", "SNM", "Sanami", null),
        PortCode("JP", "SNN", "Shonan", null),
        PortCode("JP", "SNO", "Shitanoe", null),
        PortCode("JP", "SNR", "Shukunoura", null),
        PortCode("JP", "SNU", "Shimanoura", null),
        PortCode("JP", "SNW", "Shinokawa", null),
        PortCode("JP", "SNX", "Sanagi", null),
        PortCode("JP", "SNZ", "Shinzaike", null),
        PortCode("JP", "SOG", "Sogo", null),
        PortCode("JP", "SOH", "Shiohama", null),
        PortCode("JP", "SOO", "Shimonokae", null),
        PortCode("JP", "SOR", "Sonoura", null),
        PortCode("JP", "SOT", "Sotodomari/Nishiumi", null),
        PortCode("JP", "SOY", "Soya", null),
        PortCode("JP", "SOZ", "Sozu", null),
        PortCode("JP", "SRA", "Shiraki", null),
        PortCode("JP", "SRH", "Shirahama, Kagawa", null),
        PortCode("JP", "SRJ", "Shiro", null),
        PortCode("JP", "SRK", "Shirosaki", null),
        PortCode("JP", "SRO", "Shiraoi", null),
        PortCode("JP", "SRS", "Shirose", null),
        PortCode("JP", "SRT", "Shirakata", null),
        PortCode("JP", "SRX", "Shirahama, Chiba", null),
        PortCode("JP", "SRZ", "Sakurajima", null),
        PortCode("JP", "SSA", "Shimotsuura", null),
        PortCode("JP", "SSB", "Sasebo", null),
        PortCode("JP", "SSE", "Sasue", null),
        PortCode("JP", "SSH", "Shishiboe", null),
        PortCode("JP", "SSI", "Sashiki", null),
        PortCode("JP", "SSJ", "Shisakajima", null),
        PortCode("JP", "SSK", "Saizaki", null),
        PortCode("JP", "SSM", "Shishimi", null),
        PortCode("JP", "SSN", "Sasuna", null),
        PortCode("JP", "SSS", "Saikai", Location(32.933333, 129.65)),
        PortCode("JP", "SSU", "Sensyu", Location(34.433333, 135.25)),
        PortCode("JP", "SSZ", "Shimada", Location(34.833333, 138.183333)),
        PortCode("JP", "STA", "Sata", null),
        PortCode("JP", "STB", "Shitaba", null),
        PortCode("JP", "STD", "Setoda", null),
        PortCode("JP", "STE", "Satoura", null),
        PortCode("JP", "STI", "Shimotsui", null),
        PortCode("JP", "STJ", "Shikata", null),
        PortCode("JP", "STN", "Setana", null),
        PortCode("JP", "STO", "Sakito", null),
        PortCode("JP", "STR", "Shirotori", null),
        PortCode("JP", "STT", "Seto, Kagoshima", null),
        PortCode("JP", "STU", "Suttsu", null),
        PortCode("JP", "STW", "Satsukawawan", null),
        PortCode("JP", "STZ", "Saitozaki", null),
        PortCode("JP", "SUE", "Sunoe", null),
        PortCode("JP", "SUG", "Suga", null),
        PortCode("JP", "SUH", "Sumoto, Hyogo", null),
        PortCode("JP", "SUK", "Sukumowan", Location(32.916667, 132.716667)),
        PortCode("JP", "SUM", "Suminoe", null),
        PortCode("JP", "SUR", "Sugeura", null),
        PortCode("JP", "SUS", "Susa", null),
        PortCode("JP", "SUT", "Sumoto, Kumamoto", null),
        PortCode("JP", "SUU", "Sugawa", null),
        PortCode("JP", "SUW", "Suwa", null),
        PortCode("JP", "SUZ", "Susaki", null),
        PortCode("JP", "SWA", "Shimokawaguchi", null),
        PortCode("JP", "SXM", "Sunami", null),
        PortCode("JP", "SXT", "Seto, Kagawa", null),
        PortCode("JP", "SXZ", "Nakanoto", Location(36.983333, 136.9)),
        PortCode("JP", "SYA", "Shioya, Okinawa", null),
        PortCode("JP", "SYD", "Sanyo Onoda Yamaguchi", Location(34.083333, 131.183333)),
        PortCode("JP", "SYG", "Shioyagamoto", null),
        PortCode("JP", "SYM", "Sonoyama", null),
        PortCode("JP", "SYO", "Shoura", null),
        PortCode("JP", "SYZ", "Shiriyazaki", null),
        PortCode("JP", "SZG", "Shizugawa", null),
        PortCode("JP", "SZI", "Shinjima", null),
        PortCode("JP", "SZK", "Senzaki", null),
        PortCode("JP", "SZU", "Shizuura", null),
        PortCode("JP", "TAA", "Takamijima", null),
        PortCode("JP", "TAB", "Tabugawa", null),
        PortCode("JP", "TAC", "Tachiyama", null),
        PortCode("JP", "TAD", "Tadotsu", null),
        PortCode("JP", "TAE", "Tanabe", null),
        PortCode("JP", "TAG", "Tagi", null),
        PortCode("JP", "TAH", "Takahama, Ehime", null),
        PortCode("JP", "TAJ", "Tajiri", null),
        PortCode("JP", "TAK", "Takamatsu", null),
        PortCode("JP", "TAL", "Tainouchi", null),
        PortCode("JP", "TAM", "Tamano", null),
        PortCode("JP", "TAN", "Tanagawa", null),
        PortCode("JP", "TAO", "Tago", null),
        PortCode("JP", "TAQ", "Taira", null),
        PortCode("JP", "TAR", "Tahara", null),
        PortCode("JP", "TAS", "Takeshiki", null),
        PortCode("JP", "TAT", "Tatsugo", null),
        PortCode("JP", "TAW", "Tannowa", null),
        PortCode("JP", "TAZ", "Tai", null),
        PortCode("JP", "TBN", "Tachibana", null),
        PortCode("JP", "TBO", "Tobo", Location(33.483333, 129.933333)),
        PortCode("JP", "TBR", "Tabira", null),
        PortCode("JP", "TBS", "Awajikoryunotsubasa", null),
        PortCode("JP", "TBT", "Tobata/Kitakyushu", Location(33.883333, 130.833333)),
        PortCode("JP", "TBU", "Tabu", null),
        PortCode("JP", "TCC", "Tokuchi", null),
        PortCode("JP", "TCH", "Tsuchiura", null),
        PortCode("JP", "TDA", "Tohda", null),
        PortCode("JP", "TDJ", "Takedatsu", null),
        PortCode("JP", "TDN", "Tadanoumi", null),
        PortCode("JP", "TDT", "Tairadate", null),
        PortCode("JP", "TEA", "Takena", null),
        PortCode("JP", "TEE", "Take", null),
        PortCode("JP", "TEI", "Tei", null),
        PortCode("JP", "TEK", "Tekutsuku", null),
        PortCode("JP", "TER", "Teuri", null),
        PortCode("JP", "TET", "Tateishi, Ehime", null),
        PortCode("JP", "TEU", "Teuchi", null),
        PortCode("JP", "TGC", "Toguchi", null),
        PortCode("JP", "TGO", "Tagonoura", null),
        PortCode("JP", "THM", "Tanohama", null),
        PortCode("JP", "THR", "Takehara", null),
        PortCode("JP", "THS", "Toyohashi", null),
        PortCode("JP", "TIA", "Taisha", null),
        PortCode("JP", "TIN", "Tainoura", null),
        PortCode("JP", "TIS", "Teishi", null),
        PortCode("JP", "TJI", "Takarajima", null),
        PortCode("JP", "TJJ", "Tomamae", null),
        PortCode("JP", "TJK", "Takashima/Masuda", null),
        PortCode("JP", "TJM", "Tojima", null),
        PortCode("JP", "TJO", "Toshima, Hyogo", null),
        PortCode("JP", "TJR", "Tajiri, Tottori", null),
        PortCode("JP", "TJS", "Tokashiki", null),
        PortCode("JP", "TKA", "Tokai", null),
        PortCode("JP", "TKC", "Takanokuchi", null),
        PortCode("JP", "TKD", "Takada", null),
        PortCode("JP", "TKE", "Takeno", null),
        PortCode("JP", "TKG", "Takasu, Kagoshima", null),
        PortCode("JP", "TKH", "Takahama/Amakusa", Location(32.366667, 130.0)),
        PortCode("JP", "TKI", "Taki", null),
        PortCode("JP", "TKJ", "Tokujin", null),
        PortCode("JP", "TKK", "Takaoka", null),
        PortCode("JP", "TKM", "Takuma", null),
        PortCode("JP", "TKO", "Tokonami", null),
        PortCode("JP", "TKR", "Tokoro", null),
        PortCode("JP", "TKS", "Tokushima", null),
        PortCode("JP", "TKT", "Taketoyo", null),
        PortCode("JP", "TKU", "Takuno", null),
        PortCode("JP", "TKW", "Tainokawa", null),
        PortCode("JP", "TKY", "Tokuyama", null),
        PortCode("JP", "TKZ", "Takezaki", null),
        PortCode("JP", "TMA", "Tomari/Shiribeshi", null),
        PortCode("JP", "TME", "Tomie", null),
        PortCode("JP", "TMI", "Tsukumi", null),
        PortCode("JP", "TMJ", "Takami", null),
        PortCode("JP", "TMK", "Tomakomai", null),
        PortCode("JP", "TMM", "Tomiku", null),
        PortCode("JP", "TMN", "Tamanoura", null),
        PortCode("JP", "TMO", "Tomioka, Kumamoto", null),
        PortCode("JP", "TMR", "Tomari, Okinawa", null),
        PortCode("JP", "TMS", "Tamatsu, Ehime", null),
        PortCode("JP", "TMT", "Tamatsu, Okayama", null),
        PortCode("JP", "TMU", "Tomitsu", null),
        PortCode("JP", "TMZ", "Tarumizu", null),
        PortCode("JP", "TNA", "Tsuna", null),
        PortCode("JP", "TNB", "Takanabe", null),
        PortCode("JP", "TND", "Tonda", null),
        PortCode("JP", "TNH", "Tonoshohigash", null),
        PortCode("JP", "TNI", "Tsuneishi", null),
        PortCode("JP", "TNK", "Tanasoko", null),
        PortCode("JP", "TNO", "Tonosho", null),
        PortCode("JP", "TNR", "Tanoura, Kumamoto", null),
        PortCode("JP", "TNS", "Tsunoshima", null),
        PortCode("JP", "TNU", "Tanoura/Kitakyushu", null),
        PortCode("JP", "TNW", "Tanowaki", null),
        PortCode("JP", "TNY", "Taniyama", Location(31.283333, 130.316667)),
        PortCode("JP", "TOA", "Toyo", Location(33.916667, 133.083333)),
        PortCode("JP", "TOB", "Toba", null),
        PortCode("JP", "TOC", "Togane", Location(35.566667, 140.366667)),
        PortCode("JP", "TOD", "Todohokke", null),
        PortCode("JP", "TOG", "Togi", null),
        PortCode("JP", "TOI", "Toi", null),
        PortCode("JP", "TOJ", "Toga", null),
        PortCode("JP", "TOK", "Tokachi", null),
        PortCode("JP", "TOM", "Tomioka, Tokushima", null),
        PortCode("JP", "TON", "Tonoura", null),
        PortCode("JP", "TOS", "Toyamashinko", null),
        PortCode("JP", "TOT", "Totoro", null),
        PortCode("JP", "TOU", "Touyo", null),
        PortCode("JP", "TOX", "Toshima/Tokyo", Location(34.516667, 139.266667)),
        PortCode("JP", "TOY", "Toyama", null),
        PortCode("JP", "TRC", "Tsuruuchi", null),
        PortCode("JP", "TRD", "Teradomari", null),
        PortCode("JP", "TRG", "Tsuruga", null),
        PortCode("JP", "TRH", "Tarugahama", null),
        PortCode("JP", "TRO", "Tororo", null),
        PortCode("JP", "TRR", "Tomariura", null),
        PortCode("JP", "TRU", "Tsurumi, Okayama", null),
        PortCode("JP", "TRZ", "Terazu/Yatsuka", null),
        PortCode("JP", "TSG", "Takasago", null),
        PortCode("JP", "TSH", "Tsushi", null),
        PortCode("JP", "TSI", "Teshima", null),
        PortCode("JP", "TSK", "Tsurusaki", null),
        PortCode("JP", "TSM", "Takashima/Nishisonogi", null),
        PortCode("JP", "TSO", "Teshio", null),
        PortCode("JP", "TSS", "Tasumi", null),
        PortCode("JP", "TST", "Tsutsu", null),
        PortCode("JP", "TSU", "Tsu", null),
        PortCode("JP", "TSX", "Takeshima", null),
        PortCode("JP", "TSZ", "Tosashimizu", null),
        PortCode("JP", "TTH", "Taketomihigashi", null),
        PortCode("JP", "TTJ", "Tottori", null),
        PortCode("JP", "TTK", "Tsuzuki Ku", Location(35.533333, 139.566667)),
        PortCode("JP", "TTM", "Tsutsumi", null),
        PortCode("JP", "TTS", "Tateishi, Kagawa", null),
        PortCode("JP", "TTU", "Tokitsu", null),
        PortCode("JP", "TTY", "Tateyama", null),
        PortCode("JP", "TUB", "Tsubame", Location(37.65, 138.933333)),
        PortCode("JP", "TUD", "Tsuda", null),
        PortCode("JP", "TUI", "Tsui", null),
        PortCode("JP", "TUR", "Tanoura, Ehime", null),
        PortCode("JP", "TUS", "Toyoshige", null),
        PortCode("JP", "TUU", "Tsukumo", null),
        PortCode("JP", "TUZ", "Tsuzu Yamaguchi", Location(34.05, 132.2)),
        PortCode("JP", "TWA", "Tsukinokawa", null),
        PortCode("JP", "TXD", "Tokuyamakudamatsu", Location(34.0, 131.766667)),
        PortCode("JP", "TXK", "Takasu, Fukui", null),
        PortCode("JP", "TXN", "Tokoname", null),
        PortCode("JP", "TYA", "Toyota", Location(35.083333, 137.166667)),
        PortCode("JP", "TYH", "Toyohama, Kagawa", null),
        PortCode("JP", "TYJ", "Toyohama, Aichi", null),
        PortCode("JP", "TYN", "Tsuiyama", null),
        PortCode("JP", "TYO", "Tokyo", Location(35.683333, 139.75)),
        PortCode("JP", "TYP", "Tsuyoshi", null),
        PortCode("JP", "TYR", "Toyoura", null),
        PortCode("JP", "TYU", "Tayui", null),
        PortCode("JP", "TZA", "Taiza", null),
        PortCode("JP", "TZU", "Terazu/Matsue", null),
        PortCode("JP", "UAO", "Urago", null),
        PortCode("JP", "UBJ", "Ube", null),
        PortCode("JP", "UBK", "Ushibuka", null),
        PortCode("JP", "UBY", "Ubuyu", null),
        PortCode("JP", "UCH", "Uchiumi", null),
        PortCode("JP", "UCN", "Uchinomi", null),
        PortCode("JP", "UCR", "Uchiura, Ishikawa", null),
        PortCode("JP", "UCU", "Uchiura, Fukui", null),
        PortCode("JP", "UDD", "Udo", null),
        PortCode("JP", "UDO", "Udono", null),
        PortCode("JP", "UEC", "Uechi", null),
        PortCode("JP", "UGA", "Uga", null),
        PortCode("JP", "UGU", "Ugusu", null),
        PortCode("JP", "UHH", "Uchihana", null),
        PortCode("JP", "UJI", "Ujina", null),
        PortCode("JP", "UJY", "Ujiyamada", null),
        PortCode("JP", "UKA", "Usuka", null),
        PortCode("JP", "UKB", "Kobe", Location(34.683333, 135.166667)),
        PortCode("JP", "UKI", "Ukui", null),
        PortCode("JP", "UKJ", "Ukejima", null),
        PortCode("JP", "UKN", "Uken", null),
        PortCode("JP", "UKT", "Ukitsu", null),
        PortCode("JP", "UMG", "Umagoe", null),
        PortCode("JP", "UNM", "Uranomae", null),
        PortCode("JP", "UNO", "Uno", null),
        PortCode("JP", "UNS", "Unoshima", null),
        PortCode("JP", "UNT", "Unten", null),
        PortCode("JP", "UNU", "Uchinourahetsuka", null),
        PortCode("JP", "UOM", "Uomi", null),
        PortCode("JP", "UOU", "Uozu, Shimane", null),
        PortCode("JP", "UOZ", "Uozu, Toyama", null),
        PortCode("JP", "URA", "Ura", null),
        PortCode("JP", "URG", "Uraga", null),
        PortCode("JP", "URH", "Urahara", null),
        PortCode("JP", "URK", "Urakawa", null),
        PortCode("JP", "URM", "Uragami", null),
        PortCode("JP", "URR", "Urashiro", null),
        PortCode("JP", "URS", "Urasoko", null),
        PortCode("JP", "URU", "Furumi", null),
        PortCode("JP", "USA", "Usa/Tosa", null),
        PortCode("JP", "USG", "Ushigakubijima", null),
        PortCode("JP", "USH", "Ushimado", null),
        PortCode("JP", "USI", "Ushine", null),
        PortCode("JP", "USJ", "Usujiri", null),
        PortCode("JP", "USK", "Usuki", null),
        PortCode("JP", "USN", "Usuno", null),
        PortCode("JP", "UST", "Ushitsu", null),
        PortCode("JP", "USU", "Usunoura", null),
        PortCode("JP", "UTM", "Utsumi, Aichi", null),
        PortCode("JP", "UTS", "Utsumi, Hiroshima", null),
        PortCode("JP", "UTZ", "Utazu", null),
        PortCode("JP", "UUN", "Unnan", Location(35.283333, 132.9)),
        PortCode("JP", "UUR", "Uchinoura", null),
        PortCode("JP", "UWA", "Uwajima", null),
        PortCode("JP", "UZK", "Uzuki", null),
        PortCode("JP", "WAD", "Wadomari", null),
        PortCode("JP", "WAI", "Waita", null),
        PortCode("JP", "WAK", "Wakayama", null),
        PortCode("JP", "WAM", "Wakamatsu/Kitakyushu", Location(33.883333, 130.816667)),
        PortCode("JP", "WAN", "Wan", null),
        PortCode("JP", "WAT", "Watanoha", null),
        PortCode("JP", "WDA", "Wada", null),
        PortCode("JP", "WJM", "Wajima", null),
        PortCode("JP", "WKI", "Wakimisaki", null),
        PortCode("JP", "WKJ", "Wakkanai", null),
        PortCode("JP", "WKR", "Wakura", null),
        PortCode("JP", "WKT", "Wakatsu", null),
        PortCode("JP", "WKW", "Wakinosawa", null),
        PortCode("JP", "WKZ", "Wakizaki", null),
        PortCode("JP", "WMT", "Wakimoto", null),
        PortCode("JP", "WNA", "Wano", null),
        PortCode("JP", "WNI", "Waniura", null),
        PortCode("JP", "WSB", "Washibeyanoura", null),
        PortCode("JP", "WTU", "Wakamatsu, Nagasaki", null),
        PortCode("JP", "XCA", "Niikappu", Location(42.366667, 142.316667)),
        PortCode("JP", "YAA", "Yanagi", null),
        PortCode("JP", "YAD", "Yamada, Iwate", null),
        PortCode("JP", "YAG", "Yagi, Hyogo", null),
        PortCode("JP", "YAM", "Yamagawa", null),
        PortCode("JP", "YAN", "Yanai", null),
        PortCode("JP", "YAS", "Yasumiya", null),
        PortCode("JP", "YAT", "Yatsushiro", null),
        PortCode("JP", "YBK", "Yobuko", null),
        PortCode("JP", "YBT", "Yubetsu", null),
        PortCode("JP", "YCH", "Yachiyo", Location(35.733333, 140.1)),
        PortCode("JP", "YDA", "Yoshida, Aichi", null),
        PortCode("JP", "YDM", "Yudomari", null),
        PortCode("JP", "YGE", "Yuge", null),
        PortCode("JP", "YGH", "Yamaguchihigashi", null),
        PortCode("JP", "YGI", "Yagi, Iwate", null),
        PortCode("JP", "YGR", "Yagishiri", null),
        PortCode("JP", "YHA", "Yoshiura/Yunotsu", null),
        PortCode("JP", "YHI", "Yoshiumi", Location(34.133333, 133.033333)),
        PortCode("JP", "YIC", "Yoichi", null),
        PortCode("JP", "YKK", "Yokkaichi", null),
        PortCode("JP", "YKS", "Yokoshima/Kurahashi", null),
        PortCode("JP", "YKT", "Yokota, Hiroshima", null),
        PortCode("JP", "YKU", "Yakuzu", null),
        PortCode("JP", "YMA", "Yasurahama", null),
        PortCode("JP", "YMC", "Yumachi", null),
        PortCode("JP", "YMD", "Yamada, Okayama", null),
        PortCode("JP", "YMG", "Yamaguchi", null),
        PortCode("JP", "YMN", "Yamanoura", null),
        PortCode("JP", "YMT", "Yamatani", null),
        PortCode("JP", "YMU", "Yumugi", null),
        PortCode("JP", "YNE", "Yaene", null),
        PortCode("JP", "YNI", "Yani", null),
        PortCode("JP", "YNM", "Yunomochiki", null),
        PortCode("JP", "YNN", "Yanma", null),
        PortCode("JP", "YNT", "Yunotsu", null),
        PortCode("JP", "YNZ", "Yonouzu", null),
        PortCode("JP", "YOC", "Yoichigaura", null),
        PortCode("JP", "YOG", "Yonegura", null),
        PortCode("JP", "YOK", "Yokohama", Location(35.45, 139.65)),
        PortCode("JP", "YOR", "Yoro", null),
        PortCode("JP", "YOS", "Yokosuka", Location(35.283333, 139.666667)),
        PortCode("JP", "YOT", "Yotsukura", null),
        PortCode("JP", "YOU", "Youra", null),
        PortCode("JP", "YQD", "Yamada", null),
        PortCode("JP", "YRA", "Yura, Hyogo", null),
        PortCode("JP", "YRG", "Yurigahama", null),
        PortCode("JP", "YRO", "Yoro", Location(35.3, 136.55)),
        PortCode("JP", "YSD", "Yoshida, Ehime", null),
        PortCode("JP", "YSG", "Yasugi", null),
        PortCode("JP", "YSH", "Yuasahiro", null),
        PortCode("JP", "YSM", "Yoshima", null),
        PortCode("JP", "YSN", "Yoshinozaki", null),
        PortCode("JP", "YSR", "Yoshiura/Misumi", null),
        PortCode("JP", "YSS", "Yoshiase", null),
        PortCode("JP", "YSU", "Yoshiura", null),
        PortCode("JP", "YSZ", "Yoshizu", null),
        PortCode("JP", "YTI", "Yutai", null),
        PortCode("JP", "YUA", "Yura, Yamaguchi", null),
        PortCode("JP", "YUJ", "Yura, Yamagata", null),
        PortCode("JP", "YUK", "Yuki", null),
        PortCode("JP", "YUR", "Yura, Wakayama", null),
        PortCode("JP", "YUS", "Yusu", null),
        PortCode("JP", "YUU", "Yuu", null),
        PortCode("JP", "YWH", "Yawatahama", null),
        PortCode("JP", "YWN", "Yuwan", null),
        PortCode("JP", "YWT", "Yawata/Kitakyushu", Location(33.85, 130.8)),
        PortCode("JP", "YYA", "Awano", null),
        PortCode("JP", "YZU", "Yaizu", null),
        PortCode("JP", "ZKA", "Iizuka", Location(33.65, 130.683333)),
        PortCode("JP", "ZMM", "Zamami", null)
    )
}
