package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.common.domain.model.geodata.Location
import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode

object PortsPH {
    val PORTS: List<PortCode> = listOf(
        PortCode("PH", "ABU", "Abulug", Location(18.433333, 121.45)),
        PortCode("PH", "ADL", "Adlay/Bislig", Location(9.4, 125.9)),
        PortCode("PH", "AHE", "Aheron/Ozamis", null),
        PortCode("PH", "AJU", "Ajuy", Location(11.166667, 123.033333)),
        PortCode("PH", "ALA", "Alasang/Siain", null),
        PortCode("PH", "ALB", "Albuera", Location(10.966667, 124.633333)),
        PortCode("PH", "ALC", "Alcoy", Location(9.683333, 123.5)),
        PortCode("PH", "ALE", "Aleran/Ozamis", null),
        PortCode("PH", "AMU", "Amunitan/Aparri", Location(18.316667, 122.05)),
        PortCode("PH", "ANA", "Anakan/Masao", null),
        PortCode("PH", "ANT", "Antipolo", null),
        PortCode("PH", "APR", "Aparri, Luzon", null),
        PortCode("PH", "AQE", "Hamtic", Location(10.7, 121.966667)),
        PortCode("PH", "ARA", "Aras Asan/Bislig", Location(8.883333, 126.3)),
        PortCode("PH", "AST", "Astorga", Location(6.883333, 125.45)),
        PortCode("PH", "ATI", "Atimonan/Siain", Location(13.983333, 121.9)),
        PortCode("PH", "AYG", "Ayungon", Location(9.85, 123.133333)),
        PortCode("PH", "BAB", "Babato/Dadiangas", null),
        PortCode("PH", "BAC", "Bacong", Location(9.233333, 123.3)),
        PortCode("PH", "BAG", "Baguio", null),
        PortCode("PH", "BAI", "Bais/Dumaguete", null),
        PortCode("PH", "BAL", "Balaboe", null),
        PortCode("PH", "BAS", "Basiauang/Dadiangas", null),
        PortCode("PH", "BAT", "Batonbaton", Location(9.183333, 118.35)),
        PortCode("PH", "BAU", "Bauan/Batangas", Location(13.8, 121.0)),
        PortCode("PH", "BCD", "Bacolod, Negros", null),
        PortCode("PH", "BCO", "Bacon/Legaspi", null),
        PortCode("PH", "BCT", "Isabela, Basilan", Location(6.7, 121.966667)),
        PortCode("PH", "BCU", "Baculin/Mati", null),
        PortCode("PH", "BGC", "Bagac", null),
        PortCode("PH", "BGI", "Bagui Bay/San Fernando", null),
        PortCode("PH", "BGR", "Bucar Grande/Suriagao", null),
        PortCode("PH", "BGS", "Balingasag", Location(8.75, 124.783333)),
        PortCode("PH", "BGV", "Borongan", null),
        PortCode("PH", "BIN", "Biñan", Location(14.333333, 121.083333)),
        PortCode("PH", "BIY", "Biyawa/Davao", null),
        PortCode("PH", "BLA", "Balanga/Batan", null),
        PortCode("PH", "BLC", "Balabac, Palawan", Location(7.966667, 117.05)),
        PortCode("PH", "BLG", "Balogo/Batangas", null),
        PortCode("PH", "BLN", "Balengan/Siain", null),
        PortCode("PH", "BLP", "Bolos Point/Aparri", null),
        PortCode("PH", "BLT", "Balintang/Puerto Princesa", null),
        PortCode("PH", "BLU", "Balumo/Zamboanga", null),
        PortCode("PH", "BNG", "Bauang", Location(16.516667, 120.316667)),
        PortCode("PH", "BNQ", "Baganga/Mati", null),
        PortCode("PH", "BNW", "Banawan/Dadiangas", null),
        PortCode("PH", "BOA", "Boac, Marinduque", Location(13.433333, 121.833333)),
        PortCode("PH", "BOG", "Bogo", Location(11.05, 124.0)),
        PortCode("PH", "BOR", "Boracay", Location(11.966667, 121.916667)),
        PortCode("PH", "BOS", "Boston/Davao", Location(7.866667, 126.35)),
        PortCode("PH", "BPH", "Bislig, Mindanao", null),
        PortCode("PH", "BQA", "Baler/Siain", null),
        PortCode("PH", "BRB", "Barobo/Bislig", Location(8.55, 126.116667)),
        PortCode("PH", "BRP", "Brookes Point, Palawan", Location(8.766667, 117.833333)),
        PortCode("PH", "BRT", "Barton/Puerto Princesa", null),
        PortCode("PH", "BSO", "Basco", Location(20.45, 121.966667)),
        PortCode("PH", "BSY", "Basey/Catbalogan", null),
        PortCode("PH", "BTG", "Batangas/Luzon", Location(13.75, 121.05)),
        PortCode("PH", "BTN", "Bataan, Mariveles", null),
        PortCode("PH", "BTS", "Batarasa/Puerto Princesa", null),
        PortCode("PH", "BTY", "Bantayon/San Jose", null),
        PortCode("PH", "BUD", "Budbud/Davao", null),
        PortCode("PH", "BUG", "Bugo", null),
        PortCode("PH", "BUL", "Bulan, Luzon", null),
        PortCode("PH", "BUR", "Burdeos, Polillo Isl", Location(14.833333, 121.966667)),
        PortCode("PH", "BXU", "Butuan Bay/Masao", null),
        PortCode("PH", "BYB", "Baybay/Tacloban", null),
        PortCode("PH", "BYP", "Bayang Point", null),
        PortCode("PH", "BYS", "Bayabas/Bislig", null),
        PortCode("PH", "BYW", "Bayawan/Dumaguete", null),
        PortCode("PH", "CAB", "Cabugao Bay/Legaspi", null),
        PortCode("PH", "CAJ", "Cajidiocan, Visayan Isl", Location(12.366667, 122.683333)),
        PortCode("PH", "CAM", "Camarines Norte/Jose Panganiban", null),
        PortCode("PH", "CAZ", "Cadiz", null),
        PortCode("PH", "CBO", "Cotabato, Mindanao", null),
        PortCode("PH", "CBY", "Calbayog, Samar", Location(12.066667, 124.6)),
        PortCode("PH", "CCG", "Calag-Calag/Dumaguete", null),
        PortCode("PH", "CDB", "Caldera Bay/Zamboanga", null),
        PortCode("PH", "CDN", "Cagdianao", Location(9.916667, 125.666667)),
        PortCode("PH", "CEB", "Cebu", null),
        PortCode("PH", "CGG", "Casiguran/Siain", null),
        PortCode("PH", "CGI", "Corregidor Island", Location(14.383333, 120.583333)),
        PortCode("PH", "CGM", "Camiguin Island/Aparri", null),
        PortCode("PH", "CGP", "Calug Point/Zamboanga", null),
        PortCode("PH", "CGT", "Calaguitan/Tacloban", null),
        PortCode("PH", "CGY", "Cagayan de Oro, Mindanao", null),
        PortCode("PH", "CLP", "Calapan/Batangas", null),
        PortCode("PH", "CLV", "Claveria/Aparri", null),
        PortCode("PH", "CML", "Camalagawan/Aparri", null),
        PortCode("PH", "CMO", "Currimao", null),
        PortCode("PH", "CNT", "Cantilan/Surigao", null),
        PortCode("PH", "CNY", "Canaybon/Catbalogan", null),
        PortCode("PH", "CPC", "Capoocan", Location(11.3, 124.65)),
        PortCode("PH", "CPL", "Capalonga/Siain", null),
        PortCode("PH", "CRA", "Carigara", Location(11.3, 124.683333)),
        PortCode("PH", "CRG", "Caraga/Mati", null),
        PortCode("PH", "CSB", "Casul Bay/Ozamis", null),
        PortCode("PH", "CSI", "Culasi", Location(11.6, 122.7)),
        PortCode("PH", "CST", "Castañas", Location(13.883333, 121.55)),
        PortCode("PH", "CTB", "Catamon Bay/Iloilo", null),
        PortCode("PH", "CTS", "Catbalogan, Samar", null),
        PortCode("PH", "CUG", "Calubian, Leyte", Location(11.433333, 124.416667)),
        PortCode("PH", "CUJ", "Culion", null),
        PortCode("PH", "CUN", "Catanauan", null),
        PortCode("PH", "CUR", "Curuan/Zamboanga", null),
        PortCode("PH", "CVE", "Cavite, Luzon", null),
        PortCode("PH", "CWY", "Calowayan/Catabalogan", null),
        PortCode("PH", "DCB", "Dahikan Bay", null),
        PortCode("PH", "DDW", "Dinadiawan/Aparri", null),
        PortCode("PH", "DGL", "Dingalan/Siain", null),
        PortCode("PH", "DGT", "Dumaguete", null),
        PortCode("PH", "DIC", "Diculum/Zamboanga", null),
        PortCode("PH", "DID", "Didadongan/Aparri", null),
        PortCode("PH", "DIO", "Diotorin/Siain", null),
        PortCode("PH", "DIR", "Dirgalan", null),
        PortCode("PH", "DIV", "Divilacan/Aparri", null),
        PortCode("PH", "DNG", "Dinagat Island/Surigao", null),
        PortCode("PH", "DNL", "Dinalongan/Siain", null),
        PortCode("PH", "DNO", "Danao", Location(10.533333, 124.033333)),
        PortCode("PH", "DPL", "Dipolog/Ozamis", null),
        PortCode("PH", "DPT", "Diapitan/Siain", null),
        PortCode("PH", "DRB", "Diaraboan/Siain", null),
        PortCode("PH", "DUL", "Dulag", null),
        PortCode("PH", "DVO", "Davao, Mindanao", null),
        PortCode("PH", "ENI", "El Nido/Puerto Princesa", Location(11.183333, 119.4)),
        PortCode("PH", "GAC", "Gachitorena/Jose Panganiban", null),
        PortCode("PH", "GAS", "Gasan", null),
        PortCode("PH", "GES", "General Santos", Location(6.116667, 125.15)),
        PortCode("PH", "GGG", "Gigaquit, Mindanao", Location(9.583333, 125.683333)),
        PortCode("PH", "GGM", "Gigmoto, Catanduanes", Location(13.766667, 124.383333)),
        PortCode("PH", "GHE", "Garcia Hernandez", Location(9.616667, 124.3)),
        PortCode("PH", "GHG", "Guihulngan", Location(10.116667, 123.283333)),
        PortCode("PH", "GIN", "Gingoog/Masao", null),
        PortCode("PH", "GMS", "Guimaras/Iloilo", null),
        PortCode("PH", "GNI", "General Island/Bislig", null),
        PortCode("PH", "GUN", "Guiuan", Location(11.033333, 125.716667)),
        PortCode("PH", "HIJ", "Hijo Wharf/Davao", null),
        PortCode("PH", "HIL", "Hilongos", Location(10.366667, 124.75)),
        PortCode("PH", "HIM", "Himamaylan, Negros", Location(10.083333, 122.866667)),
        PortCode("PH", "HMH", "Homonhon", Location(10.75, 125.7)),
        PortCode("PH", "HNB", "Hinobaan/Iloilo", null),
        PortCode("PH", "HNG", "Hinigaran/Iloilo", null),
        PortCode("PH", "HNT", "Hinatuan/Bislig", null),
        PortCode("PH", "HON", "Hondagua/Siain", null),
        PortCode("PH", "HOO", "Hook Bay/Siain", null),
        PortCode("PH", "HYB", "Hagnava Bay", null),
        PortCode("PH", "IGN", "Iligan, Mindanao", null),
        PortCode("PH", "ILO", "Iloilo, Panay", null),
        PortCode("PH", "INP", "Inampulugan Island", null),
        PortCode("PH", "IPE", "Ipil/Zamboanga", null),
        PortCode("PH", "IRN", "Port Irene", Location(18.366667, 122.1)),
        PortCode("PH", "ISL", "Isabel", null),
        PortCode("PH", "JAG", "Jagna", null),
        PortCode("PH", "JAS", "Jasaan", Location(8.65, 124.75)),
        PortCode("PH", "JNZ", "Jimenez/Ozamis", null),
        PortCode("PH", "JOL", "Jolo", null),
        PortCode("PH", "JPM", "Jose Panganiban, Luzon", null),
        PortCode("PH", "KAR", "Karomatan/Iligan", null),
        PortCode("PH", "KAS", "Kabasalan/Zamboanga", Location(7.783333, 122.75)),
        PortCode("PH", "KAT", "Katipunan/Ozamis", null),
        PortCode("PH", "KIA", "Kiamba/Dadiangas", null),
        PortCode("PH", "KIL", "Kilbay Point/Jose Panganiban", null),
        PortCode("PH", "KIN", "Kinogitan/Iligan", null),
        PortCode("PH", "KIP", "Kipit/Ozamis", null),
        PortCode("PH", "KIW", "Kiwalan/Iligan", null),
        PortCode("PH", "KLM", "Kalamansig", Location(6.55, 124.05)),
        PortCode("PH", "KOL", "Kolambugan/Iligan", null),
        PortCode("PH", "KUM", "Kumalarang/Zamboanga", null),
        PortCode("PH", "LAB", "Labason/Zamboanga", Location(8.066667, 122.516667)),
        PortCode("PH", "LAC", "La Carlota", Location(10.416667, 122.916667)),
        PortCode("PH", "LAG", "Lagonoy/Jose Panganiban", null),
        PortCode("PH", "LAM", "Lamit Bay/Jose Panganiban", null),
        PortCode("PH", "LAN", "Lanuza/Bislig", null),
        PortCode("PH", "LAO", "Laoag, Luzon", Location(18.183333, 120.583333)),
        PortCode("PH", "LAY", "Lagondy River", null),
        PortCode("PH", "LBK", "Lebak", Location(6.633333, 124.066667)),
        PortCode("PH", "LEY", "Leyte", Location(11.366667, 124.483333)),
        PortCode("PH", "LGG", "Lingig/Bislig", Location(8.033333, 126.4)),
        PortCode("PH", "LGP", "Legaspi Apt, Luzon", Location(13.133333, 123.75)),
        PortCode("PH", "LGU", "Laguna", Location(10.3, 123.883333)),
        PortCode("PH", "LIA", "Lianga/Bislig", null),
        PortCode("PH", "LIB", "Libjo/Surigao", null),
        PortCode("PH", "LIM", "Limay/Bataan", null),
        PortCode("PH", "LIN", "Lingayen, Luzon", null),
        PortCode("PH", "LNA", "Larena", Location(9.25, 123.583333)),
        PortCode("PH", "LNK", "Linik/Dadiangas", null),
        PortCode("PH", "LNO", "Lunao", Location(8.866667, 125.05)),
        PortCode("PH", "LOM", "Lomuyon/Dadiangas", null),
        PortCode("PH", "LOO", "Looc Bay/San Jose", null),
        PortCode("PH", "LOP", "Long Point/Puerto Princesa", null),
        PortCode("PH", "LPA", "Lipa", null),
        PortCode("PH", "LPU", "Lapu-Lapu, Cebu", Location(10.316667, 123.95)),
        PortCode("PH", "LPZ", "La Paz/Iloilo", null),
        PortCode("PH", "LRP", "La Rap/Jose Panganiban", null),
        PortCode("PH", "LUC", "Lucanin", Location(14.466667, 120.616667)),
        PortCode("PH", "LUG", "Lugait", Location(8.333333, 124.25)),
        PortCode("PH", "LUM", "Lumasal/Dadiangas", null),
        PortCode("PH", "LZB", "Lazi", Location(9.116667, 123.633333)),
        PortCode("PH", "MAB", "Mabini, Mindanao", Location(8.95, 124.783333)),
        PortCode("PH", "MAC", "Matho Cortez/Bislig", null),
        PortCode("PH", "MAD", "Madaum/Davao", null),
        PortCode("PH", "MAI", "Maitum/Dadiangas", null),
        PortCode("PH", "MAK", "Makar/Dadiangas", null),
        PortCode("PH", "MAS", "Masao", null),
        PortCode("PH", "MBT", "Masbate", null),
        PortCode("PH", "MCD", "Mercedes/Jose Panganiban", null),
        PortCode("PH", "MCJ", "Macojalan/Ozamis", null),
        PortCode("PH", "MCO", "Maco/Davao", null),
        PortCode("PH", "MDN", "Medina", Location(8.916667, 125.016667)),
        PortCode("PH", "MGA", "Magalona/Iloilo", null),
        PortCode("PH", "MGB", "Magueda Bay/Catbalogan", null),
        PortCode("PH", "MGD", "Mabaguid", null),
        PortCode("PH", "MGG", "Mangogoy/Bislig", null),
        PortCode("PH", "MGI", "Mambagid", null),
        PortCode("PH", "MHT", "Marihatag, Mindanao", Location(8.783333, 126.283333)),
        PortCode("PH", "MIC", "Misamis Or./Cagayan de Oro", null),
        PortCode("PH", "MIL", "Milbuk/Dadiangas", null),
        PortCode("PH", "MIO", "Misamis Occ./Ozamis", null),
        PortCode("PH", "MKC", "Makati City", Location(14.55, 121.033333)),
        PortCode("PH", "MLB", "Maluso, Basilan", Location(6.533333, 121.866667)),
        PortCode("PH", "MLL", "Malalag/Davao", null),
        PortCode("PH", "MLS", "Magellanes/Masao", null),
        PortCode("PH", "MNI", "Manicani", Location(11.0, 125.65)),
        PortCode("PH", "MNL", "Manila", null),
        PortCode("PH", "MNN", "Manila North Harbour", null),
        PortCode("PH", "MNS", "Manila South Harbour", null),
        PortCode("PH", "MNT", "Muntinlupa City", Location(14.616667, 121.05)),
        PortCode("PH", "MNY", "Manay/Mati", null),
        PortCode("PH", "MON", "Monserrat/Mati", null),
        PortCode("PH", "MOR", "Morong/Mariveles", null),
        PortCode("PH", "MSB", "Malasugat Bay/Zamboanga", null),
        PortCode("PH", "MSC", "Masinloc/Sual", null),
        PortCode("PH", "MSS", "Mission/Aparri", null),
        PortCode("PH", "MSY", "Manansalay/Batangas", null),
        PortCode("PH", "MTA", "Matina Aplaya/Davao", null),
        PortCode("PH", "MTI", "Makati", Location(16.416667, 121.1)),
        PortCode("PH", "MTP", "Malatapay", Location(9.55, 123.15)),
        PortCode("PH", "MUL", "Mulanay/Siain", null),
        PortCode("PH", "MVS", "Mariveles, Luzon", null),
        PortCode("PH", "MXI", "Mati, Mindanao", null),
        PortCode("PH", "NAB", "Nabulao Bay/Iloilo", null),
        PortCode("PH", "NAL", "Nalungga/Iloilo", null),
        PortCode("PH", "NAP", "Napsan/Puerto Princesa", null),
        PortCode("PH", "NAR", "Naris Point/Puerto Princesa", null),
        PortCode("PH", "NAS", "Nasipit/Masao", null),
        PortCode("PH", "NGH", "Nagh", null),
        PortCode("PH", "NID", "Nido Terminal", null),
        PortCode("PH", "NON", "Nonoc/Surigao Del Norte", null),
        PortCode("PH", "NOP", "Mactan Island Apt", Location(10.3, 124.0)),
        PortCode("PH", "NTO", "Nato", null),
        PortCode("PH", "NUG", "Nasugbu, Luzon", Location(14.066667, 120.633333)),
        PortCode("PH", "ODI", "Odiongan", Location(12.4, 121.983333)),
        PortCode("PH", "OLO", "Olongapo", null),
        PortCode("PH", "OPO", "Opol", Location(8.516667, 124.566667)),
        PortCode("PH", "ORA", "Orayuita", null),
        PortCode("PH", "ORC", "Ormoc/Tacloban", null),
        PortCode("PH", "ORL", "Oroquieta", Location(8.483333, 123.8)),
        PortCode("PH", "ORS", "Oras", Location(12.15, 125.433333)),
        PortCode("PH", "OTE", "Oteiza/Bislig", null),
        PortCode("PH", "OZC", "Ozamis, Mindanao", null),
        PortCode("PH", "PAG", "Pagadian/Zamboanga", null),
        PortCode("PH", "PAM", "Pampanga", null),
        PortCode("PH", "PAN", "Panabo", Location(7.3, 125.683333)),
        PortCode("PH", "PAS", "Pasay, Luzon", null),
        PortCode("PH", "PBA", "Port Barton/Palawan", null),
        PortCode("PH", "PCA", "Panacosa/Puerto Princesa", null),
        PortCode("PH", "PCN", "Panacan/Davao", null),
        PortCode("PH", "PDC", "Polanco, Mindanao", Location(8.516667, 123.35)),
        PortCode("PH", "PDR", "Pacio de Rozas/Batangas", null),
        PortCode("PH", "PGA", "Puerto Galera", Location(13.5, 120.933333)),
        PortCode("PH", "PGB", "Pagbilao", Location(13.966667, 121.683333)),
        PortCode("PH", "PGT", "Pangutaran/Jolo", null),
        PortCode("PH", "PHD", "Port Holland", null),
        PortCode("PH", "PIN", "Pinamalayan/Batangas", null),
        PortCode("PH", "PIS", "Philippines", Location(14.583333, 121.0)),
        PortCode("PH", "PLA", "Plaridel/Ozamis", null),
        PortCode("PH", "PLB", "Palamit Bay/San Jose", null),
        PortCode("PH", "PLC", "Polloc", null),
        PortCode("PH", "PLL", "Polillo, Polillo Isl", Location(14.7, 121.933333)),
        PortCode("PH", "PLP", "Palapag/San Jose", null),
        PortCode("PH", "PLW", "Palawan/Ozamis", null),
        PortCode("PH", "PMT", "Pamintayan/Zamboanga", null),
        PortCode("PH", "PNB", "Panabutan/Zamboanga", null),
        PortCode("PH", "PNN", "Paninirongan/Sanjose", null),
        PortCode("PH", "PNT", "Punti/Aparri", null),
        PortCode("PH", "PPL", "Pamplona/Aparri", null),
        PortCode("PH", "PPP", "Pagudpud, Luzon", Location(16.616667, 120.316667)),
        PortCode("PH", "PPS", "Puerto Princesa, Palawan", null),
        PortCode("PH", "PRA", "Parang", Location(7.366667, 124.266667)),
        PortCode("PH", "PRO", "Poro/San Fernando", null),
        PortCode("PH", "PSL", "Pasaleng, Luzon", Location(18.55, 120.916667)),
        PortCode("PH", "PTL", "Puntalinao/Mati", null),
        PortCode("PH", "PUG", "Pugad/Bislig", null),
        PortCode("PH", "PUL", "Pulupandan", null),
        PortCode("PH", "QBI", "Quinabigan", null),
        PortCode("PH", "QBL", "Quinablagan/Mati", null),
        PortCode("PH", "QPT", "Quipit Bay/Ozamis", null),
        PortCode("PH", "QUE", "Queson/Siain", null),
        PortCode("PH", "QUI", "Quiddiao/Aparri", null),
        PortCode("PH", "REA", "Real/Siain", null),
        PortCode("PH", "RLN", "Romblon", null),
        PortCode("PH", "ROM", "Romblon", Location(12.566667, 122.266667)),
        PortCode("PH", "RXS", "Roxas/Puerto Princesa", null),
        PortCode("PH", "SAG", "Sagay/Iloilo", null),
        PortCode("PH", "SAN", "Santa Ana/Aparri", null),
        PortCode("PH", "SAS", "Sasa/Davao", null),
        PortCode("PH", "SAY", "Sayao/Batangas", null),
        PortCode("PH", "SBB", "Sabbot/Siain", null),
        PortCode("PH", "SBG", "Sabang", Location(10.183333, 118.9)),
        PortCode("PH", "SBI", "Subic", Location(14.9, 120.233333)),
        PortCode("PH", "SBY", "Sablayan/Batangas", null),
        PortCode("PH", "SCA", "San Carlos/Dumaguete", null),
        PortCode("PH", "SCR", "Santa Cruz/Sual", null),
        PortCode("PH", "SCT", "Santa Catalina/Dumaguete", null),
        PortCode("PH", "SDG", "Sindangan/Ozamis", null),
        PortCode("PH", "SFE", "San Fernando, Luzon", null),
        PortCode("PH", "SFS", "Subic Bay", null),
        PortCode("PH", "SGD", "Sogod/Tacloban", null),
        PortCode("PH", "SIG", "Sigayan/Sultan Naga Dimaporo", Location(7.733333, 123.766667)),
        PortCode("PH", "SIN", "Siain, Luzon", null),
        PortCode("PH", "SIO", "San Ignacio/Mati", null),
        PortCode("PH", "SIR", "Siari/Ozamis", null),
        PortCode("PH", "SIS", "San Isidro/Sanjose", null),
        PortCode("PH", "SIY", "Siay/Zamboanga", null),
        PortCode("PH", "SJI", "San Jose Apt, Mindoro", Location(12.35, 121.083333)),
        PortCode("PH", "SKU", "Sultan Kudarat/Dadiangas", null),
        PortCode("PH", "SLM", "Salomague", Location(17.783333, 120.416667)),
        PortCode("PH", "SLU", "Santa Lucia/Puerto Princesa", null),
        PortCode("PH", "SMA", "Santa Maria/Zamboanga", null),
        PortCode("PH", "SMR", "Semirara", Location(12.066667, 121.4)),
        PortCode("PH", "SNG", "Sangi/Cebu", null),
        PortCode("PH", "SNI", "Santa Nino", null),
        PortCode("PH", "SOR", "Sorsogon/Legaspi", null),
        PortCode("PH", "SPQ", "San Pio Quinto/Aparri", null),
        PortCode("PH", "STE", "San Teodoro/Batangas", null),
        PortCode("PH", "SUA", "Sual", null),
        PortCode("PH", "SUG", "Surigao, Mindanao", null),
        PortCode("PH", "TAC", "Tacloban, Leyte", null),
        PortCode("PH", "TAG", "Tagbilaran, Bohol", null),
        PortCode("PH", "TAL", "Talibon", Location(10.133333, 124.316667)),
        PortCode("PH", "TAN", "Tandayag", Location(9.45, 123.216667)),
        PortCode("PH", "TAY", "Taytay/Puerto Princesa", null),
        PortCode("PH", "TBC", "Tabaco/Legaspi", Location(13.35, 123.733333)),
        PortCode("PH", "TBG", "Tabangoa", null),
        PortCode("PH", "TBU", "Tagabuli/Davao", null),
        PortCode("PH", "TDC", "Tandoc", null),
        PortCode("PH", "TDG", "Tandag/Bislig", null),
        PortCode("PH", "TGD", "Tagudin/San Fernando", null),
        PortCode("PH", "TGI", "Tuguis/Dadiangas", null),
        PortCode("PH", "TGL", "Taguilon/Ozamis", null),
        PortCode("PH", "TGN", "Tambungon/Davao", null),
        PortCode("PH", "TGO", "Tagoloan", Location(8.533333, 124.75)),
        PortCode("PH", "TGT", "Taguite Bay/Zamboanga", null),
        PortCode("PH", "TGW", "Tungawan Bay/Zamboanga", null),
        PortCode("PH", "TIB", "Tibungco/Davao", null),
        PortCode("PH", "TIN", "Tindalo Oil Field", Location(11.066667, 118.9)),
        PortCode("PH", "TKW", "Tagkawayan/Siain", null),
        PortCode("PH", "TLD", "Toledo/Cebu", null),
        PortCode("PH", "TLG", "Tolong/Dumaguete", null),
        PortCode("PH", "TLM", "Talomo/Davao", null),
        PortCode("PH", "TLP", "Tolopo", null),
        PortCode("PH", "TLS", "Tolosa/Tacloban", null),
        PortCode("PH", "TNU", "Tanauan/Tacloban", null),
        PortCode("PH", "TOB", "Toboso/Dumaguete", null),
        PortCode("PH", "TON", "Tubigon", Location(9.95, 123.966667)),
        PortCode("PH", "TTO", "Taganito", Location(9.55, 125.816667)),
        PortCode("PH", "ULY", "Ulugan Bay", null),
        PortCode("PH", "URR", "Umrur", null),
        PortCode("PH", "VCS", "Victorias, Negros", null),
        PortCode("PH", "VNV", "Villanueva", null),
        PortCode("PH", "VTL", "Vitali/Zamboanga", Location(7.366667, 122.283333)),
        PortCode("PH", "VTO", "Vito/Iloilo", null),
        PortCode("PH", "WAS", "Wasag/Dadiangas", null),
        PortCode("PH", "WAW", "Wawa/Batangas", null),
        PortCode("PH", "WNP", "Naga/Zamboanga", Location(7.8, 122.7)),
        PortCode("PH", "XSO", "Siocon/Zamboanga", null),
        PortCode("PH", "ZAM", "Zamboanga", null)
    )
}
