package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.common.domain.model.geodata.Location
import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode

object PortsIE {
    val PORTS: List<PortCode> = listOf(
        PortCode("IE", "ALQ", "Alexandra Quay", null),
        PortCode("IE", "ARD", "Ardmore", Location(51.95, -7.716667)),
        PortCode("IE", "ARH", "Arklow Head (Ie009)", null),
        PortCode("IE", "ARK", "Arklow", null),
        PortCode("IE", "ARO", "Alexandra Road Oil", null),
        PortCode("IE", "ATN", "Annacotty", Location(52.4, -8.3)),
        PortCode("IE", "AUG", "Aughinish Island", null),
        PortCode("IE", "BBG", "Balbriggan", Location(53.616667, -6.183333)),
        PortCode("IE", "BGY", "Ballynacargy", Location(53.566667, -7.533333)),
        PortCode("IE", "BHT", "Blanchardstown", Location(53.383333, -6.366667)),
        PortCode("IE", "BIF", "B & I Ferryport", null),
        PortCode("IE", "BIT", "B & I Terminal", null),
        PortCode("IE", "BLL", "Ballina", Location(54.116667, -9.166667)),
        PortCode("IE", "BNA", "Ballina", Location(52.8, -8.433333)),
        PortCode("IE", "BNG", "Bangor", Location(54.133333, -9.733333)),
        PortCode("IE", "BTH", "Bantry Harbour", Location(51.683333, -9.45)),
        PortCode("IE", "BTM", "Baltimore", null),
        PortCode("IE", "BUC", "Buncrana", null),
        PortCode("IE", "BUR", "Burtonport", Location(54.983333, -8.433333)),
        PortCode("IE", "BVD", "Ballydavid", Location(52.216667, -10.35)),
        PortCode("IE", "BYT", "Bantry", Location(51.683333, -9.45)),
        PortCode("IE", "CAR", "Carlingford", null),
        PortCode("IE", "CCT", "Coastal Control Terminal", null),
        PortCode("IE", "CFI", "Castlefinn", Location(54.8, -7.6)),
        PortCode("IE", "CFN", "Donegal", null),
        PortCode("IE", "CHE", "Cahirciveen", Location(51.95, -10.216667)),
        PortCode("IE", "CLC", "Clarecastle", Location(52.816667, -8.95)),
        PortCode("IE", "CLD", "Clare Island", Location(53.8, -9.95)),
        PortCode("IE", "CLG", "Clogherhead", Location(53.783333, -6.233333)),
        PortCode("IE", "CLI", "Clifden", null),
        PortCode("IE", "COB", "Cobh", null),
        PortCode("IE", "CRO", "Crookhaven", null),
        PortCode("IE", "CRS", "Carrick-on-Suir", Location(52.333333, -7.4)),
        PortCode("IE", "CTB", "Castletown Bearhaven", Location(51.65, -9.916667)),
        PortCode("IE", "DCN", "Duncannon/Saint Helens", Location(52.216667, -6.983333)),
        PortCode("IE", "DDK", "Dundalk", null),
        PortCode("IE", "DFA", "Dublin-Ferryport Terminal 1", Location(53.316667, -6.183333)),
        PortCode("IE", "DFB", "Dublin-Ferryport Terminal 2", Location(53.316667, -6.2)),
        PortCode("IE", "DFC", "Dublin-Ferryport Terminal 3", Location(53.316667, -6.233333)),
        PortCode("IE", "DFT", "Dublin-Dublin Ferryport Terminals", Location(53.316667, -6.233333)),
        PortCode("IE", "DFY", "Dunfanaghy", Location(55.183333, -7.966667)),
        PortCode("IE", "DGV", "Dungarvan", Location(52.583333, -7.083333)),
        PortCode("IE", "DIN", "Dingle", null),
        PortCode("IE", "DLG", "Dun Laoghaire", Location(53.3, -6.133333)),
        PortCode("IE", "DMF", "Drogheda Maxol Facility", Location(53.716667, -6.333333)),
        PortCode("IE", "DNM", "Dunmore East", null),
        PortCode("IE", "DPP", "Drogheda Premiere Periclase", Location(53.716667, -62.516667)),
        PortCode("IE", "DRO", "Drogheda", null),
        PortCode("IE", "DUB", "Dublin", null),
        PortCode("IE", "DWE", "Ennistymon", Location(52.933333, -9.283333)),
        PortCode("IE", "EBF", "Broadford", null),
        PortCode("IE", "EKY", "Easkey/Rathlee", Location(54.283333, -8.966667)),
        PortCode("IE", "ESB", "ESB Poolbeg-Dublin", Location(53.333333, -6.183333)),
        PortCode("IE", "FCW", "Frank Cassin Wharf", null),
        PortCode("IE", "FEN", "Fenit", Location(52.266667, -9.866667)),
        PortCode("IE", "FGY", "Coolock", Location(53.383333, -6.183333)),
        PortCode("IE", "FID", "Fiddown", null),
        PortCode("IE", "FIN", "Fintona", Location(54.5, -7.316667)),
        PortCode("IE", "FOV", "Foynes", null),
        PortCode("IE", "FPD", "Flogas Products Drogheda", Location(53.716667, -6.35)),
        PortCode("IE", "FRW", "Ford's Wharf (Topaz Energy Terminal)", Location(51.883333, -8.433333)),
        PortCode("IE", "FTD", "Fethard/Slade", Location(52.2, -6.833333)),
        PortCode("IE", "GGA", "Glengarriff", Location(51.75, -9.55)),
        PortCode("IE", "GOW", "Gowran", Location(57.616667, -7.4)),
        PortCode("IE", "GRE", "Greencastle", Location(55.2, -6.983333)),
        PortCode("IE", "GRN", "Greenore", null),
        PortCode("IE", "GRT", "Gortahork", Location(55.116667, -8.133333)),
        PortCode("IE", "GWY", "Galway", null),
        PortCode("IE", "HAU", "Haulbowline", null),
        PortCode("IE", "HOW", "Howth", null),
        PortCode("IE", "KBS", "Killybegs", null),
        PortCode("IE", "KIC", "Kilcoole", null),
        PortCode("IE", "KIN", "Kilronan", Location(53.116667, -9.666667)),
        PortCode("IE", "KKA", "Kilmokea", null),
        PortCode("IE", "KLA", "Killala", null),
        PortCode("IE", "KLN", "Kinsale", null),
        PortCode("IE", "KLR", "Kilrush", null),
        PortCode("IE", "KNG", "Kinnegad", null),
        PortCode("IE", "LAR", "Lurganm Armagh", null),
        PortCode("IE", "LMK", "Limerick", null),
        PortCode("IE", "MAG", "Maghera", null),
        PortCode("IE", "MAP", "Marino Point", null),
        PortCode("IE", "MAR", "Marshmeadows/New Ross", Location(52.383333, -6.95)),
        PortCode("IE", "MOT", "Moneypoint", null),
        PortCode("IE", "MOV", "Moville", Location(55.183333, -7.033333)),
        PortCode("IE", "MRT", "Magheraroarty", Location(55.133333, -8.166667)),
        PortCode("IE", "MTL", "Dublin-Marine Terminal", Location(53.333333, -6.233333)),
        PortCode("IE", "NAY", "Newtonabbey", Location(54.65, -5.933333)),
        PortCode("IE", "NET", "Newport", Location(53.883333, -9.533333)),
        PortCode("IE", "NEX", "Newtown", null),
        PortCode("IE", "NRR", "New Ross-Raheen/Roberscon", Location(52.383333, -6.95)),
        PortCode("IE", "NRS", "New Ross", Location(52.383333, -6.933333)),
        PortCode("IE", "ORK", "Cork", null),
        PortCode("IE", "PAP", "Parnell Place", null),
        PortCode("IE", "PAT", "Pandoro Terminal", null),
        PortCode("IE", "PAW", "Passage West", Location(51.866667, -8.35)),
        PortCode("IE", "RAT", "Rathmullan", Location(55.1, -7.533333)),
        PortCode("IE", "RAV", "Rossaveel", null),
        PortCode("IE", "RDM", "Rathdrum", Location(52.916667, -6.233333)),
        PortCode("IE", "RDT", "Ringaskiddy Deepwater Terminal", Location(51.833333, -8.316667)),
        PortCode("IE", "RIN", "Ringaskiddy", Location(51.833333, -8.316667)),
        PortCode("IE", "ROE", "Rosslare", null),
        PortCode("IE", "ROS", "Rosslare Harbour", null),
        PortCode("IE", "RPT", "Ringaskiddy Passenger Terminal", Location(51.833333, -8.316667)),
        PortCode("IE", "RRR", "Kildorrery", Location(52.233333, -8.416667)),
        PortCode("IE", "RSM", "Rossaveel", Location(53.266667, -9.55)),
        PortCode("IE", "RTN", "Ramelton", Location(55.033333, -7.633333)),
        PortCode("IE", "RUS", "Rushbrooke", Location(51.85, -8.316667)),
        PortCode("IE", "RVM", "River Moy", null),
        PortCode("IE", "SKL", "Skull", Location(51.516667, -9.533333)),
        PortCode("IE", "SLI", "Sligo", null),
        PortCode("IE", "SNN", "Shannon", Location(52.7, -8.85)),
        PortCode("IE", "SNR", "Stokestown/New Ross", Location(52.35, -6.983333)),
        PortCode("IE", "TAR", "Tarbert", null),
        PortCode("IE", "TIV", "Tivoli", null),
        PortCode("IE", "TLK", "Castlenock", null),
        PortCode("IE", "TME", "Tramore", null),
        PortCode("IE", "TOB", "Tober", Location(53.366667, -7.65)),
        PortCode("IE", "TQY", "Town Quays/Drogheda", Location(53.716667, -6.333333)),
        PortCode("IE", "TRA", "Tralee", null),
        PortCode("IE", "TRP", "Tom Roes Point Terminal/Drogheda", Location(53.716667, -6.3)),
        PortCode("IE", "UHL", "Unionhall", Location(51.55, -9.15)),
        PortCode("IE", "WAT", "Waterford", Location(52.25, -7.1)),
        PortCode("IE", "WCQ", "Waterford City Quays", Location(52.25, -7.1)),
        PortCode("IE", "WES", "Westport", null),
        PortCode("IE", "WEX", "Wexford", null),
        PortCode("IE", "WGI", "Waterford Great Island (ESB)", Location(52.266667, -6.983333)),
        PortCode("IE", "WHI", "Whitegate", null),
        PortCode("IE", "WIC", "Wicklow", null),
        PortCode("IE", "WIL", "Wilton", null),
        PortCode("IE", "YOU", "Youghal", null)
    )
}
