package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode
import de.visualdigits.common.domain.model.geodata.Location
                 
object PortsPG {
    val PORTS: List<PortCode> = listOf(
        PortCode("PG", "ABW", "Abau", null),
        PortCode("PG", "AHO", "Ahioma", null),
        PortCode("PG", "AIA", "Aiambak", Location(-7.35, 141.266667)),
        PortCode("PG", "AKI", "Akinum", null),
        PortCode("PG", "ALC", "Alcester Island", Location(-9.566667, 152.45)),
        PortCode("PG", "AMI", "Amio", Location(-6.116667, 150.75)),
        PortCode("PG", "ANB", "Anewa Bay", Location(-6.2, 155.55)),
        PortCode("PG", "ATN", "Namatanai", null),
        PortCode("PG", "BNA", "Buna", null),
        PortCode("PG", "BOI", "Boigu Island", Location(-9.266667, 142.216667)),
        PortCode("PG", "BOR", "Boroko", null),
        PortCode("PG", "BUA", "Buka", null),
        PortCode("PG", "CAU", "Caution Bay", Location(-9.333333, 146.933333)),
        PortCode("PG", "CFG", "Conflict Group", Location(-10.783333, 151.8)),
        PortCode("PG", "DAU", "Daru", null),
        PortCode("PG", "DBL", "Deboyne Lagoon", Location(-10.783333, 152.4)),
        PortCode("PG", "FIN", "Finschhafen", null),
        PortCode("PG", "FUB", "Fulleborn", null),
        PortCode("PG", "GAW", "Gawa Island", Location(-8.966667, 151.983333)),
        PortCode("PG", "GEI", "Green Islands", null),
        PortCode("PG", "GIL", "Gilau", null),
        PortCode("PG", "GMI", "Gasmata Island", null),
        PortCode("PG", "GUR", "Alotau", null),
        PortCode("PG", "HKN", "Hoskins", null),
        PortCode("PG", "KAI", "Kaibola", Location(-8.416667, 151.1)),
        PortCode("PG", "KIE", "Kieta", null),
        PortCode("PG", "KIM", "Kimbe", null),
        PortCode("PG", "KLO", "Kalo", null),
        PortCode("PG", "KMA", "Kerema", null),
        PortCode("PG", "KOP", "Kopi", Location(-7.3, 144.183333)),
        PortCode("PG", "KPP", "Kakapo", null),
        PortCode("PG", "KRK", "Kairuku", Location(-8.833333, 146.533333)),
        PortCode("PG", "KRX", "Karkar Is", Location(-4.633333, 145.966667)),
        PortCode("PG", "KUL", "Kumul", Location(-8.1, 144.566667)),
        PortCode("PG", "KVG", "Kavieng", null),
        PortCode("PG", "LAE", "Lae", null),
        PortCode("PG", "LAK", "Lakuramau", Location(-2.883333, 151.25)),
        PortCode("PG", "LAM", "Lambom Island", Location(-4.8, 152.833333)),
        PortCode("PG", "LDT", "Londolovit", Location(-3.066667, 152.616667)),
        PortCode("PG", "LLA", "Laughlan Atoll", Location(-9.283333, 153.666667)),
        PortCode("PG", "LNV", "Lihir Island", null),
        PortCode("PG", "LOL", "Loloho", null),
        PortCode("PG", "LOM", "Lombrum", Location(-2.033333, 147.366667)),
        PortCode("PG", "LOR", "Lorengau, Manus Island", null),
        PortCode("PG", "MAG", "Madang", Location(-5.216667, 145.783333)),
        PortCode("PG", "MAM", "Manam Island", null),
        PortCode("PG", "MIE", "Mielelek", null),
        PortCode("PG", "MIS", "Misima Island", null),
        PortCode("PG", "MTK", "Motukea Island", Location(-9.433333, 147.1)),
        PortCode("PG", "NAP", "Napa Napa", Location(-9.45, 147.116667)),
        PortCode("PG", "PDO", "Pondo Harbour", Location(-4.566667, 151.616667)),
        PortCode("PG", "POM", "Port Moresby", null),
        PortCode("PG", "RAB", "Rabaul", null),
        PortCode("PG", "RAM", "Rambutyo Island", null),
        PortCode("PG", "RKU", "Yule Island", null),
        PortCode("PG", "RNR", "Robinson River", null),
        PortCode("PG", "ROR", "Orobay", null),
        PortCode("PG", "RVI", "Russel Island", null),
        PortCode("PG", "SAI", "Saibai", Location(-9.383333, 142.616667)),
        PortCode("PG", "SCH", "Schauten", null),
        PortCode("PG", "SMU", "Salamaua", null),
        PortCode("PG", "SOI", "Sokar Island", null),
        PortCode("PG", "SPL", "Sipul", null),
        PortCode("PG", "SQT", "Samarai", Location(-10.633333, 150.633333)),
        PortCode("PG", "TAI", "Tambutyo Island", null),
        PortCode("PG", "TAM", "Tambanum", Location(-4.2, 143.6)),
        PortCode("PG", "TAU", "Taugu Island", null),
        PortCode("PG", "TFI", "Tufi", null),
        PortCode("PG", "TGL", "Tagula", null),
        PortCode("PG", "TLW", "Talasea", null),
        PortCode("PG", "TMI", "Tami Island", Location(-6.766667, 147.9)),
        PortCode("PG", "TOI", "Tolokiwa Island", null),
        PortCode("PG", "ULA", "Ulamona", Location(-5.0, 151.25)),
        PortCode("PG", "UNG", "Kiunga", null),
        PortCode("PG", "VAI", "Vanimo", null),
        PortCode("PG", "VLA", "Vailala", Location(-7.95, 145.45)),
        PortCode("PG", "WAT", "Watabung", Location(-6.083333, 145.216667)),
        PortCode("PG", "WOK", "Woodlark", null),
        PortCode("PG", "WWK", "Wewak", null),
        PortCode("PG", "YEN", "Yentchan", Location(-4.133333, 143.25))
    )
}
