package de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.ports

import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.PortCode
import de.visualdigits.common.domain.model.geodata.Location
                 
object PortsID {
    val PORTS: List<PortCode> = listOf(
        PortCode("ID", "ADB", "Adang Bay", null),
        PortCode("ID", "AGR", "Anggrek", Location(0.85, 122.783333)),
        PortCode("ID", "AJN", "Arjuna, Java", null),
        PortCode("ID", "AKE", "Akeselaka", Location(1.05, 127.966667)),
        PortCode("ID", "AMA", "Amamapare, Ij", null),
        PortCode("ID", "AMP", "Ampenan, Bali", null),
        PortCode("ID", "AMQ", "Ambon, Molucas", null),
        PortCode("ID", "ANG", "Angar", Location(-3.65, 130.833333)),
        PortCode("ID", "ANO", "Anoa Natuna Pt.", Location(5.233333, 105.6)),
        PortCode("ID", "ANR", "Anyer Kidul", Location(-6.066667, 105.883333)),
        PortCode("ID", "APN", "Ampana", Location(-0.866667, 121.583333)),
        PortCode("ID", "ARB", "Aroe Bay", null),
        PortCode("ID", "ASI", "Asike", Location(-6.65, 140.416667)),
        PortCode("ID", "AUN", "Arun", null),
        PortCode("ID", "BAK", "Batu Kilat", null),
        PortCode("ID", "BAL", "Balongan Terminal", Location(-6.383333, 108.4)),
        PortCode("ID", "BAM", "Batuampar", Location(-0.966667, 102.733333)),
        PortCode("ID", "BAP", "Batu Ampar", Location(-0.75, 109.533333)),
        PortCode("ID", "BDJ", "Banjarmasin", null),
        PortCode("ID", "BEK", "Bekapai Terminal", null),
        PortCode("ID", "BEN", "Benete", Location(-8.866667, 116.716667)),
        PortCode("ID", "BET", "Belida Terminal", Location(4.133333, 105.133333)),
        PortCode("ID", "BGD", "Bagendang", Location(-2.733333, 112.55)),
        PortCode("ID", "BGG", "Banggai", null),
        PortCode("ID", "BIK", "Biak, Irian Jaya", null),
        PortCode("ID", "BIR", "Biringkassi", Location(-4.816667, 119.483333)),
        PortCode("ID", "BIT", "Bitung, Sulawesi", null),
        PortCode("ID", "BJU", "Banjuwangi, Java", null),
        PortCode("ID", "BKS", "Bengkulu, Sumatra", null),
        PortCode("ID", "BLH", "Balohan", Location(5.816667, 95.333333)),
        PortCode("ID", "BLI", "Blinju, Banka", null),
        PortCode("ID", "BLL", "Blang Lancang, St", null),
        PortCode("ID", "BLT", "Belitung", Location(-2.833333, 107.916667)),
        PortCode("ID", "BLV", "Beliling", null),
        PortCode("ID", "BLW", "Belawan, Sumatra", null),
        PortCode("ID", "BMT", "Bima Terminal, Jv", null),
        PortCode("ID", "BMU", "Bima, Sb", null),
        PortCode("ID", "BNG", "Bonggala", null),
        PortCode("ID", "BNT", "Belanak Terminal", Location(4.166667, 106.233333)),
        PortCode("ID", "BOA", "Benoa", Location(-8.766667, 115.216667)),
        PortCode("ID", "BPN", "Balikpapan", Location(-1.283333, 116.833333)),
        PortCode("ID", "BTM", "Batam Island", Location(1.083333, 104.033333)),
        PortCode("ID", "BTN", "Banten", null),
        PortCode("ID", "BTW", "Batulicin", Location(-3.45, 115.983333)),
        PortCode("ID", "BUA", "Bula", null),
        PortCode("ID", "BUG", "Buleleng, Bali", null),
        PortCode("ID", "BUR", "Batu Ampar", Location(1.166667, 104.016667)),
        PortCode("ID", "BXT", "Bontang, Kl", null),
        PortCode("ID", "BYQ", "Bunyu", Location(3.5, 117.8)),
        PortCode("ID", "CBN", "Cirebon (Tjeribon)", Location(-6.733333, 108.566667)),
        PortCode("ID", "CEB", "Celukan Bawang, Bl", null),
        PortCode("ID", "CER", "Cereweh", Location(-8.816667, 116.816667)),
        PortCode("ID", "CIW", "Ciwandan", Location(-6.016667, 105.95)),
        PortCode("ID", "CSA", "Cape Sago", null),
        PortCode("ID", "CTO", "New Priok Port", Location(-6.083333, 106.916667)),
        PortCode("ID", "CXP", "Cilacap (Tjilatjap)", Location(-7.733333, 109.0)),
        PortCode("ID", "DAS", "Dabo, Singkep Isl", Location(-0.5, 104.55)),
        PortCode("ID", "DIV", "Diviematra", null),
        PortCode("ID", "DJA", "Djankar", null),
        PortCode("ID", "DJB", "Jambi, Sumatra", null),
        PortCode("ID", "DJJ", "Jayapura, Irian Jaya", Location(-2.533333, 140.7)),
        PortCode("ID", "DMA", "Demta", Location(-2.333333, 140.133333)),
        PortCode("ID", "DOB", "Dobo", Location(-5.75, 134.216667)),
        PortCode("ID", "DOG", "Donggi", Location(-1.533333, 122.25)),
        PortCode("ID", "DUM", "Dumai, Sumatra", null),
        PortCode("ID", "ELA", "Elat", Location(-5.65, 133.116667)),
        PortCode("ID", "ENO", "Kuala Enok", Location(-0.533333, 103.4)),
        PortCode("ID", "EXS", "Exspan", Location(-1.8, 105.133333)),
        PortCode("ID", "FKQ", "Fak Fak, Irian Jaya", null),
        PortCode("ID", "FTG", "Pelabuhan Futong Terminal", Location(0.816667, 102.4)),
        PortCode("ID", "GEE", "Gee Island", Location(0.833333, 128.316667)),
        PortCode("ID", "GIL", "Gilimanuk, Bali", null),
        PortCode("ID", "GNS", "Gunung Sitoli, St", null),
        PortCode("ID", "GRE", "Gresik, Java", Location(-7.15, 112.65)),
        PortCode("ID", "GTO", "Gorontalo, Sulawesi", null),
        PortCode("ID", "GTS", "Gatot Subroto Permai", Location(-8.633333, 115.2)),
        PortCode("ID", "IBT", "Indonesia Bulk Terminal", null),
        PortCode("ID", "INA", "Inanwatan", Location(-2.133333, 132.166667)),
        PortCode("ID", "JBK", "Jababeka", Location(-6.25, 107.15)),
        PortCode("ID", "JBT", "Jabung Terminal", Location(-0.883333, 104.066667)),
        PortCode("ID", "JEP", "Jepara", Location(-6.583333, 110.65)),
        PortCode("ID", "JIP", "Jogja Inland Port", Location(-7.9, 110.383333)),
        PortCode("ID", "JKT", "Jakarta, Java", Location(-6.133333, 106.833333)),
        PortCode("ID", "JOR", "Jorong Anchorage", Location(-4.183333, 115.1)),
        PortCode("ID", "JPU", "Jakarta Pusat", Location(-6.183333, 106.833333)),
        PortCode("ID", "JWA", "Jawa Timur", Location(-7.733333, 112.5)),
        PortCode("ID", "KAH", "Kahayan Bay", null),
        PortCode("ID", "KAM", "Kambunong, Celebes", null),
        PortCode("ID", "KAR", "Karosa, Sulawesi", null),
        PortCode("ID", "KAS", "Kasim, Ij", null),
        PortCode("ID", "KAU", "Kau", Location(1.183333, 127.9)),
        PortCode("ID", "KBH", "Kalabahi", Location(-8.216667, 124.516667)),
        PortCode("ID", "KDI", "Kendari, Sulawesi", null),
        PortCode("ID", "KDW", "Kendawangan", Location(-2.533333, 110.2)),
        PortCode("ID", "KEM", "Kempo, Sb", null),
        PortCode("ID", "KGH", "Krueng Geukueh", Location(5.25, 97.033333)),
        PortCode("ID", "KHY", "Kahyangan", Location(-8.483333, 116.666667)),
        PortCode("ID", "KID", "Kidjang, Bintan", null),
        PortCode("ID", "KKA", "Kuala Kapuas, Kl", null),
        PortCode("ID", "KKB", "Kunak, Borneo", null),
        PortCode("ID", "KMD", "Komodo", Location(-8.583333, 119.5)),
        PortCode("ID", "KNL", "Kolonodale", Location(-1.966667, 121.333333)),
        PortCode("ID", "KNT", "Kakap Natuna Terminal", Location(5.016667, 105.95)),
        PortCode("ID", "KOE", "Kupang, Timor", null),
        PortCode("ID", "KOJ", "Koja", Location(-6.3, 106.383333)),
        PortCode("ID", "KOK", "Kokas", Location(-2.7, 132.433333)),
        PortCode("ID", "KOL", "Kolaka", Location(-4.05, 121.566667)),
        PortCode("ID", "KPL", "Kampung Laut", Location(-0.9, 103.8)),
        PortCode("ID", "KPN", "Kotapinang, Baru", null),
        PortCode("ID", "KRG", "Kariangau", Location(-1.166667, 116.783333)),
        PortCode("ID", "KSE", "Kassue", Location(-6.983333, 139.216667)),
        PortCode("ID", "KSO", "Kalbut Situbondo", Location(-7.616667, 113.883333)),
        PortCode("ID", "KTG", "Ketapang, Kl", null),
        PortCode("ID", "KTJ", "Kualatanjung", Location(3.35, 99.483333)),
        PortCode("ID", "KUA", "Kualalangsa", Location(4.533333, 98.016667)),
        PortCode("ID", "KUM", "Kumai", Location(-2.733333, 111.716667)),
        PortCode("ID", "LAH", "Labuha, Molucas", Location(-0.616667, 127.483333)),
        PortCode("ID", "LAS", "Langsa, Sumatra", null),
        PortCode("ID", "LAT", "Lalang Terminal, St", null),
        PortCode("ID", "LBM", "Lobam", Location(1.0, 104.266667)),
        PortCode("ID", "LBO", "Labuan Bajo", Location(-8.5, 119.883333)),
        PortCode("ID", "LBR", "Lembar", Location(-8.733333, 116.066667)),
        PortCode("ID", "LIF", "Lifamatola", null),
        PortCode("ID", "LKI", "Loki", Location(-3.3, 128.05)),
        PortCode("ID", "LLA", "Lawe-Lawe, Kl", null),
        PortCode("ID", "LOM", "Lombok", Location(-8.5, 116.666667)),
        PortCode("ID", "LSW", "Lhokseumawe", Location(5.166667, 97.133333)),
        PortCode("ID", "LTT", "Lubuk Tutung", Location(0.766667, 117.733333)),
        PortCode("ID", "LUW", "Luwuk", null),
        PortCode("ID", "MAI", "Mapia Island", Location(0.883333, 134.316667)),
        PortCode("ID", "MAJ", "Majene, Sv", null),
        PortCode("ID", "MAK", "Makassar", Location(-5.116667, 119.4)),
        PortCode("ID", "MAL", "Mangole", null),
        PortCode("ID", "MAR", "Marabahan", Location(-2.983333, 114.766667)),
        PortCode("ID", "MBK", "Muara Bangkong", Location(0.4, 103.783333)),
        PortCode("ID", "MDC", "Manado", null),
        PortCode("ID", "MDR", "Madura Terminal", Location(-6.85, 112.95)),
        PortCode("ID", "MEQ", "Meulaboh, Sumatra", null),
        PortCode("ID", "MES", "Medan, Sumatra", null),
        PortCode("ID", "MGB", "Manggis", Location(-8.483333, 115.516667)),
        PortCode("ID", "MIT", "Misool Terminal", Location(-1.566667, 130.516667)),
        PortCode("ID", "MJU", "Mamuju", null),
        PortCode("ID", "MKJ", "Mangkajang", Location(2.133333, 117.733333)),
        PortCode("ID", "MKQ", "Merauke, Irian Jaya", null),
        PortCode("ID", "MKW", "Manokwari, Irian Jaya", null),
        PortCode("ID", "MLI", "Malili, Sulawesi", null),
        PortCode("ID", "MNT", "Mantang, Riau", null),
        PortCode("ID", "MOF", "Maumere, Flores", null),
        PortCode("ID", "MOR", "Mornopo", Location(0.783333, 128.216667)),
        PortCode("ID", "MOW", "Morowali", Location(-1.866667, 121.5)),
        PortCode("ID", "MPN", "Muara Pantai", null),
        PortCode("ID", "MRB", "Merantibunting, Sumatra", null),
        PortCode("ID", "MRI", "Musi River, Sumatra", null),
        PortCode("ID", "MRK", "Merak, Java", null),
        PortCode("ID", "MSB", "Muara Siberut", Location(-1.583333, 99.2)),
        PortCode("ID", "MSK", "Muara Sabak", Location(-0.8, 103.916667)),
        PortCode("ID", "MTU", "Muturi", null),
        PortCode("ID", "MUB", "Muara Berau", null),
        PortCode("ID", "MUD", "Muara Djawa", null),
        PortCode("ID", "MUO", "Muntok, Banka", null),
        PortCode("ID", "MUP", "Muara Pegah", null),
        PortCode("ID", "MUW", "Muara Teweh", Location(-56.966667, 114.9)),
        PortCode("ID", "NIP", "Nipah", Location(1.116667, 103.55)),
        PortCode("ID", "NNX", "Nunukan", null),
        PortCode("ID", "NPL", "North Pulau Laut", Location(-3.216667, 116.266667)),
        PortCode("ID", "OBI", "Obi Island", null),
        PortCode("ID", "OJA", "Olah Jasa Andal/Jakarta", null),
        PortCode("ID", "OLO", "Olee Lheue", null),
        PortCode("ID", "PAC", "Paciran", Location(-6.866667, 112.333333)),
        PortCode("ID", "PAG", "Pagatan, Kalimantan", null),
        PortCode("ID", "PAL", "Palu", Location(-0.883333, 119.85)),
        PortCode("ID", "PAS", "Pasir Panjang", null),
        PortCode("ID", "PAZ", "Pasuruan, Java", Location(-7.633333, 112.9)),
        PortCode("ID", "PBB", "Pelabuhan Badas", Location(-8.45, 117.366667)),
        PortCode("ID", "PBJ", "Pulau Bunyu", Location(-0.3, 115.866667)),
        PortCode("ID", "PDG", "Padang", Location(-0.95, 100.35)),
        PortCode("ID", "PDJ", "Tandjang", null),
        PortCode("ID", "PER", "Perawang", Location(1.066667, 102.866667)),
        PortCode("ID", "PEX", "Pekalongan, Java", null),
        PortCode("ID", "PGA", "Pagerungan", Location(-6.916667, 115.916667)),
        PortCode("ID", "PGK", "Pangkalpinang, Banka", null),
        PortCode("ID", "PGM", "Pagimana", Location(-0.8, 122.616667)),
        PortCode("ID", "PGX", "Pangkal Balam, Banka", null),
        PortCode("ID", "PIR", "Piru", Location(-3.066667, 128.183333)),
        PortCode("ID", "PJM", "Pandjung Mani", null),
        PortCode("ID", "PKN", "Pangkalanbuun", null),
        PortCode("ID", "PKR", "Pangkalan Brandan, Sumatra", null),
        PortCode("ID", "PKS", "Pangkalan Susu, Sumatra", null),
        PortCode("ID", "PLA", "Plaju, Sumatra", Location(-2.983333, 104.8)),
        PortCode("ID", "PLM", "Palembang, Sumatra", null),
        PortCode("ID", "PMG", "Port Meneng", null),
        PortCode("ID", "PMK", "Pomako", Location(-4.8, 136.766667)),
        PortCode("ID", "PNG", "Penuba", null),
        PortCode("ID", "PNJ", "Panjang", null),
        PortCode("ID", "PNK", "Pontianak, Kalimantan", null),
        PortCode("ID", "PNN", "Pamanukan, Java", null),
        PortCode("ID", "PNT", "Prointal, Jv", null),
        PortCode("ID", "POT", "Poto Tano", Location(-8.516667, 116.833333)),
        PortCode("ID", "PPO", "Palapo, Sulawesi", Location(-3.083333, 120.233333)),
        PortCode("ID", "PPS", "Pulangpisau", null),
        PortCode("ID", "PRN", "Panarukan, Java", null),
        PortCode("ID", "PRO", "Probolinggo, Java", null),
        PortCode("ID", "PSJ", "Poso, Sulawesi", null),
        PortCode("ID", "PSS", "Pulau Sambu, Riau", null),
        PortCode("ID", "PTK", "Padang Tikar", Location(-0.666667, 109.266667)),
        PortCode("ID", "PTL", "Pantoloan, Sv", null),
        PortCode("ID", "PUM", "Pomalaa, Sulawesi", Location(-4.033333, 121.583333)),
        PortCode("ID", "PUT", "Pulau Laut", Location(-3.283333, 116.15)),
        PortCode("ID", "PWG", "Perawang", Location(0.633333, 101.616667)),
        PortCode("ID", "REO", "Reo", Location(-8.316667, 120.5)),
        PortCode("ID", "RGT", "Rengat, Sumatra", null),
        PortCode("ID", "RNI", "Ranai", Location(3.916667, 108.383333)),
        PortCode("ID", "SAD", "Sadau, Borneo", null),
        PortCode("ID", "SAN", "Sanang, Celebes", null),
        PortCode("ID", "SAP", "Sape", Location(-8.566667, 118.983333)),
        PortCode("ID", "SAS", "Sasayap", null),
        PortCode("ID", "SAT", "Santan Terminal, Kl", null),
        PortCode("ID", "SBG", "Sabang, Sumatra", null),
        PortCode("ID", "SBM", "Subaim", Location(1.116667, 128.166667)),
        PortCode("ID", "SBS", "Sambas, Kalimantan", null),
        PortCode("ID", "SDA", "Durian", Location(1.016667, 103.566667)),
        PortCode("ID", "SDJ", "Sidoarjo", null),
        PortCode("ID", "SEB", "Sebangan Bay, Kalimantan", null),
        PortCode("ID", "SEP", "Sepanjang Terminal", Location(-7.183333, 115.783333)),
        PortCode("ID", "SEQ", "Sungai Pakning, Sumatra", null),
        PortCode("ID", "SGG", "Senggigi", Location(-8.5, 116.05)),
        PortCode("ID", "SGO", "Port Segoro Fajar Satryo/Jakarta", null),
        PortCode("ID", "SGU", "Sanggau", Location(0.116667, 110.6)),
        PortCode("ID", "SIA", "Siak Yechil, Riau", null),
        PortCode("ID", "SID", "Sidangoli", Location(0.9, 127.483333)),
        PortCode("ID", "SKI", "Sangkulirang, Kalimantan", null),
        PortCode("ID", "SKK", "Soengei Kolak", null),
        PortCode("ID", "SKP", "Sekupang", Location(1.133333, 103.933333)),
        PortCode("ID", "SKW", "Singkawang, Kalimantan", null),
        PortCode("ID", "SLG", "Sibolga, Sumatra", null),
        PortCode("ID", "SMB", "Semangka Bay, St", null),
        PortCode("ID", "SMQ", "Sampit, Kalimantan", null),
        PortCode("ID", "SNG", "Sinabang", null),
        PortCode("ID", "SOQ", "Sorong", null),
        PortCode("ID", "SPA", "Selat Pandjang, Sumatra", null),
        PortCode("ID", "SPH", "Senipah Terminal", null),
        PortCode("ID", "SRG", "Semarang", Location(-6.966667, 110.483333)),
        PortCode("ID", "SRI", "Samarinda, Kalimantan", null),
        PortCode("ID", "SSO", "Susu", null),
        PortCode("ID", "STN", "Setagin", Location(-3.283333, 116.166667)),
        PortCode("ID", "STU", "Satui", null),
        PortCode("ID", "SUA", "Suaran", Location(2.05, 117.7)),
        PortCode("ID", "SUB", "Surabaya", Location(-7.233333, 112.75)),
        PortCode("ID", "SUG", "Sungai Gerong, Sumatra", null),
        PortCode("ID", "SUK", "Sukabumi", Location(-65.85, 106.916667)),
        PortCode("ID", "SUM", "Sumenep", Location(-7.05, 113.95)),
        PortCode("ID", "SUN", "Sunut", Location(-8.866667, 116.55)),
        PortCode("ID", "SUP", "Sumenep, Madura", null),
        PortCode("ID", "SUQ", "Sungai Guntung, Sumatra", null),
        PortCode("ID", "SUS", "Susoh, Sumatra", null),
        PortCode("ID", "SWQ", "Sumbawa", null),
        PortCode("ID", "SWT", "Salawati Terminal", Location(-1.35, 131.0)),
        PortCode("ID", "SZA", "Cikande", Location(-6.2, 106.35)),
        PortCode("ID", "SZH", "Senipah", Location(-0.95, 117.15)),
        PortCode("ID", "TAB", "Taboneo", Location(-3.683333, 114.416667)),
        PortCode("ID", "TAL", "Tanah Laut", null),
        PortCode("ID", "TAN", "Tanjunguban", Location(1.05, 104.233333)),
        PortCode("ID", "TAR", "Tarjun", Location(-3.266667, 116.083333)),
        PortCode("ID", "TAX", "Taliabu Island Apt, Moluccas", null),
        PortCode("ID", "TBG", "Teluk Betung, Sumatra", null),
        PortCode("ID", "TBL", "Toboali", Location(-3.0, 106.5)),
        PortCode("ID", "TBN", "Tuban, Jv", null),
        PortCode("ID", "TBO", "Tobelo", null),
        PortCode("ID", "TBR", "Telukbayur", Location(-1.0, 100.366667)),
        PortCode("ID", "TBT", "Tandjung Batu, Riau", null),
        PortCode("ID", "TBU", "Tanjung Buli", Location(0.833333, 128.25)),
        PortCode("ID", "TEG", "Tegal, Java", null),
        PortCode("ID", "TER", "Terempa", Location(3.216667, 106.216667)),
        PortCode("ID", "TJB", "Tanjungbalai", Location(1.0, 103.433333)),
        PortCode("ID", "TJQ", "Tanjung Pandan", Location(-2.75, 107.65)),
        PortCode("ID", "TKA", "Telok Ayer, Kalimantan", null),
        PortCode("ID", "TLI", "Tolitoli", null),
        PortCode("ID", "TME", "Tanjung Merangas", Location(0.033333, 117.516667)),
        PortCode("ID", "TMK", "Timika", Location(-4.75, 136.55)),
        PortCode("ID", "TMO", "Telok Melano", null),
        PortCode("ID", "TNJ", "Tanjungpinang", Location(0.916667, 104.45)),
        PortCode("ID", "TPN", "Tanjung Pemancingan", Location(-3.183333, 116.266667)),
        PortCode("ID", "TRH", "Tarahan", Location(-5.566667, 105.366667)),
        PortCode("ID", "TRK", "Tarakan, Kalimantan", null),
        PortCode("ID", "TSE", "Tanjung Sekong, Jv", null),
        PortCode("ID", "TTE", "Ternate, Halmahera", null),
        PortCode("ID", "TUA", "Tual", Location(-5.633333, 132.733333)),
        PortCode("ID", "TZD", "Amurang", Location(1.166667, -124.566667)),
        PortCode("ID", "UDG", "Udang Natuna Terminal", Location(4.016667, 106.466667)),
        PortCode("ID", "UPG", "Ujung Pandang, Sulawesi", null),
        PortCode("ID", "UTC", "Jakarta UTC1", null),
        PortCode("ID", "UTE", "Jakarta UTC3", null),
        PortCode("ID", "WAI", "Wainibe", Location(-3.066667, 126.533333)),
        PortCode("ID", "WAN", "Wanam", Location(-7.55, 139.1)),
        PortCode("ID", "WED", "Weda", Location(0.333333, 127.883333)),
        PortCode("ID", "WGP", "Waingapu, Sumba", Location(-9.65, 120.266667)),
        PortCode("ID", "WSS", "Wamsasi", Location(-3.566667, 126.166667))
    )
}
