package de.visualdigits.shipermansfriend.domain.model

import de.visualdigits.shipermansfriend.domain.model.geodata.unlocode.Country
import org.junit.jupiter.api.Test
import java.io.File

//@Disabled("Only for local dev machine")
class RenameAnthems {

    @Test
    fun checkAnthems() {
        val rootDirectory = "E:\\Downloads\\Musik\\Nationalhymnen\\_copy"
        val anthems = File(rootDirectory)
            .listFiles { file -> file.isFile && file.name.endsWith(".mp3") }
            ?.map { file -> file.nameWithoutExtension }
            ?:listOf()
        val countries = Country.entries.toMutableList()
        countries.removeAll { country -> anthems.contains(country.prefix) }
        println(countries.sortedBy { country -> country.countryName }.joinToString("\n") { country -> "${country.countryName} [${country.prefix}]" })
    }

    @Test
    fun renameAnthems() {
        val rootDirectory = File("E:\\Downloads\\Musik\\Nationalhymnen\\_copy")

        File(rootDirectory, "Afghanistan.mp3").renameTo(File(rootDirectory, "af.mp3"))
        File(rootDirectory, "Albanien.mp3").renameTo(File(rootDirectory, "al.mp3"))
        File(rootDirectory, "Algerien.mp3").renameTo(File(rootDirectory, "dz.mp3"))
        File(rootDirectory, "Angola.mp3").renameTo(File(rootDirectory, "ao.mp3"))
        File(rootDirectory, "Antigua und Barbuda.mp3").renameTo(File(rootDirectory, "ag.mp3"))
        File(rootDirectory, "Argentinien.mp3").renameTo(File(rootDirectory, "ar.mp3"))
        File(rootDirectory, "Armenien.mp3").renameTo(File(rootDirectory, "am.mp3"))
        File(rootDirectory, "Aruba.mp3").renameTo(File(rootDirectory, "aw.mp3"))
        File(rootDirectory, "Aserbaidschan.mp3").renameTo(File(rootDirectory, "az.mp3"))
        File(rootDirectory, "Australien.mp3").renameTo(File(rootDirectory, "au.mp3"))
        File(rootDirectory, "Bahamas.mp3").renameTo(File(rootDirectory, "bs.mp3"))
        File(rootDirectory, "Bahrain.mp3").renameTo(File(rootDirectory, "bh.mp3"))
        File(rootDirectory, "Bangladesch.mp3").renameTo(File(rootDirectory, "bd.mp3"))
        File(rootDirectory, "Barbados.mp3").renameTo(File(rootDirectory, "bb.mp3"))
        File(rootDirectory, "Belgien.mp3").renameTo(File(rootDirectory, "be.mp3"))
        File(rootDirectory, "Belieze.mp3").renameTo(File(rootDirectory, "bz.mp3"))
        File(rootDirectory, "Benin.mp3").renameTo(File(rootDirectory, "bj.mp3"))
        File(rootDirectory, "Bolivien.mp3").renameTo(File(rootDirectory, "bo.mp3"))
        File(rootDirectory, "Bosnien und Herzegovina.mp3").renameTo(File(rootDirectory, "ba.mp3"))
        File(rootDirectory, "Botsuana.mp3").renameTo(File(rootDirectory, "bw.mp3"))
        File(rootDirectory, "Brasilien.mp3").renameTo(File(rootDirectory, "br.mp3"))
        File(rootDirectory, "Brunei.mp3").renameTo(File(rootDirectory, "bn.mp3"))
        File(rootDirectory, "Bulgarien.mp3").renameTo(File(rootDirectory, "bg.mp3"))
        File(rootDirectory, "Burkina-Faso.mp3").renameTo(File(rootDirectory, "bf.mp3"))
        File(rootDirectory, "Chile.mp3").renameTo(File(rootDirectory, "cl.mp3"))
        File(rootDirectory, "China.mp3").renameTo(File(rootDirectory, "cn.mp3"))
        File(rootDirectory, "Comoros.mp3").renameTo(File(rootDirectory, "km.mp3"))
        File(rootDirectory, "Cook Inseln.mp3").renameTo(File(rootDirectory, "ck.mp3"))
        File(rootDirectory, "Costa Rica.mp3").renameTo(File(rootDirectory, "cr.mp3"))
        File(rootDirectory, "Deutschland.mp3").renameTo(File(rootDirectory, "de.mp3"))
        File(rootDirectory, "Dominica.mp3").renameTo(File(rootDirectory, "dm.mp3"))
        File(rootDirectory, "Dominikanische Republik.mp3").renameTo(File(rootDirectory, "do.mp3"))
        File(rootDirectory, "Dschibuti.mp3").renameTo(File(rootDirectory, "dj.mp3"))
        File(rootDirectory, "Dänemark (National Anthem).mp3").renameTo(File(rootDirectory, "dk.mp3"))
        File(rootDirectory, "Ecuador.mp3").renameTo(File(rootDirectory, "ec.mp3"))
        File(rootDirectory, "El Salvador.mp3").renameTo(File(rootDirectory, "sv.mp3"))
        File(rootDirectory, "Elfenbeinküste.mp3").renameTo(File(rootDirectory, "ci.mp3"))
        File(rootDirectory, "Eritrea.mp3").renameTo(File(rootDirectory, "er.mp3"))
        File(rootDirectory, "Estland.mp3").renameTo(File(rootDirectory, "ee.mp3"))
        File(rootDirectory, "Fidschi.mp3").renameTo(File(rootDirectory, "fj.mp3"))
        File(rootDirectory, "Finnland.mp3").renameTo(File(rootDirectory, "fi.mp3"))
        File(rootDirectory, "Frankreich.mp3").renameTo(File(rootDirectory, "fr.mp3"))
        File(rootDirectory, "Gabun.mp3").renameTo(File(rootDirectory, "ga.mp3"))
        File(rootDirectory, "Gambia.mp3").renameTo(File(rootDirectory, "gm.mp3"))
        File(rootDirectory, "Georgien.mp3").renameTo(File(rootDirectory, "ge.mp3"))
        File(rootDirectory, "Ghana.mp3").renameTo(File(rootDirectory, "gh.mp3"))
        File(rootDirectory, "Griechenland.mp3").renameTo(File(rootDirectory, "gr.mp3"))
        File(rootDirectory, "Großbritannien.mp3").renameTo(File(rootDirectory, "gb.mp3"))
        File(rootDirectory, "Guatemala.mp3").renameTo(File(rootDirectory, "gt.mp3"))
        File(rootDirectory, "Guinea-Bissau.mp3").renameTo(File(rootDirectory, "gw.mp3"))
        File(rootDirectory, "Guinea.mp3").renameTo(File(rootDirectory, "gn.mp3"))
        File(rootDirectory, "Guyana.mp3").renameTo(File(rootDirectory, "gy.mp3"))
        File(rootDirectory, "Haiti.mp3").renameTo(File(rootDirectory, "ht.mp3"))
        File(rootDirectory, "Honduras.mp3").renameTo(File(rootDirectory, "hn.mp3"))
        File(rootDirectory, "Indien.mp3").renameTo(File(rootDirectory, "in.mp3"))
        File(rootDirectory, "Indonesien.mp3").renameTo(File(rootDirectory, "id.mp3"))
        File(rootDirectory, "Irak.mp3").renameTo(File(rootDirectory, "iq.mp3"))
        File(rootDirectory, "Irland.mp3").renameTo(File(rootDirectory, "ie.mp3"))
        File(rootDirectory, "Island.mp3").renameTo(File(rootDirectory, "is.mp3"))
        File(rootDirectory, "Israel.mp3").renameTo(File(rootDirectory, "il.mp3"))
        File(rootDirectory, "Italien.mp3").renameTo(File(rootDirectory, "it.mp3"))
        File(rootDirectory, "Jamaica.mp3").renameTo(File(rootDirectory, "jm.mp3"))
        File(rootDirectory, "Japan.mp3").renameTo(File(rootDirectory, "jp.mp3"))
        File(rootDirectory, "Jemen.mp3").renameTo(File(rootDirectory, "ye.mp3"))
        File(rootDirectory, "Jordanien.mp3").renameTo(File(rootDirectory, "jo.mp3"))
        // File(rootDirectory, "Jungferninseln.mp3").renameTo(File(rootDirectory, "xxx.mp3")) // nicht eindeutig (vg = britische / VI = Amerikanische)
        File(rootDirectory, "Kambodscha.mp3").renameTo(File(rootDirectory, "kh.mp3"))
        File(rootDirectory, "Kamerun.mp3").renameTo(File(rootDirectory, "cm.mp3"))
        File(rootDirectory, "Kanada.mp3").renameTo(File(rootDirectory, "ca.mp3"))
        File(rootDirectory, "Kap Verde.mp3").renameTo(File(rootDirectory, "cv.mp3"))
        File(rootDirectory, "Kasachstan.mp3").renameTo(File(rootDirectory, "kz.mp3"))
        File(rootDirectory, "Katar.mp3").renameTo(File(rootDirectory, "qa.mp3"))
        File(rootDirectory, "Kenya.mp3").renameTo(File(rootDirectory, "ke.mp3"))
        File(rootDirectory, "Kirgistan.mp3").renameTo(File(rootDirectory, "kg.mp3"))
        File(rootDirectory, "Kolumbien.mp3").renameTo(File(rootDirectory, "co.mp3"))
        File(rootDirectory, "Kongo.mp3").renameTo(File(rootDirectory, "cg.mp3")) // für die republik kongo. (demokratische republik Kongo wäre CD)
        File(rootDirectory, "Kroatien.mp3").renameTo(File(rootDirectory, "hr.mp3"))
        File(rootDirectory, "Kuba.mp3").renameTo(File(rootDirectory, "cu.mp3"))
        File(rootDirectory, "Kuwait.mp3").renameTo(File(rootDirectory, "kw.mp3"))
        File(rootDirectory, "Laos.mp3").renameTo(File(rootDirectory, "la.mp3"))
        File(rootDirectory, "Lettland.mp3").renameTo(File(rootDirectory, "lv.mp3"))
        File(rootDirectory, "Libanon.mp3").renameTo(File(rootDirectory, "lb.mp3"))
        File(rootDirectory, "Liberia.mp3").renameTo(File(rootDirectory, "lr.mp3"))
        File(rootDirectory, "Liechtenstein.mp3").renameTo(File(rootDirectory, "li.mp3"))
        File(rootDirectory, "Litauen.mp3").renameTo(File(rootDirectory, "lt.mp3"))
        File(rootDirectory, "Luxemburg.mp3").renameTo(File(rootDirectory, "lu.mp3"))

        File(rootDirectory, "Madagascar.mp3").renameTo(File(rootDirectory, "mg.mp3"))
        File(rootDirectory, "Malawi.mp3").renameTo(File(rootDirectory, "mw.mp3"))
        File(rootDirectory, "Malaysia.mp3").renameTo(File(rootDirectory, "my.mp3"))
        File(rootDirectory, "Malediven.mp3").renameTo(File(rootDirectory, "mv.mp3"))
        File(rootDirectory, "Malta.mp3").renameTo(File(rootDirectory, "mt.mp3"))
        File(rootDirectory, "Marokko.mp3").renameTo(File(rootDirectory, "ma.mp3"))
        File(rootDirectory, "Marshallinseln.mp3").renameTo(File(rootDirectory, "mh.mp3"))
        File(rootDirectory, "Mauritanien.mp3").renameTo(File(rootDirectory, "mr.mp3"))
        File(rootDirectory, "Mauritius.mp3").renameTo(File(rootDirectory, "mu.mp3"))
        File(rootDirectory, "Mazedonien.mp3").renameTo(File(rootDirectory, "mk.mp3")) // nordmazedonien
        File(rootDirectory, "Mexiko.mp3").renameTo(File(rootDirectory, "mx.mp3"))
        File(rootDirectory, "Mikronesien.mp3").renameTo(File(rootDirectory, "fm.mp3"))
        File(rootDirectory, "Moldavien.mp3").renameTo(File(rootDirectory, "md.mp3"))
        File(rootDirectory, "Monaco.mp3").renameTo(File(rootDirectory, "mc.mp3"))
        File(rootDirectory, "Montenegro.mp3").renameTo(File(rootDirectory, "me.mp3"))
        File(rootDirectory, "Myanmar.mp3").renameTo(File(rootDirectory, "mm.mp3"))
        File(rootDirectory, "Namibia.mp3").renameTo(File(rootDirectory, "na.mp3"))
        File(rootDirectory, "Nepal.mp3").renameTo(File(rootDirectory, "np.mp3"))
        File(rootDirectory, "Neuseeland (God Defend New Zealand).mp3").renameTo(File(rootDirectory, "nz.mp3"))
        File(rootDirectory, "Nicaragua.mp3").renameTo(File(rootDirectory, "ni.mp3"))
        File(rootDirectory, "Niederlande.mp3").renameTo(File(rootDirectory, "nl.mp3"))
        File(rootDirectory, "Nigeria.mp3").renameTo(File(rootDirectory, "ng.mp3"))
        File(rootDirectory, "Norwegen.mp3").renameTo(File(rootDirectory, "no.mp3"))
        File(rootDirectory, "Oman.mp3").renameTo(File(rootDirectory, "om.mp3"))
        File(rootDirectory, "Osttimor.mp3").renameTo(File(rootDirectory, "tl.mp3"))
        File(rootDirectory, "Pakistan.mp3").renameTo(File(rootDirectory, "pk.mp3"))
        File(rootDirectory, "Palau.mp3").renameTo(File(rootDirectory, "pw.mp3"))
        File(rootDirectory, "Panama.mp3").renameTo(File(rootDirectory, "pa.mp3"))
        File(rootDirectory, "Papua-Neuguinea.mp3").renameTo(File(rootDirectory, "pg.mp3"))
        File(rootDirectory, "Paraguay.mp3").renameTo(File(rootDirectory, "py.mp3"))
        File(rootDirectory, "Peru.mp3").renameTo(File(rootDirectory, "pe.mp3"))
        File(rootDirectory, "Phillipinen.mp3").renameTo(File(rootDirectory, "ph.mp3"))
        File(rootDirectory, "Polen.mp3").renameTo(File(rootDirectory, "pl.mp3"))
        File(rootDirectory, "Portugal.mp3").renameTo(File(rootDirectory, "pt.mp3"))
        File(rootDirectory, "Puerto Rico.mp3").renameTo(File(rootDirectory, "pr.mp3"))
        File(rootDirectory, "Ruanda.mp3").renameTo(File(rootDirectory, "rw.mp3"))
        File(rootDirectory, "Rumänien.mp3").renameTo(File(rootDirectory, "ro.mp3"))
        File(rootDirectory, "Russland.mp3").renameTo(File(rootDirectory, "ru.mp3"))
        File(rootDirectory, "Sao Tome and Principe.mp3").renameTo(File(rootDirectory, "st.mp3"))
        File(rootDirectory, "Saudi Arabien.mp3").renameTo(File(rootDirectory, "sa.mp3"))
        File(rootDirectory, "Schweden.mp3").renameTo(File(rootDirectory, "se.mp3"))
        File(rootDirectory, "Schweiz.mp3").renameTo(File(rootDirectory, "ch.mp3"))
        File(rootDirectory, "Senegal.mp3").renameTo(File(rootDirectory, "sn.mp3"))
        File(rootDirectory, "Serbien.mp3").renameTo(File(rootDirectory, "rs.mp3"))
        File(rootDirectory, "Seychellen.mp3").renameTo(File(rootDirectory, "sc.mp3"))
        File(rootDirectory, "Sierra Leone.mp3").renameTo(File(rootDirectory, "sl.mp3"))
        File(rootDirectory, "Singapur.mp3").renameTo(File(rootDirectory, "sg.mp3"))
        File(rootDirectory, "Slovenien.mp3").renameTo(File(rootDirectory, "si.mp3"))
        File(rootDirectory, "Slowakische Republik.mp3").renameTo(File(rootDirectory, "sk.mp3"))
        File(rootDirectory, "Spanien.mp3").renameTo(File(rootDirectory, "es.mp3"))
        File(rootDirectory, "Sri Lanka.mp3").renameTo(File(rootDirectory, "lk.mp3"))
        File(rootDirectory, "St. Kitt's and Nevis.mp3").renameTo(File(rootDirectory, "kn.mp3"))
        File(rootDirectory, "Sudan.mp3").renameTo(File(rootDirectory, "sd.mp3"))
        File(rootDirectory, "Swasiland.mp3").renameTo(File(rootDirectory, "sz.mp3")) // eswatini
        File(rootDirectory, "Syrien.mp3").renameTo(File(rootDirectory, "sy.mp3"))
        File(rootDirectory, "Südafrika.mp3").renameTo(File(rootDirectory, "za.mp3"))
        File(rootDirectory, "Südkorea.mp3").renameTo(File(rootDirectory, "kr.mp3"))
        File(rootDirectory, "Tansania.mp3").renameTo(File(rootDirectory, "tz.mp3"))
        File(rootDirectory, "Thailand.mp3").renameTo(File(rootDirectory, "th.mp3"))
        File(rootDirectory, "Togo.mp3").renameTo(File(rootDirectory, "tg.mp3"))
        File(rootDirectory, "Trinidad & Tobago.mp3").renameTo(File(rootDirectory, "tt.mp3"))
        File(rootDirectory, "Tschechische Republik.mp3").renameTo(File(rootDirectory, "cz.mp3"))
        File(rootDirectory, "Tunisien.mp3").renameTo(File(rootDirectory, "tn.mp3"))
        File(rootDirectory, "Turkmenistan.mp3").renameTo(File(rootDirectory, "tm.mp3"))
        File(rootDirectory, "Türkei.mp3").renameTo(File(rootDirectory, "tr.mp3"))
        File(rootDirectory, "USA.mp3").renameTo(File(rootDirectory, "us.mp3"))
        File(rootDirectory, "Ukraine.mp3").renameTo(File(rootDirectory, "ua.mp3"))
        File(rootDirectory, "Ungarn.mp3").renameTo(File(rootDirectory, "hu.mp3"))
        File(rootDirectory, "Uruguay.mp3").renameTo(File(rootDirectory, "uy.mp3"))
        File(rootDirectory, "Usbekistan.mp3").renameTo(File(rootDirectory, "uz.mp3"))
        File(rootDirectory, "Vanuatu.mp3").renameTo(File(rootDirectory, "vu.mp3"))
        File(rootDirectory, "Venezuela.mp3").renameTo(File(rootDirectory, "ve.mp3"))
        File(rootDirectory, "Vereinigte Arabische Emirate.mp3").renameTo(File(rootDirectory, "ae.mp3"))
        File(rootDirectory, "Vietnam.mp3").renameTo(File(rootDirectory, "vn.mp3"))
        File(rootDirectory, "Weißrussland.mp3").renameTo(File(rootDirectory, "by.mp3"))
        File(rootDirectory, "Zentralafrikanische Republik.mp3").renameTo(File(rootDirectory, "cf.mp3"))
        File(rootDirectory, "Ägypten.mp3").renameTo(File(rootDirectory, "eg.mp3"))
        File(rootDirectory, "Äthiopien.mp3").renameTo(File(rootDirectory, "et.mp3"))
        File(rootDirectory, "Österreich.mp3").renameTo(File(rootDirectory, "at.mp3"))


    }
}
