package de.visualdigits.shipermansfriend.domain.model

import org.junit.jupiter.api.Test
import java.io.File

class RenameAnthemsTest {

    @Test
    fun renameAnthems() {
        val rootDirectory = File("E:\\Downloads\\Musik\\Nationalhymnen\\_copy")

        File(rootDirectory, "Afghanistan.mp3").renameTo(File(rootDirectory, "AF.mp3"))
        File(rootDirectory, "Albanien.mp3").renameTo(File(rootDirectory, "AL.mp3"))
        File(rootDirectory, "Algerien.mp3").renameTo(File(rootDirectory, "DZ.mp3"))
        File(rootDirectory, "Angola.mp3").renameTo(File(rootDirectory, "AO.mp3"))
        File(rootDirectory, "Antigua und Barbuda.mp3").renameTo(File(rootDirectory, "AG.mp3"))
        File(rootDirectory, "Argentinien.mp3").renameTo(File(rootDirectory, "AR.mp3"))
        File(rootDirectory, "Armenien.mp3").renameTo(File(rootDirectory, "AM.mp3"))
        File(rootDirectory, "Aruba.mp3").renameTo(File(rootDirectory, "AW.mp3"))
        File(rootDirectory, "Aserbaidschan.mp3").renameTo(File(rootDirectory, "AZ.mp3"))
        File(rootDirectory, "Australien.mp3").renameTo(File(rootDirectory, "AU.mp3"))
        File(rootDirectory, "Bahamas.mp3").renameTo(File(rootDirectory, "BS.mp3"))
        File(rootDirectory, "Bahrain.mp3").renameTo(File(rootDirectory, "BH.mp3"))
        File(rootDirectory, "Bangladesch.mp3").renameTo(File(rootDirectory, "BD.mp3"))
        File(rootDirectory, "Barbados.mp3").renameTo(File(rootDirectory, "BB.mp3"))
        File(rootDirectory, "Belgien.mp3").renameTo(File(rootDirectory, "BE.mp3"))
        File(rootDirectory, "Belieze.mp3").renameTo(File(rootDirectory, "BZ.mp3")) // Tippfehler im Original (Belize)
        File(rootDirectory, "Benin.mp3").renameTo(File(rootDirectory, "BJ.mp3"))
        File(rootDirectory, "Bolivien.mp3").renameTo(File(rootDirectory, "BO.mp3"))
        File(rootDirectory, "Bosnien und Herzegovina.mp3").renameTo(File(rootDirectory, "BA.mp3"))
        File(rootDirectory, "Botsuana.mp3").renameTo(File(rootDirectory, "BW.mp3"))
        File(rootDirectory, "Brasilien.mp3").renameTo(File(rootDirectory, "BR.mp3"))
        File(rootDirectory, "Brunei.mp3").renameTo(File(rootDirectory, "BN.mp3"))
        File(rootDirectory, "Bulgarien.mp3").renameTo(File(rootDirectory, "BG.mp3"))
        File(rootDirectory, "Burkina-Faso.mp3").renameTo(File(rootDirectory, "BF.mp3"))
        File(rootDirectory, "Chile.mp3").renameTo(File(rootDirectory, "CL.mp3"))
        File(rootDirectory, "China.mp3").renameTo(File(rootDirectory, "CN.mp3"))
        File(rootDirectory, "Comoros.mp3").renameTo(File(rootDirectory, "KM.mp3"))
        File(rootDirectory, "Cook Inseln.mp3").renameTo(File(rootDirectory, "CK.mp3"))
        File(rootDirectory, "Costa Rica.mp3").renameTo(File(rootDirectory, "CR.mp3"))
        File(rootDirectory, "Deutschland.mp3").renameTo(File(rootDirectory, "DE.mp3"))
        File(rootDirectory, "Dominica.mp3").renameTo(File(rootDirectory, "DM.mp3"))
        File(rootDirectory, "Dominikanische Republik.mp3").renameTo(File(rootDirectory, "DO.mp3"))
        File(rootDirectory, "Dschibuti.mp3").renameTo(File(rootDirectory, "DJ.mp3"))
        File(rootDirectory, "Dänemark (National Anthem).mp3").renameTo(File(rootDirectory, "DK.mp3"))
        File(rootDirectory, "Ecuador.mp3").renameTo(File(rootDirectory, "EC.mp3"))
        File(rootDirectory, "El Salvador.mp3").renameTo(File(rootDirectory, "SV.mp3"))
        File(rootDirectory, "Elfenbeinküste.mp3").renameTo(File(rootDirectory, "CI.mp3"))
        File(rootDirectory, "Eritrea.mp3").renameTo(File(rootDirectory, "ER.mp3"))
        File(rootDirectory, "Estland.mp3").renameTo(File(rootDirectory, "EE.mp3"))
        File(rootDirectory, "Fidschi.mp3").renameTo(File(rootDirectory, "FJ.mp3"))
        File(rootDirectory, "Finnland.mp3").renameTo(File(rootDirectory, "FI.mp3"))
        File(rootDirectory, "Frankreich.mp3").renameTo(File(rootDirectory, "FR.mp3"))
        File(rootDirectory, "Gabun.mp3").renameTo(File(rootDirectory, "GA.mp3"))
        File(rootDirectory, "Gambia.mp3").renameTo(File(rootDirectory, "GM.mp3"))
        File(rootDirectory, "Georgien.mp3").renameTo(File(rootDirectory, "GE.mp3"))
        File(rootDirectory, "Ghana.mp3").renameTo(File(rootDirectory, "GH.mp3"))
        File(rootDirectory, "Griechenland.mp3").renameTo(File(rootDirectory, "GR.mp3"))
        File(rootDirectory, "Großbritannien.mp3").renameTo(File(rootDirectory, "GB.mp3"))
        File(rootDirectory, "Guatemala.mp3").renameTo(File(rootDirectory, "GT.mp3"))
        File(rootDirectory, "Guinea-Bissau.mp3").renameTo(File(rootDirectory, "GW.mp3"))
        File(rootDirectory, "Guinea.mp3").renameTo(File(rootDirectory, "GN.mp3"))
        File(rootDirectory, "Guyana.mp3").renameTo(File(rootDirectory, "GY.mp3"))
        File(rootDirectory, "Haiti.mp3").renameTo(File(rootDirectory, "HT.mp3"))
        File(rootDirectory, "Honduras.mp3").renameTo(File(rootDirectory, "HN.mp3"))
        File(rootDirectory, "Indien.mp3").renameTo(File(rootDirectory, "IN.mp3"))
        File(rootDirectory, "Indonesien.mp3").renameTo(File(rootDirectory, "ID.mp3"))
        File(rootDirectory, "Irak.mp3").renameTo(File(rootDirectory, "IQ.mp3"))
        File(rootDirectory, "Irland.mp3").renameTo(File(rootDirectory, "IE.mp3"))
        File(rootDirectory, "Island.mp3").renameTo(File(rootDirectory, "IS.mp3"))
        File(rootDirectory, "Israel.mp3").renameTo(File(rootDirectory, "IL.mp3"))
        File(rootDirectory, "Italien.mp3").renameTo(File(rootDirectory, "IT.mp3"))
        File(rootDirectory, "Jamaica.mp3").renameTo(File(rootDirectory, "JM.mp3"))
        File(rootDirectory, "Japan.mp3").renameTo(File(rootDirectory, "JP.mp3"))
        File(rootDirectory, "Jemen.mp3").renameTo(File(rootDirectory, "YE.mp3"))
        File(rootDirectory, "Jordanien.mp3").renameTo(File(rootDirectory, "JO.mp3"))
        // File(rootDirectory, "Jungferninseln.mp3").renameTo(File(rootDirectory, "xxx.mp3")) // Nicht eindeutig (VG = Britische / VI = Amerikanische)
        File(rootDirectory, "Kambodscha.mp3").renameTo(File(rootDirectory, "KH.mp3"))
        File(rootDirectory, "Kamerun.mp3").renameTo(File(rootDirectory, "CM.mp3"))
        File(rootDirectory, "Kanada.mp3").renameTo(File(rootDirectory, "CA.mp3"))
        File(rootDirectory, "Kap Verde.mp3").renameTo(File(rootDirectory, "CV.mp3"))
        File(rootDirectory, "Kasachstan.mp3").renameTo(File(rootDirectory, "KZ.mp3"))
        File(rootDirectory, "Katar.mp3").renameTo(File(rootDirectory, "QA.mp3"))
        File(rootDirectory, "Kenya.mp3").renameTo(File(rootDirectory, "KE.mp3"))
        File(rootDirectory, "Kirgistan.mp3").renameTo(File(rootDirectory, "KG.mp3"))
        File(rootDirectory, "Kolumbien.mp3").renameTo(File(rootDirectory, "CO.mp3"))
        File(rootDirectory, "Kongo.mp3").renameTo(File(rootDirectory, "CG.mp3")) // Für die Republik Kongo. (Demokratische Republik Kongo wäre CD)
        File(rootDirectory, "Kroatien.mp3").renameTo(File(rootDirectory, "HR.mp3"))
        File(rootDirectory, "Kuba.mp3").renameTo(File(rootDirectory, "CU.mp3"))
        File(rootDirectory, "Kuwait.mp3").renameTo(File(rootDirectory, "KW.mp3"))
        File(rootDirectory, "Laos.mp3").renameTo(File(rootDirectory, "LA.mp3"))
        File(rootDirectory, "Lettland.mp3").renameTo(File(rootDirectory, "LV.mp3"))
        File(rootDirectory, "Libanon.mp3").renameTo(File(rootDirectory, "LB.mp3"))
        File(rootDirectory, "Liberia.mp3").renameTo(File(rootDirectory, "LR.mp3"))
        File(rootDirectory, "Liechtenstein.mp3").renameTo(File(rootDirectory, "LI.mp3"))
        File(rootDirectory, "Litauen.mp3").renameTo(File(rootDirectory, "LT.mp3"))
        File(rootDirectory, "Luxemburg.mp3").renameTo(File(rootDirectory, "LU.mp3"))

        File(rootDirectory, "Madagascar.mp3").renameTo(File(rootDirectory, "MG.mp3"))
        File(rootDirectory, "Malawi.mp3").renameTo(File(rootDirectory, "MW.mp3"))
        File(rootDirectory, "Malaysia.mp3").renameTo(File(rootDirectory, "MY.mp3"))
        File(rootDirectory, "Malediven.mp3").renameTo(File(rootDirectory, "MV.mp3"))
        File(rootDirectory, "Malta.mp3").renameTo(File(rootDirectory, "MT.mp3"))
        File(rootDirectory, "Marokko.mp3").renameTo(File(rootDirectory, "MA.mp3"))
        File(rootDirectory, "Marshallinseln.mp3").renameTo(File(rootDirectory, "MH.mp3"))
        File(rootDirectory, "Mauritanien.mp3").renameTo(File(rootDirectory, "MR.mp3"))
        File(rootDirectory, "Mauritius.mp3").renameTo(File(rootDirectory, "MU.mp3"))
        File(rootDirectory, "Mazedonien.mp3").renameTo(File(rootDirectory, "MK.mp3")) // Nordmazedonien
        File(rootDirectory, "Mexiko.mp3").renameTo(File(rootDirectory, "MX.mp3"))
        File(rootDirectory, "Mikronesien.mp3").renameTo(File(rootDirectory, "FM.mp3"))
        File(rootDirectory, "Moldavien.mp3").renameTo(File(rootDirectory, "MD.mp3"))
        File(rootDirectory, "Monaco.mp3").renameTo(File(rootDirectory, "MC.mp3"))
        File(rootDirectory, "Montenegro.mp3").renameTo(File(rootDirectory, "ME.mp3"))
        File(rootDirectory, "Myanmar.mp3").renameTo(File(rootDirectory, "MM.mp3"))
        File(rootDirectory, "Namibia.mp3").renameTo(File(rootDirectory, "NA.mp3"))
        File(rootDirectory, "Nepal.mp3").renameTo(File(rootDirectory, "NP.mp3"))
        File(rootDirectory, "Neuseeland (God Defend New Zealand).mp3").renameTo(File(rootDirectory, "NZ.mp3"))
        File(rootDirectory, "Nicaragua.mp3").renameTo(File(rootDirectory, "NI.mp3"))
        File(rootDirectory, "Niederlande.mp3").renameTo(File(rootDirectory, "NL.mp3"))
        File(rootDirectory, "Nigeria.mp3").renameTo(File(rootDirectory, "NG.mp3"))
        File(rootDirectory, "Norwegen.mp3").renameTo(File(rootDirectory, "NO.mp3"))
        File(rootDirectory, "Oman.mp3").renameTo(File(rootDirectory, "OM.mp3"))
        File(rootDirectory, "Osttimor.mp3").renameTo(File(rootDirectory, "TL.mp3"))
        File(rootDirectory, "Pakistan.mp3").renameTo(File(rootDirectory, "PK.mp3"))
        File(rootDirectory, "Palau.mp3").renameTo(File(rootDirectory, "PW.mp3"))
        File(rootDirectory, "Panama.mp3").renameTo(File(rootDirectory, "PA.mp3"))
        File(rootDirectory, "Papua-Neuguinea.mp3").renameTo(File(rootDirectory, "PG.mp3"))
        File(rootDirectory, "Paraguay.mp3").renameTo(File(rootDirectory, "PY.mp3"))
        File(rootDirectory, "Peru.mp3").renameTo(File(rootDirectory, "PE.mp3"))
        File(rootDirectory, "Phillipinen.mp3").renameTo(File(rootDirectory, "PH.mp3"))
        File(rootDirectory, "Polen.mp3").renameTo(File(rootDirectory, "PL.mp3"))
        File(rootDirectory, "Portugal.mp3").renameTo(File(rootDirectory, "PT.mp3"))
        File(rootDirectory, "Puerto Rico.mp3").renameTo(File(rootDirectory, "PR.mp3"))
        File(rootDirectory, "Ruanda.mp3").renameTo(File(rootDirectory, "RW.mp3"))
        File(rootDirectory, "Rumänien.mp3").renameTo(File(rootDirectory, "RO.mp3"))
        File(rootDirectory, "Russland.mp3").renameTo(File(rootDirectory, "RU.mp3"))
        File(rootDirectory, "Sao Tome and Principe.mp3").renameTo(File(rootDirectory, "ST.mp3"))
        File(rootDirectory, "Saudi Arabien.mp3").renameTo(File(rootDirectory, "SA.mp3"))
        File(rootDirectory, "Schweden.mp3").renameTo(File(rootDirectory, "SE.mp3"))
        File(rootDirectory, "Schweiz.mp3").renameTo(File(rootDirectory, "CH.mp3"))
        File(rootDirectory, "Senegal.mp3").renameTo(File(rootDirectory, "SN.mp3"))
        File(rootDirectory, "Serbien.mp3").renameTo(File(rootDirectory, "RS.mp3"))
        File(rootDirectory, "Seychellen.mp3").renameTo(File(rootDirectory, "SC.mp3"))
        File(rootDirectory, "Sierra Leone.mp3").renameTo(File(rootDirectory, "SL.mp3"))
        File(rootDirectory, "Singapur.mp3").renameTo(File(rootDirectory, "SG.mp3"))
        File(rootDirectory, "Slovenien.mp3").renameTo(File(rootDirectory, "SI.mp3"))
        File(rootDirectory, "Slowakische Republik.mp3").renameTo(File(rootDirectory, "SK.mp3"))
        File(rootDirectory, "Spanien.mp3").renameTo(File(rootDirectory, "ES.mp3"))
        File(rootDirectory, "Sri Lanka.mp3").renameTo(File(rootDirectory, "LK.mp3"))
        File(rootDirectory, "St. Kitt's and Nevis.mp3").renameTo(File(rootDirectory, "KN.mp3"))
        File(rootDirectory, "Sudan.mp3").renameTo(File(rootDirectory, "SD.mp3"))
        File(rootDirectory, "Swasiland.mp3").renameTo(File(rootDirectory, "SZ.mp3")) // Eswatini
        File(rootDirectory, "Syrien.mp3").renameTo(File(rootDirectory, "SY.mp3"))
        File(rootDirectory, "Südafrika.mp3").renameTo(File(rootDirectory, "ZA.mp3"))
        File(rootDirectory, "Südkorea.mp3").renameTo(File(rootDirectory, "KR.mp3"))
        File(rootDirectory, "Tansania.mp3").renameTo(File(rootDirectory, "TZ.mp3"))
        File(rootDirectory, "Thailand.mp3").renameTo(File(rootDirectory, "TH.mp3"))
        File(rootDirectory, "Togo.mp3").renameTo(File(rootDirectory, "TG.mp3"))
        File(rootDirectory, "Trinidad & Tobago.mp3").renameTo(File(rootDirectory, "TT.mp3"))
        File(rootDirectory, "Tschechische Republik.mp3").renameTo(File(rootDirectory, "CZ.mp3"))
        File(rootDirectory, "Tunisien.mp3").renameTo(File(rootDirectory, "TN.mp3"))
        File(rootDirectory, "Turkmenistan.mp3").renameTo(File(rootDirectory, "TM.mp3"))
        File(rootDirectory, "Türkei.mp3").renameTo(File(rootDirectory, "TR.mp3"))
        File(rootDirectory, "USA.mp3").renameTo(File(rootDirectory, "US.mp3"))
        File(rootDirectory, "Ukraine.mp3").renameTo(File(rootDirectory, "UA.mp3"))
        File(rootDirectory, "Ungarn.mp3").renameTo(File(rootDirectory, "HU.mp3"))
        File(rootDirectory, "Uruguay.mp3").renameTo(File(rootDirectory, "UY.mp3"))
        File(rootDirectory, "Usbekistan.mp3").renameTo(File(rootDirectory, "UZ.mp3"))
        File(rootDirectory, "Vanuatu.mp3").renameTo(File(rootDirectory, "VU.mp3"))
        File(rootDirectory, "Venezuela.mp3").renameTo(File(rootDirectory, "VE.mp3"))
        File(rootDirectory, "Vereinigte Arabische Emirate.mp3").renameTo(File(rootDirectory, "AE.mp3"))
        File(rootDirectory, "Vietnam.mp3").renameTo(File(rootDirectory, "VN.mp3"))
        File(rootDirectory, "Weißrussland.mp3").renameTo(File(rootDirectory, "BY.mp3"))
        File(rootDirectory, "Zentralafrikanische Republik.mp3").renameTo(File(rootDirectory, "CF.mp3"))
        File(rootDirectory, "Ägypten.mp3").renameTo(File(rootDirectory, "EG.mp3"))
        File(rootDirectory, "Äthiopien.mp3").renameTo(File(rootDirectory, "ET.mp3"))
        File(rootDirectory, "Österreich.mp3").renameTo(File(rootDirectory, "AT.mp3"))


    }
}
